// Class: ReadkMLP_pca_ce_200_2x_n-6
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_pca_ce_200_2x_n-6
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Tue Oct 15 12:15:10 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/hades/user/knowakow/PP/FAT/TMVA/L1520
Training events: 128231
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "200" [Number of training cycles]
HiddenLayers: "N-6,N-6" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N,P" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 17
oa_lambda                     oa_lambda                     oa_lambda                     oa_lambda                     deg                               'F'    [0.0262573082,179.981933594]
eVert_x                       eVert_x                       eVert_x                       eVert_x                       mm                                'F'    [-293.690185547,208.465637207]
eVert_y                       eVert_y                       eVert_y                       eVert_y                       mm                                'F'    [-181.513931274,223.032836914]
eVert_z                       eVert_z                       eVert_z                       eVert_z                       mm                                'F'    [-430.539245605,656.647888184]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-6614.59179688,18386.5273438]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-4248.56591797,6396.78417969]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-24060.0410156,11815.3623047]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-1543.90686035,2392.25366211]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-2087.46826172,1862.33325195]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-8150.22900391,3973.37231445]
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [0.000280363572529,555.603942871]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [0.000110681634396,541.141479492]
dist_p_eVert                  dist_p_eVert                  dist_p_eVert                  dist_p_eVert                  mm                                'F'    [0.0253113750368,380.341186523]
dist_pim_eVert                dist_pim_eVert                dist_pim_eVert                dist_pim_eVert                mm                                'F'    [0.00962274055928,456.076324463]
dist_lambda_eVert             dist_lambda_eVert             dist_lambda_eVert             dist_lambda_eVert             mm                                'F'    [0.0268057268113,348.131011963]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.0355898067355,25382.5605469]
m_inv_p_pim                   m_inv_p_pim                   m_inv_p_pim                   m_inv_p_pim                   MeV                               'F'    [1077.86279297,1597.13977051]
NSpec 1
m_inv_p_pim_pip_pim           m_inv_p_pim_pip_pim           m_inv_p_pim_pip_pim           m_inv_p_pim_pip_pim           MeV                               'F'    [1365.29125977,2552.95336914]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_pca_ce_200_2x_n-6 : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_pca_ce_200_2x_n-6( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_pca_ce_200_2x_n-6" ),
        fNvars( 17 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "oa_lambda", "eVert_x", "eVert_y", "eVert_z", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "dist_p_pim", "dist_pip_pim", "dist_p_eVert", "dist_pim_eVert", "dist_lambda_eVert", "dist_lambda_ver_pip_pim", "m_inv_p_pim" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.899706482887268;
      fVmax[0] = 1.1273101568222;
      fVmin[1] = -2.88245820999146;
      fVmax[1] = 0.142200708389282;
      fVmin[2] = -1.80198955535889;
      fVmax[2] = 0.19768488407135;
      fVmin[3] = -0.546818554401398;
      fVmax[3] = 1.91513824462891;
      fVmin[4] = -1.57039618492126;
      fVmax[4] = 0.645590543746948;
      fVmin[5] = -0.65726226568222;
      fVmax[5] = 1.21592092514038;
      fVmin[6] = -1.54520285129547;
      fVmax[6] = 1.29598891735077;
      fVmin[7] = -1.20148098468781;
      fVmax[7] = 0.664354860782623;
      fVmin[8] = -0.780640125274658;
      fVmax[8] = 0.925257742404938;
      fVmin[9] = -1.73409724235535;
      fVmax[9] = 0.886555671691895;
      fVmin[10] = -1.02324628829956;
      fVmax[10] = 0.987686157226562;
      fVmin[11] = -0.928509950637817;
      fVmax[11] = 0.723447144031525;
      fVmin[12] = -2.05605387687683;
      fVmax[12] = 1.20969951152802;
      fVmin[13] = -0.574679374694824;
      fVmax[13] = 0.406969487667084;
      fVmin[14] = -2.21619582176208;
      fVmax[14] = 0.0324645526707172;
      fVmin[15] = -0.395964711904526;
      fVmax[15] = 0.488712519407272;
      fVmin[16] = -0.624663650989532;
      fVmax[16] = 0.224274173378944;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_pca_ce_200_2x_n-6() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][17];
   double fMax_1[3][17];

   void X2P_2( const double*, double*, int ) const;
   double fMeanValues_2[3][17];
   double fEigenVectors_2[3][17][17];

   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[17];
   double fVmax[17];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[17];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[12][18];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadkMLP_pca_ce_200_2x_n-6::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 18; fWeights[0] = new double[18]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.62319406969165;
   fWeightMatrix0to1[1][0] = 2.30283780344041;
   fWeightMatrix0to1[2][0] = -0.373914944650267;
   fWeightMatrix0to1[3][0] = 1.49744725331998;
   fWeightMatrix0to1[4][0] = -3.58270401597562;
   fWeightMatrix0to1[5][0] = -3.57969855687495;
   fWeightMatrix0to1[6][0] = 1.49242963893734;
   fWeightMatrix0to1[7][0] = -1.35354975609819;
   fWeightMatrix0to1[8][0] = -0.887014945242642;
   fWeightMatrix0to1[9][0] = -1.08207509932667;
   fWeightMatrix0to1[10][0] = 1.67307304135835;
   fWeightMatrix0to1[0][1] = -3.35246370565042;
   fWeightMatrix0to1[1][1] = -0.886167882788001;
   fWeightMatrix0to1[2][1] = -5.82526563518865;
   fWeightMatrix0to1[3][1] = -2.16236692119753;
   fWeightMatrix0to1[4][1] = 0.566435438516413;
   fWeightMatrix0to1[5][1] = -1.06499833999565;
   fWeightMatrix0to1[6][1] = 7.07706580054863;
   fWeightMatrix0to1[7][1] = 1.60298746465377;
   fWeightMatrix0to1[8][1] = 6.63974881001841;
   fWeightMatrix0to1[9][1] = 1.47364109573099;
   fWeightMatrix0to1[10][1] = 1.88232033367399;
   fWeightMatrix0to1[0][2] = -0.563462856082193;
   fWeightMatrix0to1[1][2] = 7.59796866415708;
   fWeightMatrix0to1[2][2] = -14.9883775962728;
   fWeightMatrix0to1[3][2] = -0.781041571924063;
   fWeightMatrix0to1[4][2] = 0.174084743287805;
   fWeightMatrix0to1[5][2] = 0.557578577286894;
   fWeightMatrix0to1[6][2] = -14.2398521062395;
   fWeightMatrix0to1[7][2] = 0.179056187915529;
   fWeightMatrix0to1[8][2] = -1.67166778265038;
   fWeightMatrix0to1[9][2] = 13.5252531751325;
   fWeightMatrix0to1[10][2] = 5.98364608782394;
   fWeightMatrix0to1[0][3] = -0.42376879881858;
   fWeightMatrix0to1[1][3] = 0.109887724461911;
   fWeightMatrix0to1[2][3] = -0.72309301329573;
   fWeightMatrix0to1[3][3] = -0.678638986654393;
   fWeightMatrix0to1[4][3] = 2.79899915654532;
   fWeightMatrix0to1[5][3] = -1.066028127032;
   fWeightMatrix0to1[6][3] = 0.0792021865707153;
   fWeightMatrix0to1[7][3] = 1.43368711007593;
   fWeightMatrix0to1[8][3] = 0.266386122938157;
   fWeightMatrix0to1[9][3] = 1.210161846585;
   fWeightMatrix0to1[10][3] = -0.222505793079451;
   fWeightMatrix0to1[0][4] = -2.66924263771696;
   fWeightMatrix0to1[1][4] = -1.69289506919107;
   fWeightMatrix0to1[2][4] = -2.16561610804056;
   fWeightMatrix0to1[3][4] = 0.679619549614097;
   fWeightMatrix0to1[4][4] = 1.00135604534271;
   fWeightMatrix0to1[5][4] = 1.41000148074254;
   fWeightMatrix0to1[6][4] = 3.6825411616782;
   fWeightMatrix0to1[7][4] = 3.37135251230017;
   fWeightMatrix0to1[8][4] = -6.92772529243158;
   fWeightMatrix0to1[9][4] = -0.155850420372515;
   fWeightMatrix0to1[10][4] = -2.6162725658886;
   fWeightMatrix0to1[0][5] = -1.3018397366709;
   fWeightMatrix0to1[1][5] = -2.15088693044191;
   fWeightMatrix0to1[2][5] = 1.77609823733471;
   fWeightMatrix0to1[3][5] = 2.20842875744765;
   fWeightMatrix0to1[4][5] = 0.576422282280724;
   fWeightMatrix0to1[5][5] = -0.572418171114767;
   fWeightMatrix0to1[6][5] = 0.55572208167153;
   fWeightMatrix0to1[7][5] = -1.6625788976233;
   fWeightMatrix0to1[8][5] = 3.53828461117147;
   fWeightMatrix0to1[9][5] = 1.61794431011653;
   fWeightMatrix0to1[10][5] = -3.09159125668414;
   fWeightMatrix0to1[0][6] = -0.619164721136822;
   fWeightMatrix0to1[1][6] = -0.474208165933992;
   fWeightMatrix0to1[2][6] = -0.393088109610321;
   fWeightMatrix0to1[3][6] = -1.12504914371749;
   fWeightMatrix0to1[4][6] = -0.282707330339143;
   fWeightMatrix0to1[5][6] = -1.30495081181084;
   fWeightMatrix0to1[6][6] = -0.250342010712738;
   fWeightMatrix0to1[7][6] = 0.360193501390954;
   fWeightMatrix0to1[8][6] = 2.78540463332487;
   fWeightMatrix0to1[9][6] = 0.50019658355824;
   fWeightMatrix0to1[10][6] = -1.55811981167228;
   fWeightMatrix0to1[0][7] = -1.64545660129833;
   fWeightMatrix0to1[1][7] = 1.76230113169794;
   fWeightMatrix0to1[2][7] = 1.92276281434037;
   fWeightMatrix0to1[3][7] = 2.15573947439273;
   fWeightMatrix0to1[4][7] = 0.811703520595389;
   fWeightMatrix0to1[5][7] = 1.59168703872062;
   fWeightMatrix0to1[6][7] = 0.00729303553852644;
   fWeightMatrix0to1[7][7] = -0.992686888512927;
   fWeightMatrix0to1[8][7] = -1.23125499277287;
   fWeightMatrix0to1[9][7] = 0.635361925430426;
   fWeightMatrix0to1[10][7] = -1.65508210226657;
   fWeightMatrix0to1[0][8] = -2.90345548455829;
   fWeightMatrix0to1[1][8] = -1.23287568046456;
   fWeightMatrix0to1[2][8] = 0.0782107187000631;
   fWeightMatrix0to1[3][8] = -0.259557033586804;
   fWeightMatrix0to1[4][8] = 1.33213276497256;
   fWeightMatrix0to1[5][8] = -1.72704529198236;
   fWeightMatrix0to1[6][8] = -2.24387451521401;
   fWeightMatrix0to1[7][8] = 0.929074190161471;
   fWeightMatrix0to1[8][8] = 1.5088705963292;
   fWeightMatrix0to1[9][8] = 0.20174548557401;
   fWeightMatrix0to1[10][8] = -1.00465571556059;
   fWeightMatrix0to1[0][9] = 0.22412981830622;
   fWeightMatrix0to1[1][9] = -1.67334382871;
   fWeightMatrix0to1[2][9] = -0.96008659215517;
   fWeightMatrix0to1[3][9] = 0.972644749086048;
   fWeightMatrix0to1[4][9] = 1.51952665794784;
   fWeightMatrix0to1[5][9] = -0.97962465675563;
   fWeightMatrix0to1[6][9] = 1.92109901457449;
   fWeightMatrix0to1[7][9] = -0.5429258402003;
   fWeightMatrix0to1[8][9] = -2.25806270612864;
   fWeightMatrix0to1[9][9] = -1.1107567662528;
   fWeightMatrix0to1[10][9] = -0.0492171001353854;
   fWeightMatrix0to1[0][10] = -2.412444179218;
   fWeightMatrix0to1[1][10] = -0.109254746148912;
   fWeightMatrix0to1[2][10] = 0.695073775957551;
   fWeightMatrix0to1[3][10] = 0.439680780402362;
   fWeightMatrix0to1[4][10] = -1.52238001044817;
   fWeightMatrix0to1[5][10] = 1.61101791767602;
   fWeightMatrix0to1[6][10] = 0.30073923584949;
   fWeightMatrix0to1[7][10] = -1.12722989647032;
   fWeightMatrix0to1[8][10] = 1.66847716866168;
   fWeightMatrix0to1[9][10] = -1.40409646374427;
   fWeightMatrix0to1[10][10] = -1.40909464534014;
   fWeightMatrix0to1[0][11] = 0.456729679922703;
   fWeightMatrix0to1[1][11] = -0.331369715999957;
   fWeightMatrix0to1[2][11] = 1.84812841299718;
   fWeightMatrix0to1[3][11] = 0.725083700253952;
   fWeightMatrix0to1[4][11] = -0.0557953828834989;
   fWeightMatrix0to1[5][11] = -0.00190585162685538;
   fWeightMatrix0to1[6][11] = -0.681350656304398;
   fWeightMatrix0to1[7][11] = -1.88724217828321;
   fWeightMatrix0to1[8][11] = -0.435303597450912;
   fWeightMatrix0to1[9][11] = 0.278916909120957;
   fWeightMatrix0to1[10][11] = -1.57098349931921;
   fWeightMatrix0to1[0][12] = 1.32163856635848;
   fWeightMatrix0to1[1][12] = -1.40289745326226;
   fWeightMatrix0to1[2][12] = -0.916042760567817;
   fWeightMatrix0to1[3][12] = 1.25761224605524;
   fWeightMatrix0to1[4][12] = 1.8818812947721;
   fWeightMatrix0to1[5][12] = -1.72374624703491;
   fWeightMatrix0to1[6][12] = 0.605919528431276;
   fWeightMatrix0to1[7][12] = 2.06319720725038;
   fWeightMatrix0to1[8][12] = -0.89768311828745;
   fWeightMatrix0to1[9][12] = -0.154268634033918;
   fWeightMatrix0to1[10][12] = -1.38380394076631;
   fWeightMatrix0to1[0][13] = -0.646096729532565;
   fWeightMatrix0to1[1][13] = -1.37357936178596;
   fWeightMatrix0to1[2][13] = 3.00507501115627;
   fWeightMatrix0to1[3][13] = 1.00926180834576;
   fWeightMatrix0to1[4][13] = -0.611361145140111;
   fWeightMatrix0to1[5][13] = -0.660030957730891;
   fWeightMatrix0to1[6][13] = -0.621969373604451;
   fWeightMatrix0to1[7][13] = -2.29352068946937;
   fWeightMatrix0to1[8][13] = 4.74606886283755;
   fWeightMatrix0to1[9][13] = 2.5869778376216;
   fWeightMatrix0to1[10][13] = -0.724832832421794;
   fWeightMatrix0to1[0][14] = -1.30764205813916;
   fWeightMatrix0to1[1][14] = 0.387797590864975;
   fWeightMatrix0to1[2][14] = 1.68924550079776;
   fWeightMatrix0to1[3][14] = 0.514271233464547;
   fWeightMatrix0to1[4][14] = 0.661329036051642;
   fWeightMatrix0to1[5][14] = -1.66054473660083;
   fWeightMatrix0to1[6][14] = 1.11553516936547;
   fWeightMatrix0to1[7][14] = 0.385049327211929;
   fWeightMatrix0to1[8][14] = 2.59364117040424;
   fWeightMatrix0to1[9][14] = 1.03589178889089;
   fWeightMatrix0to1[10][14] = 1.18622267318242;
   fWeightMatrix0to1[0][15] = -0.000355398630804661;
   fWeightMatrix0to1[1][15] = -0.774253711377712;
   fWeightMatrix0to1[2][15] = 0.577041065770983;
   fWeightMatrix0to1[3][15] = -0.917720577865497;
   fWeightMatrix0to1[4][15] = -0.333644602068436;
   fWeightMatrix0to1[5][15] = 1.63175704834912;
   fWeightMatrix0to1[6][15] = 1.35972692188341;
   fWeightMatrix0to1[7][15] = -0.0600515054366935;
   fWeightMatrix0to1[8][15] = -0.170008228923293;
   fWeightMatrix0to1[9][15] = 1.37385023853056;
   fWeightMatrix0to1[10][15] = -2.09049883154781;
   fWeightMatrix0to1[0][16] = 0.53104173767402;
   fWeightMatrix0to1[1][16] = 0.0381963882845204;
   fWeightMatrix0to1[2][16] = 0.40127618826076;
   fWeightMatrix0to1[3][16] = -1.71649765034955;
   fWeightMatrix0to1[4][16] = -1.60903680465368;
   fWeightMatrix0to1[5][16] = 1.19426152633932;
   fWeightMatrix0to1[6][16] = 1.49626009395547;
   fWeightMatrix0to1[7][16] = -1.78464251275739;
   fWeightMatrix0to1[8][16] = 0.305341544401139;
   fWeightMatrix0to1[9][16] = -0.244937578692264;
   fWeightMatrix0to1[10][16] = 0.390944597392214;
   fWeightMatrix0to1[0][17] = -0.169059580663674;
   fWeightMatrix0to1[1][17] = -0.369557805263904;
   fWeightMatrix0to1[2][17] = 1.46308802503416;
   fWeightMatrix0to1[3][17] = -1.76349027661918;
   fWeightMatrix0to1[4][17] = 0.127532875436872;
   fWeightMatrix0to1[5][17] = -2.81165550992536;
   fWeightMatrix0to1[6][17] = -0.238141658035721;
   fWeightMatrix0to1[7][17] = -1.16125502877604;
   fWeightMatrix0to1[8][17] = -1.88324342463112;
   fWeightMatrix0to1[9][17] = -0.364445867578436;
   fWeightMatrix0to1[10][17] = -1.89460257644521;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.09269749305515;
   fWeightMatrix1to2[1][0] = -2.24377823692626;
   fWeightMatrix1to2[2][0] = -0.699569848199361;
   fWeightMatrix1to2[3][0] = 0.802966274799988;
   fWeightMatrix1to2[4][0] = 0.213440465651914;
   fWeightMatrix1to2[5][0] = -1.28822189306472;
   fWeightMatrix1to2[6][0] = 2.6213752391381;
   fWeightMatrix1to2[7][0] = 1.27111475003458;
   fWeightMatrix1to2[8][0] = -0.0236169863744358;
   fWeightMatrix1to2[9][0] = -0.11963275466698;
   fWeightMatrix1to2[10][0] = 1.51535805013371;
   fWeightMatrix1to2[0][1] = 5.05381623408198;
   fWeightMatrix1to2[1][1] = -0.176571400644077;
   fWeightMatrix1to2[2][1] = 0.0670052729874184;
   fWeightMatrix1to2[3][1] = -4.59464802902502;
   fWeightMatrix1to2[4][1] = -1.09329809347433;
   fWeightMatrix1to2[5][1] = 3.94837097043419;
   fWeightMatrix1to2[6][1] = 1.92767735308497;
   fWeightMatrix1to2[7][1] = 1.28832498459215;
   fWeightMatrix1to2[8][1] = 0.661529361915463;
   fWeightMatrix1to2[9][1] = 1.95530385124805;
   fWeightMatrix1to2[10][1] = -1.98310768538381;
   fWeightMatrix1to2[0][2] = -8.02790321319774;
   fWeightMatrix1to2[1][2] = 2.16971596841053;
   fWeightMatrix1to2[2][2] = -1.97331003837012;
   fWeightMatrix1to2[3][2] = 2.75102705778162;
   fWeightMatrix1to2[4][2] = 1.74568520588229;
   fWeightMatrix1to2[5][2] = -9.10657406454482;
   fWeightMatrix1to2[6][2] = -1.82546762625862;
   fWeightMatrix1to2[7][2] = 5.12812814676299;
   fWeightMatrix1to2[8][2] = -3.75225088279164;
   fWeightMatrix1to2[9][2] = -1.07663978871708;
   fWeightMatrix1to2[10][2] = 0.331960617429692;
   fWeightMatrix1to2[0][3] = -0.28162094751793;
   fWeightMatrix1to2[1][3] = 0.603432853303665;
   fWeightMatrix1to2[2][3] = -1.21582203931752;
   fWeightMatrix1to2[3][3] = 2.01235509339457;
   fWeightMatrix1to2[4][3] = -1.81638441739794;
   fWeightMatrix1to2[5][3] = -1.14218213279848;
   fWeightMatrix1to2[6][3] = 0.273868703317052;
   fWeightMatrix1to2[7][3] = -1.41627949712799;
   fWeightMatrix1to2[8][3] = -2.23885261126113;
   fWeightMatrix1to2[9][3] = -1.93190838790922;
   fWeightMatrix1to2[10][3] = -0.595326299789269;
   fWeightMatrix1to2[0][4] = 0.834293637322273;
   fWeightMatrix1to2[1][4] = -0.774221633046498;
   fWeightMatrix1to2[2][4] = -1.48081539660475;
   fWeightMatrix1to2[3][4] = 0.872413034995336;
   fWeightMatrix1to2[4][4] = -1.10186688055912;
   fWeightMatrix1to2[5][4] = -0.976252935098303;
   fWeightMatrix1to2[6][4] = 0.658020623943042;
   fWeightMatrix1to2[7][4] = -2.75977948230526;
   fWeightMatrix1to2[8][4] = 0.670053503766255;
   fWeightMatrix1to2[9][4] = -1.05254466247979;
   fWeightMatrix1to2[10][4] = 0.0389779857058876;
   fWeightMatrix1to2[0][5] = 2.35037955781529;
   fWeightMatrix1to2[1][5] = 2.9919260465547;
   fWeightMatrix1to2[2][5] = -0.77762117915622;
   fWeightMatrix1to2[3][5] = -0.793617919980923;
   fWeightMatrix1to2[4][5] = -1.1411613518472;
   fWeightMatrix1to2[5][5] = -1.67932538946618;
   fWeightMatrix1to2[6][5] = -2.6756743411302;
   fWeightMatrix1to2[7][5] = -0.324339949883169;
   fWeightMatrix1to2[8][5] = -0.410563632199925;
   fWeightMatrix1to2[9][5] = 1.90705538147937;
   fWeightMatrix1to2[10][5] = -0.605074704727632;
   fWeightMatrix1to2[0][6] = -7.77360223616129;
   fWeightMatrix1to2[1][6] = -2.72931781105309;
   fWeightMatrix1to2[2][6] = -2.36983628954357;
   fWeightMatrix1to2[3][6] = 4.41905020095212;
   fWeightMatrix1to2[4][6] = 1.11989518013815;
   fWeightMatrix1to2[5][6] = -8.2908896704096;
   fWeightMatrix1to2[6][6] = 0.598335587547392;
   fWeightMatrix1to2[7][6] = 0.346481025711857;
   fWeightMatrix1to2[8][6] = 2.7306763946818;
   fWeightMatrix1to2[9][6] = 0.406063336203507;
   fWeightMatrix1to2[10][6] = -0.928277199051755;
   fWeightMatrix1to2[0][7] = 0.108609496559997;
   fWeightMatrix1to2[1][7] = 0.898222761783696;
   fWeightMatrix1to2[2][7] = 1.12163379579867;
   fWeightMatrix1to2[3][7] = 1.51136821283772;
   fWeightMatrix1to2[4][7] = -0.368514704834684;
   fWeightMatrix1to2[5][7] = 0.976874871533352;
   fWeightMatrix1to2[6][7] = 0.0168736123977197;
   fWeightMatrix1to2[7][7] = -3.28131270052081;
   fWeightMatrix1to2[8][7] = 0.147031044217175;
   fWeightMatrix1to2[9][7] = -1.78195384752722;
   fWeightMatrix1to2[10][7] = -1.74963996336073;
   fWeightMatrix1to2[0][8] = -5.87943852942901;
   fWeightMatrix1to2[1][8] = 1.53835875867162;
   fWeightMatrix1to2[2][8] = -1.61830350209705;
   fWeightMatrix1to2[3][8] = 1.11646802663716;
   fWeightMatrix1to2[4][8] = -1.45636263221953;
   fWeightMatrix1to2[5][8] = 3.60924386525974;
   fWeightMatrix1to2[6][8] = -0.607611882419836;
   fWeightMatrix1to2[7][8] = 2.09466497622236;
   fWeightMatrix1to2[8][8] = 1.53365894792333;
   fWeightMatrix1to2[9][8] = -1.86489931234797;
   fWeightMatrix1to2[10][8] = -0.216278582833718;
   fWeightMatrix1to2[0][9] = 6.71490438111493;
   fWeightMatrix1to2[1][9] = -1.75280270097685;
   fWeightMatrix1to2[2][9] = -0.755963957051473;
   fWeightMatrix1to2[3][9] = -5.8787326313765;
   fWeightMatrix1to2[4][9] = -1.05227329757321;
   fWeightMatrix1to2[5][9] = 7.38772449057757;
   fWeightMatrix1to2[6][9] = -1.29894933870417;
   fWeightMatrix1to2[7][9] = -1.64121996722788;
   fWeightMatrix1to2[8][9] = -0.929211527086923;
   fWeightMatrix1to2[9][9] = -1.1842750503455;
   fWeightMatrix1to2[10][9] = -1.33426553807294;
   fWeightMatrix1to2[0][10] = 2.19871138636842;
   fWeightMatrix1to2[1][10] = -1.75087106160822;
   fWeightMatrix1to2[2][10] = 1.22125306100842;
   fWeightMatrix1to2[3][10] = -2.6272500045537;
   fWeightMatrix1to2[4][10] = -1.34553189508175;
   fWeightMatrix1to2[5][10] = 5.61132703816967;
   fWeightMatrix1to2[6][10] = 0.505419867254588;
   fWeightMatrix1to2[7][10] = -2.09890289066951;
   fWeightMatrix1to2[8][10] = 2.37998649680884;
   fWeightMatrix1to2[9][10] = -1.80383709212153;
   fWeightMatrix1to2[10][10] = 1.44870260090544;
   fWeightMatrix1to2[0][11] = -0.801053931863069;
   fWeightMatrix1to2[1][11] = -1.00389935249515;
   fWeightMatrix1to2[2][11] = -0.792779028656193;
   fWeightMatrix1to2[3][11] = -1.27170363535625;
   fWeightMatrix1to2[4][11] = -1.36132715233716;
   fWeightMatrix1to2[5][11] = 2.55511432747279;
   fWeightMatrix1to2[6][11] = 1.54983316960296;
   fWeightMatrix1to2[7][11] = 1.83827083826852;
   fWeightMatrix1to2[8][11] = 1.61888382367409;
   fWeightMatrix1to2[9][11] = -1.40307648108024;
   fWeightMatrix1to2[10][11] = 0.474041538352043;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -8.02641111164903;
   fWeightMatrix2to3[0][1] = 1.99414850651269;
   fWeightMatrix2to3[0][2] = -1.70064354330982;
   fWeightMatrix2to3[0][3] = -5.01342197532475;
   fWeightMatrix2to3[0][4] = -0.528454506785619;
   fWeightMatrix2to3[0][5] = 6.30832090253819;
   fWeightMatrix2to3[0][6] = -2.22468351928399;
   fWeightMatrix2to3[0][7] = 4.60603111973215;
   fWeightMatrix2to3[0][8] = -2.69641020348684;
   fWeightMatrix2to3[0][9] = 0.0327676691442826;
   fWeightMatrix2to3[0][10] = -0.65266320865497;
   fWeightMatrix2to3[0][11] = -1.80053424546906;
}

inline double ReadkMLP_pca_ce_200_2x_n-6::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadkMLP_pca_ce_200_2x_n-6::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_pca_ce_200_2x_n-6::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_pca_ce_200_2x_n-6::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_pca_ce_200_2x_n-6::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0332721285522;
   fMax_1[0][0] = 178.970367432;
   fMin_1[1][0] = 0.0262573082;
   fMax_1[1][0] = 179.981933594;
   fMin_1[2][0] = 0.0262573082;
   fMax_1[2][0] = 179.981933594;
   fMin_1[0][1] = -150.329376221;
   fMax_1[0][1] = 93.4167098999;
   fMin_1[1][1] = -293.690185547;
   fMax_1[1][1] = 208.465637207;
   fMin_1[2][1] = -293.690185547;
   fMax_1[2][1] = 208.465637207;
   fMin_1[0][2] = -85.1814880371;
   fMax_1[0][2] = 91.9362564087;
   fMin_1[1][2] = -181.513931274;
   fMax_1[1][2] = 223.032836914;
   fMin_1[2][2] = -181.513931274;
   fMax_1[2][2] = 223.032836914;
   fMin_1[0][3] = -88.257484436;
   fMax_1[0][3] = 615.460083008;
   fMin_1[1][3] = -430.539245605;
   fMax_1[1][3] = 656.647888184;
   fMin_1[2][3] = -430.539245605;
   fMax_1[2][3] = 656.647888184;
   fMin_1[0][4] = -706.857299805;
   fMax_1[0][4] = 497.002258301;
   fMin_1[1][4] = -6614.59179688;
   fMax_1[1][4] = 18386.5273438;
   fMin_1[2][4] = -6614.59179688;
   fMax_1[2][4] = 18386.5273438;
   fMin_1[0][5] = -585.357055664;
   fMax_1[0][5] = 1342.75866699;
   fMin_1[1][5] = -4248.56591797;
   fMax_1[1][5] = 6396.78417969;
   fMin_1[2][5] = -4248.56591797;
   fMax_1[2][5] = 6396.78417969;
   fMin_1[0][6] = -3003.76855469;
   fMax_1[0][6] = 1475.4354248;
   fMin_1[1][6] = -24060.0410156;
   fMax_1[1][6] = 11815.3623047;
   fMin_1[2][6] = -24060.0410156;
   fMax_1[2][6] = 11815.3623047;
   fMin_1[0][7] = -486.255828857;
   fMax_1[0][7] = 381.600860596;
   fMin_1[1][7] = -1543.90686035;
   fMax_1[1][7] = 2392.25366211;
   fMin_1[2][7] = -1543.90686035;
   fMax_1[2][7] = 2392.25366211;
   fMin_1[0][8] = -299.277679443;
   fMax_1[0][8] = 191.735321045;
   fMin_1[1][8] = -2087.46826172;
   fMax_1[1][8] = 1862.33325195;
   fMin_1[2][8] = -2087.46826172;
   fMax_1[2][8] = 1862.33325195;
   fMin_1[0][9] = -1266.26794434;
   fMax_1[0][9] = 1493.03039551;
   fMin_1[1][9] = -8150.22900391;
   fMax_1[1][9] = 3973.37231445;
   fMin_1[2][9] = -8150.22900391;
   fMax_1[2][9] = 3973.37231445;
   fMin_1[0][10] = 0.000485499767819;
   fMax_1[0][10] = 345.236175537;
   fMin_1[1][10] = 0.000280363572529;
   fMax_1[1][10] = 555.603942871;
   fMin_1[2][10] = 0.000280363572529;
   fMax_1[2][10] = 555.603942871;
   fMin_1[0][11] = 0.00537627376616;
   fMax_1[0][11] = 416.967773438;
   fMin_1[1][11] = 0.000110681634396;
   fMax_1[1][11] = 541.141479492;
   fMin_1[2][11] = 0.000110681634396;
   fMax_1[2][11] = 541.141479492;
   fMin_1[0][12] = 0.0531640574336;
   fMax_1[0][12] = 168.213058472;
   fMin_1[1][12] = 0.0253113750368;
   fMax_1[1][12] = 380.341186523;
   fMin_1[2][12] = 0.0253113750368;
   fMax_1[2][12] = 380.341186523;
   fMin_1[0][13] = 0.0619826391339;
   fMax_1[0][13] = 176.90246582;
   fMin_1[1][13] = 0.00962274055928;
   fMax_1[1][13] = 456.076324463;
   fMin_1[2][13] = 0.00962274055928;
   fMax_1[2][13] = 456.076324463;
   fMin_1[0][14] = 0.0888017490506;
   fMax_1[0][14] = 164.691986084;
   fMin_1[1][14] = 0.0268057268113;
   fMax_1[1][14] = 348.131011963;
   fMin_1[2][14] = 0.0268057268113;
   fMax_1[2][14] = 348.131011963;
   fMin_1[0][15] = 0.121199041605;
   fMax_1[0][15] = 2383.80834961;
   fMin_1[1][15] = 0.0355898067355;
   fMax_1[1][15] = 25382.5605469;
   fMin_1[2][15] = 0.0355898067355;
   fMax_1[2][15] = 25382.5605469;
   fMin_1[0][16] = 1080.18322754;
   fMax_1[0][16] = 1221.71618652;
   fMin_1[1][16] = 1077.86279297;
   fMax_1[1][16] = 1597.13977051;
   fMin_1[2][16] = 1077.86279297;
   fMax_1[2][16] = 1597.13977051;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 17;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<17;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::X2P_2( const double* x, double* p, int index ) const
{
   // Calculate the principal components from the original data vector
   // x, and return it in p (function extracted from TPrincipal::X2P)
   // It's the users responsibility to make sure that both x and p are
   // of the right size (i.e., memory must be allocated for p).
   const int nVar = 17;

   for (int i = 0; i < nVar; i++) {
      p[i] = 0;
      for (int j = 0; j < nVar; j++) p[i] += (x[j] - fMeanValues_2[index][j]) * fEigenVectors_2[index][j][i];
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::InitTransform_2()
{
   // PCA transformation, initialisation
   // initialise vector of mean values
   fMeanValues_2[0][0] = -0.67024786712;
   fMeanValues_2[0][1] = 0.169879912931;
   fMeanValues_2[0][2] = -0.102056591748;
   fMeanValues_2[0][3] = -0.252651847075;
   fMeanValues_2[0][4] = -0.470940202063;
   fMeanValues_2[0][5] = -0.201900381265;
   fMeanValues_2[0][6] = 0.3395405474;
   fMeanValues_2[0][7] = -0.214995874664;
   fMeanValues_2[0][8] = 0.0570946618942;
   fMeanValues_2[0][9] = 0.346728486158;
   fMeanValues_2[0][10] = -0.977258728959;
   fMeanValues_2[0][11] = -0.954800300011;
   fMeanValues_2[0][12] = -0.954496939965;
   fMeanValues_2[0][13] = -0.933197413782;
   fMeanValues_2[0][14] = -0.961036693774;
   fMeanValues_2[0][15] = -0.998473027653;
   fMeanValues_2[0][16] = -0.858532664342;
   fMeanValues_2[1][0] = -0.0684065568682;
   fMeanValues_2[1][1] = 0.169075022519;
   fMeanValues_2[1][2] = -0.103283750489;
   fMeanValues_2[1][3] = -0.249474682599;
   fMeanValues_2[1][4] = -0.471233476334;
   fMeanValues_2[1][5] = -0.202212938152;
   fMeanValues_2[1][6] = 0.340534744393;
   fMeanValues_2[1][7] = -0.21655283727;
   fMeanValues_2[1][8] = 0.0565838143862;
   fMeanValues_2[1][9] = 0.343000856521;
   fMeanValues_2[1][10] = -0.943007318995;
   fMeanValues_2[1][11] = -0.936491105102;
   fMeanValues_2[1][12] = -0.938429100145;
   fMeanValues_2[1][13] = -0.933507308744;
   fMeanValues_2[1][14] = -0.93713019312;
   fMeanValues_2[1][15] = -0.996855272229;
   fMeanValues_2[1][16] = -0.811594389871;
   fMeanValues_2[2][0] = -0.114674242814;
   fMeanValues_2[2][1] = 0.169136899988;
   fMeanValues_2[2][2] = -0.103189410346;
   fMeanValues_2[2][3] = -0.249718933111;
   fMeanValues_2[2][4] = -0.471210930322;
   fMeanValues_2[2][5] = -0.202188909752;
   fMeanValues_2[2][6] = 0.340458313624;
   fMeanValues_2[2][7] = -0.216433142833;
   fMeanValues_2[2][8] = 0.056623086752;
   fMeanValues_2[2][9] = 0.343287425081;
   fMeanValues_2[2][10] = -0.945640460743;
   fMeanValues_2[2][11] = -0.937898658997;
   fMeanValues_2[2][12] = -0.939664345639;
   fMeanValues_2[2][13] = -0.933483484984;
   fMeanValues_2[2][14] = -0.938968050451;
   fMeanValues_2[2][15] = -0.996979640229;
   fMeanValues_2[2][16] = -0.815202858258;

   // initialise matrix of eigenvectors
   fEigenVectors_2[0][0][0] = -0.99935998851;
   fEigenVectors_2[0][0][1] = -0.0058540597714;
   fEigenVectors_2[0][0][2] = 0.00785928254815;
   fEigenVectors_2[0][0][3] = 0.0305698184956;
   fEigenVectors_2[0][0][4] = -0.00959046233979;
   fEigenVectors_2[0][0][5] = -0.00924134927197;
   fEigenVectors_2[0][0][6] = 7.89479428443e-05;
   fEigenVectors_2[0][0][7] = 0.000377425114295;
   fEigenVectors_2[0][0][8] = 0.00428350198319;
   fEigenVectors_2[0][0][9] = 0.0049802630771;
   fEigenVectors_2[0][0][10] = 0.00374195713609;
   fEigenVectors_2[0][0][11] = -0.00205122569742;
   fEigenVectors_2[0][0][12] = -0.00310709815706;
   fEigenVectors_2[0][0][13] = -0.000611149534738;
   fEigenVectors_2[0][0][14] = -0.000358566441813;
   fEigenVectors_2[0][0][15] = -2.51298232899e-05;
   fEigenVectors_2[0][0][16] = 0.000122855268831;
   fEigenVectors_2[0][1][0] = -0.000426457953008;
   fEigenVectors_2[0][1][1] = -0.00898936552887;
   fEigenVectors_2[0][1][2] = -0.00500936166625;
   fEigenVectors_2[0][1][3] = 0.00587638615929;
   fEigenVectors_2[0][1][4] = 0.0617039842378;
   fEigenVectors_2[0][1][5] = -0.0460872895051;
   fEigenVectors_2[0][1][6] = 0.0736784957467;
   fEigenVectors_2[0][1][7] = -0.990455901973;
   fEigenVectors_2[0][1][8] = -0.00329732280613;
   fEigenVectors_2[0][1][9] = 0.0512423365153;
   fEigenVectors_2[0][1][10] = -0.0621303727753;
   fEigenVectors_2[0][1][11] = 0.00243574208223;
   fEigenVectors_2[0][1][12] = 0.0283903004706;
   fEigenVectors_2[0][1][13] = 0.000536435911606;
   fEigenVectors_2[0][1][14] = 0.00495917829233;
   fEigenVectors_2[0][1][15] = 0.00162248130824;
   fEigenVectors_2[0][1][16] = 0.012659428928;
   fEigenVectors_2[0][2][0] = 0.000632844285592;
   fEigenVectors_2[0][2][1] = 0.00936980721235;
   fEigenVectors_2[0][2][2] = 0.0157271651944;
   fEigenVectors_2[0][2][3] = 0.00242865742658;
   fEigenVectors_2[0][2][4] = -0.0559402366615;
   fEigenVectors_2[0][2][5] = -0.0142449961068;
   fEigenVectors_2[0][2][6] = -0.993548674682;
   fEigenVectors_2[0][2][7] = -0.0779629117516;
   fEigenVectors_2[0][2][8] = -0.00726836373291;
   fEigenVectors_2[0][2][9] = 0.000105812766031;
   fEigenVectors_2[0][2][10] = 0.0274727210879;
   fEigenVectors_2[0][2][11] = 0.0329427866958;
   fEigenVectors_2[0][2][12] = 0.0196784284799;
   fEigenVectors_2[0][2][13] = 0.0260427141512;
   fEigenVectors_2[0][2][14] = -0.00390246948926;
   fEigenVectors_2[0][2][15] = -0.011626627135;
   fEigenVectors_2[0][2][16] = -0.000678538084209;
   fEigenVectors_2[0][3][0] = -0.00603260186828;
   fEigenVectors_2[0][3][1] = 0.12611289245;
   fEigenVectors_2[0][3][2] = 0.0552478796156;
   fEigenVectors_2[0][3][3] = -0.25791725837;
   fEigenVectors_2[0][3][4] = -0.772692438318;
   fEigenVectors_2[0][3][5] = 0.553774911079;
   fEigenVectors_2[0][3][6] = 0.0440830731915;
   fEigenVectors_2[0][3][7] = -0.072648463799;
   fEigenVectors_2[0][3][8] = -0.0084984153754;
   fEigenVectors_2[0][3][9] = 0.0050774784821;
   fEigenVectors_2[0][3][10] = 0.0147400901791;
   fEigenVectors_2[0][3][11] = -0.00346421561322;
   fEigenVectors_2[0][3][12] = 0.0538193139899;
   fEigenVectors_2[0][3][13] = -0.00812383772408;
   fEigenVectors_2[0][3][14] = -0.00266344747736;
   fEigenVectors_2[0][3][15] = -0.0147159602371;
   fEigenVectors_2[0][3][16] = 0.00553977083218;
   fEigenVectors_2[0][4][0] = 7.68101318423e-05;
   fEigenVectors_2[0][4][1] = 0.000182057779702;
   fEigenVectors_2[0][4][2] = 0.00076833521423;
   fEigenVectors_2[0][4][3] = 0.0009796496471;
   fEigenVectors_2[0][4][4] = -5.14775274147e-05;
   fEigenVectors_2[0][4][5] = 0.000776659686505;
   fEigenVectors_2[0][4][6] = -0.000697460159023;
   fEigenVectors_2[0][4][7] = -0.0131087787083;
   fEigenVectors_2[0][4][8] = 0.000369164195093;
   fEigenVectors_2[0][4][9] = 0.0003682139792;
   fEigenVectors_2[0][4][10] = -0.00625616771792;
   fEigenVectors_2[0][4][11] = -0.00305835151589;
   fEigenVectors_2[0][4][12] = 0.0082528341612;
   fEigenVectors_2[0][4][13] = -0.173190797483;
   fEigenVectors_2[0][4][14] = -0.278543198024;
   fEigenVectors_2[0][4][15] = -0.10114840606;
   fEigenVectors_2[0][4][16] = -0.939093306702;
   fEigenVectors_2[0][5][0] = 0.000384872700022;
   fEigenVectors_2[0][5][1] = -0.000968528115321;
   fEigenVectors_2[0][5][2] = 0.00116086781784;
   fEigenVectors_2[0][5][3] = 0.00117237384652;
   fEigenVectors_2[0][5][4] = 0.00116503861752;
   fEigenVectors_2[0][5][5] = 0.000900972269257;
   fEigenVectors_2[0][5][6] = -0.0263928705806;
   fEigenVectors_2[0][5][7] = -0.000210512890329;
   fEigenVectors_2[0][5][8] = 0.00548445075897;
   fEigenVectors_2[0][5][9] = 0.00123226265664;
   fEigenVectors_2[0][5][10] = 0.0167931138755;
   fEigenVectors_2[0][5][11] = 0.0106883152238;
   fEigenVectors_2[0][5][12] = 0.019544339245;
   fEigenVectors_2[0][5][13] = -0.836328868596;
   fEigenVectors_2[0][5][14] = 0.434145101196;
   fEigenVectors_2[0][5][15] = 0.332346238819;
   fEigenVectors_2[0][5][16] = -0.0102761536049;
   fEigenVectors_2[0][6][0] = -0.000523417628051;
   fEigenVectors_2[0][6][1] = 0.00107243906427;
   fEigenVectors_2[0][6][2] = -0.00212929078826;
   fEigenVectors_2[0][6][3] = -0.00378556355643;
   fEigenVectors_2[0][6][4] = -0.0137899028785;
   fEigenVectors_2[0][6][5] = 0.0130562944852;
   fEigenVectors_2[0][6][6] = 0.00347176412439;
   fEigenVectors_2[0][6][7] = -0.00245717910137;
   fEigenVectors_2[0][6][8] = -0.0098692406531;
   fEigenVectors_2[0][6][9] = 0.00447886810225;
   fEigenVectors_2[0][6][10] = 0.0013410267787;
   fEigenVectors_2[0][6][11] = 0.0017118867642;
   fEigenVectors_2[0][6][12] = -0.0416507641816;
   fEigenVectors_2[0][6][13] = 0.497229326698;
   fEigenVectors_2[0][6][14] = 0.415445957804;
   fEigenVectors_2[0][6][15] = 0.702337674102;
   fEigenVectors_2[0][6][16] = -0.290918303879;
   fEigenVectors_2[0][7][0] = -0.000426000421664;
   fEigenVectors_2[0][7][1] = -0.00180375204126;
   fEigenVectors_2[0][7][2] = -0.00535971762486;
   fEigenVectors_2[0][7][3] = -0.0249548109409;
   fEigenVectors_2[0][7][4] = -0.00340810379451;
   fEigenVectors_2[0][7][5] = -0.0143261709435;
   fEigenVectors_2[0][7][6] = 0.0155913402783;
   fEigenVectors_2[0][7][7] = -0.0834325105218;
   fEigenVectors_2[0][7][8] = 0.00214338783966;
   fEigenVectors_2[0][7][9] = -0.677075259653;
   fEigenVectors_2[0][7][10] = 0.667851040183;
   fEigenVectors_2[0][7][11] = -0.129244384519;
   fEigenVectors_2[0][7][12] = -0.265622116487;
   fEigenVectors_2[0][7][13] = -0.00386075209499;
   fEigenVectors_2[0][7][14] = -0.0135893864967;
   fEigenVectors_2[0][7][15] = -0.00213595644859;
   fEigenVectors_2[0][7][16] = -0.00054381468452;
   fEigenVectors_2[0][8][0] = 1.76203664408e-05;
   fEigenVectors_2[0][8][1] = -0.00900502589554;
   fEigenVectors_2[0][8][2] = -0.00278300226064;
   fEigenVectors_2[0][8][3] = 0.00196984968681;
   fEigenVectors_2[0][8][4] = -0.0115155295559;
   fEigenVectors_2[0][8][5] = 0.00983727543331;
   fEigenVectors_2[0][8][6] = -0.0435457405425;
   fEigenVectors_2[0][8][7] = 0.00585805033174;
   fEigenVectors_2[0][8][8] = -0.012058979562;
   fEigenVectors_2[0][8][9] = -0.165451193311;
   fEigenVectors_2[0][8][10] = -0.389701038996;
   fEigenVectors_2[0][8][11] = -0.895411475695;
   fEigenVectors_2[0][8][12] = -0.12728781706;
   fEigenVectors_2[0][8][13] = -0.0166263862844;
   fEigenVectors_2[0][8][14] = 0.00193889902287;
   fEigenVectors_2[0][8][15] = 0.00912840388508;
   fEigenVectors_2[0][8][16] = 0.00578938433393;
   fEigenVectors_2[0][9][0] = 0.00884906488208;
   fEigenVectors_2[0][9][1] = 0.0458048211661;
   fEigenVectors_2[0][9][2] = 0.0170551105399;
   fEigenVectors_2[0][9][3] = 0.0632150037576;
   fEigenVectors_2[0][9][4] = -0.0734286284642;
   fEigenVectors_2[0][9][5] = -0.0215824238918;
   fEigenVectors_2[0][9][6] = -0.0065881191527;
   fEigenVectors_2[0][9][7] = -0.0128039554866;
   fEigenVectors_2[0][9][8] = -0.0175257888639;
   fEigenVectors_2[0][9][9] = 0.54632319274;
   fEigenVectors_2[0][9][10] = 0.221530726693;
   fEigenVectors_2[0][9][11] = -0.0831177152643;
   fEigenVectors_2[0][9][12] = -0.793815706656;
   fEigenVectors_2[0][9][13] = -0.0341121186288;
   fEigenVectors_2[0][9][14] = -0.0361645070208;
   fEigenVectors_2[0][9][15] = -0.0022537922845;
   fEigenVectors_2[0][9][16] = 0.00954590197723;
   fEigenVectors_2[0][10][0] = -0.0149110885535;
   fEigenVectors_2[0][10][1] = 0.268556089664;
   fEigenVectors_2[0][10][2] = 0.0916078637852;
   fEigenVectors_2[0][10][3] = -0.0741489936078;
   fEigenVectors_2[0][10][4] = 0.600064935924;
   fEigenVectors_2[0][10][5] = 0.727787419076;
   fEigenVectors_2[0][10][6] = -0.0385705888235;
   fEigenVectors_2[0][10][7] = -0.00396369879229;
   fEigenVectors_2[0][10][8] = -0.0288725301478;
   fEigenVectors_2[0][10][9] = 0.0822888743456;
   fEigenVectors_2[0][10][10] = 0.100230906252;
   fEigenVectors_2[0][10][11] = -0.063559895788;
   fEigenVectors_2[0][10][12] = 0.0283475180912;
   fEigenVectors_2[0][10][13] = 0.00270117474415;
   fEigenVectors_2[0][10][14] = -0.00149818745311;
   fEigenVectors_2[0][10][15] = -0.00214104621586;
   fEigenVectors_2[0][10][16] = 0.00068755399111;
   fEigenVectors_2[0][11][0] = -0.00865396374426;
   fEigenVectors_2[0][11][1] = 0.274369141534;
   fEigenVectors_2[0][11][2] = -0.960663636225;
   fEigenVectors_2[0][11][3] = 0.0207745949155;
   fEigenVectors_2[0][11][4] = -0.0108125117065;
   fEigenVectors_2[0][11][5] = 0.0283153727947;
   fEigenVectors_2[0][11][6] = -0.0123874415286;
   fEigenVectors_2[0][11][7] = -0.000125466185749;
   fEigenVectors_2[0][11][8] = -0.0028506307285;
   fEigenVectors_2[0][11][9] = 0.00708874099364;
   fEigenVectors_2[0][11][10] = 0.00275460578721;
   fEigenVectors_2[0][11][11] = -0.00152592355349;
   fEigenVectors_2[0][11][12] = 0.00364080803317;
   fEigenVectors_2[0][11][13] = -0.00413548360587;
   fEigenVectors_2[0][11][14] = -0.0108790026826;
   fEigenVectors_2[0][11][15] = 0.00667115019625;
   fEigenVectors_2[0][11][16] = 0.0026143525164;
   fEigenVectors_2[0][12][0] = -0.00800340450199;
   fEigenVectors_2[0][12][1] = 0.503693881918;
   fEigenVectors_2[0][12][2] = 0.129206080619;
   fEigenVectors_2[0][12][3] = -0.393652342486;
   fEigenVectors_2[0][12][4] = -0.00260824607718;
   fEigenVectors_2[0][12][5] = -0.362420933137;
   fEigenVectors_2[0][12][6] = 0.0184380712848;
   fEigenVectors_2[0][12][7] = 0.0119634946722;
   fEigenVectors_2[0][12][8] = 0.0442112087835;
   fEigenVectors_2[0][12][9] = 0.30585517252;
   fEigenVectors_2[0][12][10] = 0.376931531525;
   fEigenVectors_2[0][12][11] = -0.282799621178;
   fEigenVectors_2[0][12][12] = 0.352814681036;
   fEigenVectors_2[0][12][13] = 0.0188236568871;
   fEigenVectors_2[0][12][14] = 0.0169174550738;
   fEigenVectors_2[0][12][15] = -0.00263959301421;
   fEigenVectors_2[0][12][16] = -0.00724553202505;
   fEigenVectors_2[0][13][0] = 0.0220307282649;
   fEigenVectors_2[0][13][1] = 0.597350648103;
   fEigenVectors_2[0][13][2] = 0.186874946519;
   fEigenVectors_2[0][13][3] = 0.755861966803;
   fEigenVectors_2[0][13][4] = -0.154058639879;
   fEigenVectors_2[0][13][5] = -0.0217501914298;
   fEigenVectors_2[0][13][6] = 0.0205929148317;
   fEigenVectors_2[0][13][7] = -0.00977703854503;
   fEigenVectors_2[0][13][8] = 0.00695879075657;
   fEigenVectors_2[0][13][9] = -0.088669133571;
   fEigenVectors_2[0][13][10] = -0.0414595884496;
   fEigenVectors_2[0][13][11] = 0.0246402951552;
   fEigenVectors_2[0][13][12] = 0.0382515220943;
   fEigenVectors_2[0][13][13] = 0.00178546090864;
   fEigenVectors_2[0][13][14] = 0.00210177471662;
   fEigenVectors_2[0][13][15] = 0.00165545531186;
   fEigenVectors_2[0][13][16] = 0.000539736478267;
   fEigenVectors_2[0][14][0] = -0.0173209080165;
   fEigenVectors_2[0][14][1] = 0.472717080686;
   fEigenVectors_2[0][14][2] = 0.114989962045;
   fEigenVectors_2[0][14][3] = -0.442232234841;
   fEigenVectors_2[0][14][4] = 0.0782979786546;
   fEigenVectors_2[0][14][5] = -0.161157783806;
   fEigenVectors_2[0][14][6] = -0.00785003038792;
   fEigenVectors_2[0][14][7] = 0.00490907825087;
   fEigenVectors_2[0][14][8] = -0.00244907984271;
   fEigenVectors_2[0][14][9] = -0.323667977276;
   fEigenVectors_2[0][14][10] = -0.440020542719;
   fEigenVectors_2[0][14][11] = 0.29791620376;
   fEigenVectors_2[0][14][12] = -0.383135853145;
   fEigenVectors_2[0][14][13] = -0.0221636965808;
   fEigenVectors_2[0][14][14] = -0.0239417998331;
   fEigenVectors_2[0][14][15] = 0.0142604797095;
   fEigenVectors_2[0][14][16] = 0.0076418352043;
   fEigenVectors_2[0][15][0] = -0.000553960632663;
   fEigenVectors_2[0][15][1] = 0.00933070465753;
   fEigenVectors_2[0][15][2] = -0.0117407537451;
   fEigenVectors_2[0][15][3] = -0.00373908148451;
   fEigenVectors_2[0][15][4] = 0.00400989070837;
   fEigenVectors_2[0][15][5] = -0.0014876802567;
   fEigenVectors_2[0][15][6] = 0.00667801926704;
   fEigenVectors_2[0][15][7] = 0.000241803297438;
   fEigenVectors_2[0][15][8] = 0.00428201577019;
   fEigenVectors_2[0][15][9] = -0.00561429269002;
   fEigenVectors_2[0][15][10] = -0.0106811365282;
   fEigenVectors_2[0][15][11] = 0.00351638090941;
   fEigenVectors_2[0][15][12] = -0.0482971619487;
   fEigenVectors_2[0][15][13] = 0.142102913758;
   fEigenVectors_2[0][15][14] = 0.747529414647;
   fEigenVectors_2[0][15][15] = -0.620698512023;
   fEigenVectors_2[0][15][16] = -0.18146302138;
   fEigenVectors_2[0][16][0] = 0.00409428180507;
   fEigenVectors_2[0][16][1] = -0.0149497951729;
   fEigenVectors_2[0][16][2] = -0.00600245758643;
   fEigenVectors_2[0][16][3] = 0.00786464017696;
   fEigenVectors_2[0][16][4] = 0.0103856489517;
   fEigenVectors_2[0][16][5] = 0.041339538164;
   fEigenVectors_2[0][16][6] = -0.00927093442852;
   fEigenVectors_2[0][16][7] = -0.00501847343704;
   fEigenVectors_2[0][16][8] = 0.998194272091;
   fEigenVectors_2[0][16][9] = -0.00202173526358;
   fEigenVectors_2[0][16][10] = -0.0167573455573;
   fEigenVectors_2[0][16][11] = -0.000585741917393;
   fEigenVectors_2[0][16][12] = -0.0305141704348;
   fEigenVectors_2[0][16][13] = 0.00746485876916;
   fEigenVectors_2[0][16][14] = -0.00289412744108;
   fEigenVectors_2[0][16][15] = 0.00778639501166;
   fEigenVectors_2[0][16][16] = -0.00100865813308;
   fEigenVectors_2[1][0][0] = 0.999788369559;
   fEigenVectors_2[1][0][1] = -0.0089363859786;
   fEigenVectors_2[1][0][2] = 0.00381592650227;
   fEigenVectors_2[1][0][3] = -0.00947428405298;
   fEigenVectors_2[1][0][4] = 0.00570793834001;
   fEigenVectors_2[1][0][5] = 0.00809857145523;
   fEigenVectors_2[1][0][6] = 0.00501657893537;
   fEigenVectors_2[1][0][7] = 0.00338541324993;
   fEigenVectors_2[1][0][8] = -0.00492161031785;
   fEigenVectors_2[1][0][9] = 0.00585009252773;
   fEigenVectors_2[1][0][10] = -0.00111460247264;
   fEigenVectors_2[1][0][11] = 0.00654671715716;
   fEigenVectors_2[1][0][12] = -4.5457630911e-06;
   fEigenVectors_2[1][0][13] = -0.00122399138211;
   fEigenVectors_2[1][0][14] = 0.000291710793034;
   fEigenVectors_2[1][0][15] = -0.000293861952857;
   fEigenVectors_2[1][0][16] = 0.000148120799417;
   fEigenVectors_2[1][1][0] = 0.000472209959908;
   fEigenVectors_2[1][1][1] = 0.000161479334403;
   fEigenVectors_2[1][1][2] = -0.000756912550585;
   fEigenVectors_2[1][1][3] = -0.0100136652926;
   fEigenVectors_2[1][1][4] = -0.0281658616142;
   fEigenVectors_2[1][1][5] = 0.00197264758469;
   fEigenVectors_2[1][1][6] = 0.219732576926;
   fEigenVectors_2[1][1][7] = -0.227756817445;
   fEigenVectors_2[1][1][8] = 0.770197991154;
   fEigenVectors_2[1][1][9] = 0.547780442621;
   fEigenVectors_2[1][1][10] = -0.0623768211087;
   fEigenVectors_2[1][1][11] = -0.0357403979944;
   fEigenVectors_2[1][1][12] = 0.0158180692941;
   fEigenVectors_2[1][1][13] = -0.00385120340324;
   fEigenVectors_2[1][1][14] = -0.00618433979402;
   fEigenVectors_2[1][1][15] = 0.0100761123846;
   fEigenVectors_2[1][1][16] = 0.0102325089277;
   fEigenVectors_2[1][2][0] = -0.000365536256359;
   fEigenVectors_2[1][2][1] = 0.0171466050559;
   fEigenVectors_2[1][2][2] = 0.00376890061192;
   fEigenVectors_2[1][2][3] = -0.00660281139024;
   fEigenVectors_2[1][2][4] = 0.0560530412913;
   fEigenVectors_2[1][2][5] = 0.00500859821842;
   fEigenVectors_2[1][2][6] = 0.442405027441;
   fEigenVectors_2[1][2][7] = -0.834366665079;
   fEigenVectors_2[1][2][8] = -0.298474657106;
   fEigenVectors_2[1][2][9] = -0.0955245548625;
   fEigenVectors_2[1][2][10] = 0.0712081314714;
   fEigenVectors_2[1][2][11] = -0.0233808407397;
   fEigenVectors_2[1][2][12] = 0.0174760722628;
   fEigenVectors_2[1][2][13] = -0.00307561667777;
   fEigenVectors_2[1][2][14] = -0.00256596075528;
   fEigenVectors_2[1][2][15] = -0.020920378815;
   fEigenVectors_2[1][2][16] = -0.0016269145805;
   fEigenVectors_2[1][3][0] = 0.00511086363228;
   fEigenVectors_2[1][3][1] = -0.0692301619111;
   fEigenVectors_2[1][3][2] = -0.00177133216769;
   fEigenVectors_2[1][3][3] = -0.0047993470266;
   fEigenVectors_2[1][3][4] = -0.243166812645;
   fEigenVectors_2[1][3][5] = 0.162809515878;
   fEigenVectors_2[1][3][6] = -0.823663424862;
   fEigenVectors_2[1][3][7] = -0.473146126029;
   fEigenVectors_2[1][3][8] = 0.0359088819486;
   fEigenVectors_2[1][3][9] = 0.0692252938276;
   fEigenVectors_2[1][3][10] = 0.0046487666448;
   fEigenVectors_2[1][3][11] = -0.026365037449;
   fEigenVectors_2[1][3][12] = -0.00937539104489;
   fEigenVectors_2[1][3][13] = 0.0144522368443;
   fEigenVectors_2[1][3][14] = -0.00159998322821;
   fEigenVectors_2[1][3][15] = -0.00920843145542;
   fEigenVectors_2[1][3][16] = 0.00683560811831;
   fEigenVectors_2[1][4][0] = 4.38835618732e-06;
   fEigenVectors_2[1][4][1] = 0.00241369048468;
   fEigenVectors_2[1][4][2] = 0.00140941904202;
   fEigenVectors_2[1][4][3] = -0.00335757311073;
   fEigenVectors_2[1][4][4] = -0.000397462405939;
   fEigenVectors_2[1][4][5] = -9.45320937519e-05;
   fEigenVectors_2[1][4][6] = 0.00319921625683;
   fEigenVectors_2[1][4][7] = -0.00202804059347;
   fEigenVectors_2[1][4][8] = 0.0143274657353;
   fEigenVectors_2[1][4][9] = 0.00832202622666;
   fEigenVectors_2[1][4][10] = -0.00224604189677;
   fEigenVectors_2[1][4][11] = 0.00714035364273;
   fEigenVectors_2[1][4][12] = -0.380007724196;
   fEigenVectors_2[1][4][13] = -0.0226582136894;
   fEigenVectors_2[1][4][14] = -0.192504997459;
   fEigenVectors_2[1][4][15] = -0.332398434145;
   fEigenVectors_2[1][4][16] = -0.840933814018;
   fEigenVectors_2[1][5][0] = -2.59514156787e-05;
   fEigenVectors_2[1][5][1] = 0.0033557779058;
   fEigenVectors_2[1][5][2] = 0.00139142197786;
   fEigenVectors_2[1][5][3] = -0.00480406708579;
   fEigenVectors_2[1][5][4] = -0.00152613545834;
   fEigenVectors_2[1][5][5] = 0.00128253091054;
   fEigenVectors_2[1][5][6] = 0.0131676377326;
   fEigenVectors_2[1][5][7] = -0.0249512542332;
   fEigenVectors_2[1][5][8] = -0.00751742027766;
   fEigenVectors_2[1][5][9] = -0.000404352225157;
   fEigenVectors_2[1][5][10] = -0.0185225977813;
   fEigenVectors_2[1][5][11] = 0.023579829625;
   fEigenVectors_2[1][5][12] = -0.685003386808;
   fEigenVectors_2[1][5][13] = -0.02113055131;
   fEigenVectors_2[1][5][14] = -0.026902821781;
   fEigenVectors_2[1][5][15] = 0.725900664462;
   fEigenVectors_2[1][5][16] = 0.029603217642;
   fEigenVectors_2[1][6][0] = 0.000358633515459;
   fEigenVectors_2[1][6][1] = -0.00427267771501;
   fEigenVectors_2[1][6][2] = -0.00201201488376;
   fEigenVectors_2[1][6][3] = 0.0061274638918;
   fEigenVectors_2[1][6][4] = -0.00114700816082;
   fEigenVectors_2[1][6][5] = 0.0020110844402;
   fEigenVectors_2[1][6][6] = -0.013957743042;
   fEigenVectors_2[1][6][7] = -0.00496856508734;
   fEigenVectors_2[1][6][8] = -0.0121534271266;
   fEigenVectors_2[1][6][9] = -3.24735865632e-05;
   fEigenVectors_2[1][6][10] = -0.0077269081389;
   fEigenVectors_2[1][6][11] = -0.00411367659177;
   fEigenVectors_2[1][6][12] = 0.615236209409;
   fEigenVectors_2[1][6][13] = 0.0246969800581;
   fEigenVectors_2[1][6][14] = -0.0356454987221;
   fEigenVectors_2[1][6][15] = 0.600649800855;
   fEigenVectors_2[1][6][16] = -0.508246498211;
   fEigenVectors_2[1][7][0] = 0.00234343632375;
   fEigenVectors_2[1][7][1] = 0.0185155517337;
   fEigenVectors_2[1][7][2] = -0.00538943303617;
   fEigenVectors_2[1][7][3] = 2.6703048797e-06;
   fEigenVectors_2[1][7][4] = 0.0264668328636;
   fEigenVectors_2[1][7][5] = -0.0386326934559;
   fEigenVectors_2[1][7][6] = -0.0164053968996;
   fEigenVectors_2[1][7][7] = -0.077768604209;
   fEigenVectors_2[1][7][8] = 0.420617700271;
   fEigenVectors_2[1][7][9] = -0.530096157309;
   fEigenVectors_2[1][7][10] = 0.413597109715;
   fEigenVectors_2[1][7][11] = 0.599887336354;
   fEigenVectors_2[1][7][12] = 0.0131930059051;
   fEigenVectors_2[1][7][13] = -0.0449510783122;
   fEigenVectors_2[1][7][14] = 0.00687545462809;
   fEigenVectors_2[1][7][15] = 0.0042763187596;
   fEigenVectors_2[1][7][16] = -0.00194439689852;
   fEigenVectors_2[1][8][0] = 0.00107771118909;
   fEigenVectors_2[1][8][1] = 0.00957973795494;
   fEigenVectors_2[1][8][2] = -0.00234649551927;
   fEigenVectors_2[1][8][3] = -0.00082070796484;
   fEigenVectors_2[1][8][4] = 0.0114751911747;
   fEigenVectors_2[1][8][5] = -0.0173608295334;
   fEigenVectors_2[1][8][6] = 0.0104290027482;
   fEigenVectors_2[1][8][7] = -0.0905867672779;
   fEigenVectors_2[1][8][8] = 0.158836201712;
   fEigenVectors_2[1][8][9] = -0.35547634799;
   fEigenVectors_2[1][8][10] = -0.898165773895;
   fEigenVectors_2[1][8][11] = 0.178780985821;
   fEigenVectors_2[1][8][12] = 0.014445937319;
   fEigenVectors_2[1][8][13] = -0.0187733037192;
   fEigenVectors_2[1][8][14] = -0.000898219044921;
   fEigenVectors_2[1][8][15] = -0.0177061168934;
   fEigenVectors_2[1][8][16] = 0.00456902454209;
   fEigenVectors_2[1][9][0] = -0.0107033350786;
   fEigenVectors_2[1][9][1] = -0.0314839720009;
   fEigenVectors_2[1][9][2] = 0.0115654161311;
   fEigenVectors_2[1][9][3] = -0.00259633690755;
   fEigenVectors_2[1][9][4] = -0.0574828107799;
   fEigenVectors_2[1][9][5] = 0.0864956644643;
   fEigenVectors_2[1][9][6] = 0.0144516988362;
   fEigenVectors_2[1][9][7] = 0.035494950267;
   fEigenVectors_2[1][9][8] = -0.325362299485;
   fEigenVectors_2[1][9][9] = 0.496256860547;
   fEigenVectors_2[1][9][10] = -0.107565083407;
   fEigenVectors_2[1][9][11] = 0.732539880339;
   fEigenVectors_2[1][9][12] = 0.0254538207263;
   fEigenVectors_2[1][9][13] = -0.291737537407;
   fEigenVectors_2[1][9][14] = 0.0156375243063;
   fEigenVectors_2[1][9][15] = -0.0128859785547;
   fEigenVectors_2[1][9][16] = 0.00367319433018;
   fEigenVectors_2[1][10][0] = -0.00443911204429;
   fEigenVectors_2[1][10][1] = -0.419845306713;
   fEigenVectors_2[1][10][2] = -0.0481232002702;
   fEigenVectors_2[1][10][3] = -0.10404245656;
   fEigenVectors_2[1][10][4] = 0.725446426693;
   fEigenVectors_2[1][10][5] = -0.466643480182;
   fEigenVectors_2[1][10][6] = -0.213534467406;
   fEigenVectors_2[1][10][7] = -0.0862381199762;
   fEigenVectors_2[1][10][8] = -0.00911088342536;
   fEigenVectors_2[1][10][9] = 0.101334131735;
   fEigenVectors_2[1][10][10] = -0.0139684795664;
   fEigenVectors_2[1][10][11] = 0.0416595656552;
   fEigenVectors_2[1][10][12] = -0.00508516391029;
   fEigenVectors_2[1][10][13] = 0.0342701234627;
   fEigenVectors_2[1][10][14] = 0.00487432877531;
   fEigenVectors_2[1][10][15] = -0.000766153746587;
   fEigenVectors_2[1][10][16] = 3.5055748049e-05;
   fEigenVectors_2[1][11][0] = 0.00791472857858;
   fEigenVectors_2[1][11][1] = -0.15814420943;
   fEigenVectors_2[1][11][2] = -0.0280367427966;
   fEigenVectors_2[1][11][3] = 0.985812376576;
   fEigenVectors_2[1][11][4] = 0.0389446278282;
   fEigenVectors_2[1][11][5] = -0.0108239933551;
   fEigenVectors_2[1][11][6] = 0.00140536936054;
   fEigenVectors_2[1][11][7] = -0.0114092346804;
   fEigenVectors_2[1][11][8] = 0.0068690303726;
   fEigenVectors_2[1][11][9] = 0.00569552509564;
   fEigenVectors_2[1][11][10] = -0.00145499910237;
   fEigenVectors_2[1][11][11] = 0.00219917069004;
   fEigenVectors_2[1][11][12] = -0.0104176317575;
   fEigenVectors_2[1][11][13] = 0.00289638314111;
   fEigenVectors_2[1][11][14] = 0.018256377149;
   fEigenVectors_2[1][11][15] = -0.00198952922447;
   fEigenVectors_2[1][11][16] = -0.00298851015788;
   fEigenVectors_2[1][12][0] = -0.00288718900358;
   fEigenVectors_2[1][12][1] = -0.542981999805;
   fEigenVectors_2[1][12][2] = -0.0274347223423;
   fEigenVectors_2[1][12][3] = -0.0733434574042;
   fEigenVectors_2[1][12][4] = -0.451410937541;
   fEigenVectors_2[1][12][5] = -0.188928329973;
   fEigenVectors_2[1][12][6] = 0.12875048154;
   fEigenVectors_2[1][12][7] = 0.034752642202;
   fEigenVectors_2[1][12][8] = -0.0585676463992;
   fEigenVectors_2[1][12][9] = 0.0349621583094;
   fEigenVectors_2[1][12][10] = -0.0149126358795;
   fEigenVectors_2[1][12][11] = 0.163367661591;
   fEigenVectors_2[1][12][12] = -0.0187099679353;
   fEigenVectors_2[1][12][13] = 0.638708004535;
   fEigenVectors_2[1][12][14] = -0.0430953719508;
   fEigenVectors_2[1][12][15] = -0.00677258734793;
   fEigenVectors_2[1][12][16] = 0.00389178605533;
   fEigenVectors_2[1][13][0] = -0.0130013112133;
   fEigenVectors_2[1][13][1] = -0.441086249752;
   fEigenVectors_2[1][13][2] = 0.0101172238622;
   fEigenVectors_2[1][13][3] = -0.0728593206558;
   fEigenVectors_2[1][13][4] = 0.30439084795;
   fEigenVectors_2[1][13][5] = 0.829629868285;
   fEigenVectors_2[1][13][6] = 0.0804412578616;
   fEigenVectors_2[1][13][7] = 0.0519326269605;
   fEigenVectors_2[1][13][8] = 0.040766110275;
   fEigenVectors_2[1][13][9] = -0.0563620576384;
   fEigenVectors_2[1][13][10] = 0.00424326814815;
   fEigenVectors_2[1][13][11] = -0.0133487940155;
   fEigenVectors_2[1][13][12] = -0.00409869162418;
   fEigenVectors_2[1][13][13] = 0.0683604092448;
   fEigenVectors_2[1][13][14] = -0.00556086701234;
   fEigenVectors_2[1][13][15] = -0.000127672834931;
   fEigenVectors_2[1][13][16] = 0.000331214671564;
   fEigenVectors_2[1][14][0] = -0.00145794343914;
   fEigenVectors_2[1][14][1] = -0.547424074435;
   fEigenVectors_2[1][14][2] = -0.0344814930292;
   fEigenVectors_2[1][14][3] = -0.0751873174041;
   fEigenVectors_2[1][14][4] = -0.329319337799;
   fEigenVectors_2[1][14][5] = -0.142908684146;
   fEigenVectors_2[1][14][6] = 0.0886843064477;
   fEigenVectors_2[1][14][7] = 0.0204421796031;
   fEigenVectors_2[1][14][8] = 0.0518092443653;
   fEigenVectors_2[1][14][9] = -0.132127312755;
   fEigenVectors_2[1][14][10] = 0.0283327525485;
   fEigenVectors_2[1][14][11] = -0.199294542239;
   fEigenVectors_2[1][14][12] = 0.0172746876587;
   fEigenVectors_2[1][14][13] = -0.701355262176;
   fEigenVectors_2[1][14][14] = 0.0579385958916;
   fEigenVectors_2[1][14][15] = 0.00676811315393;
   fEigenVectors_2[1][14][16] = -0.00790904701985;
   fEigenVectors_2[1][15][0] = 0.000368314043392;
   fEigenVectors_2[1][15][1] = -0.0116512017389;
   fEigenVectors_2[1][15][2] = -0.00411677023987;
   fEigenVectors_2[1][15][3] = 0.0176588926121;
   fEigenVectors_2[1][15][4] = 0.00282262651059;
   fEigenVectors_2[1][15][5] = -0.00654280835367;
   fEigenVectors_2[1][15][6] = -0.00347750459763;
   fEigenVectors_2[1][15][7] = 0.00452540576392;
   fEigenVectors_2[1][15][8] = -0.00322868771111;
   fEigenVectors_2[1][15][9] = -0.00884329880372;
   fEigenVectors_2[1][15][10] = 0.00566249286643;
   fEigenVectors_2[1][15][11] = -0.00447801919844;
   fEigenVectors_2[1][15][12] = 0.0732768413149;
   fEigenVectors_2[1][15][13] = -0.0707204938608;
   fEigenVectors_2[1][15][14] = -0.977240978085;
   fEigenVectors_2[1][15][15] = 0.0240897021862;
   fEigenVectors_2[1][15][16] = 0.182647502297;
   fEigenVectors_2[1][16][0] = 0.00366263141502;
   fEigenVectors_2[1][16][1] = 0.0538241669404;
   fEigenVectors_2[1][16][2] = -0.997310582136;
   fEigenVectors_2[1][16][3] = -0.0189850936206;
   fEigenVectors_2[1][16][4] = -0.00936982565824;
   fEigenVectors_2[1][16][5] = 0.0424121048108;
   fEigenVectors_2[1][16][6] = 0.00775656259618;
   fEigenVectors_2[1][16][7] = 0.00221776372735;
   fEigenVectors_2[1][16][8] = -0.00768740063597;
   fEigenVectors_2[1][16][9] = 0.00661127048748;
   fEigenVectors_2[1][16][10] = -0.00091350429782;
   fEigenVectors_2[1][16][11] = 0.00510201389687;
   fEigenVectors_2[1][16][12] = -0.00236176364377;
   fEigenVectors_2[1][16][13] = 0.00268285166801;
   fEigenVectors_2[1][16][14] = 0.00231896596074;
   fEigenVectors_2[1][16][15] = -0.000926662476777;
   fEigenVectors_2[1][16][16] = -0.000606769640195;
   fEigenVectors_2[2][0][0] = 0.999781419463;
   fEigenVectors_2[2][0][1] = -0.00441839601062;
   fEigenVectors_2[2][0][2] = 0.00776610729655;
   fEigenVectors_2[2][0][3] = -0.00975729983992;
   fEigenVectors_2[2][0][4] = 0.00488931798937;
   fEigenVectors_2[2][0][5] = 0.0101111968098;
   fEigenVectors_2[2][0][6] = 0.0053968015915;
   fEigenVectors_2[2][0][7] = 0.00314691627964;
   fEigenVectors_2[2][0][8] = -0.00421919167616;
   fEigenVectors_2[2][0][9] = 0.00585371980129;
   fEigenVectors_2[2][0][10] = -0.00101034518853;
   fEigenVectors_2[2][0][11] = 0.00654023907208;
   fEigenVectors_2[2][0][12] = -4.25761625085e-05;
   fEigenVectors_2[2][0][13] = -0.000910442327511;
   fEigenVectors_2[2][0][14] = 0.00029703442777;
   fEigenVectors_2[2][0][15] = -0.000311207687451;
   fEigenVectors_2[2][0][16] = 0.000156634295146;
   fEigenVectors_2[2][1][0] = 0.000380895417932;
   fEigenVectors_2[2][1][1] = 0.000514937854126;
   fEigenVectors_2[2][1][2] = -0.000363545020693;
   fEigenVectors_2[2][1][3] = -0.0094408773201;
   fEigenVectors_2[2][1][4] = -0.0264932603262;
   fEigenVectors_2[2][1][5] = 0.00144829174272;
   fEigenVectors_2[2][1][6] = 0.209672459373;
   fEigenVectors_2[2][1][7] = -0.213891987151;
   fEigenVectors_2[2][1][8] = 0.819293186805;
   fEigenVectors_2[2][1][9] = 0.48256696905;
   fEigenVectors_2[2][1][10] = -0.0599703494142;
   fEigenVectors_2[2][1][11] = -0.0363775169517;
   fEigenVectors_2[2][1][12] = 0.0149191535612;
   fEigenVectors_2[2][1][13] = -0.0018526090575;
   fEigenVectors_2[2][1][14] = -0.00591457438172;
   fEigenVectors_2[2][1][15] = 0.0097596144554;
   fEigenVectors_2[2][1][16] = 0.0102857654214;
   fEigenVectors_2[2][2][0] = -0.000461965968232;
   fEigenVectors_2[2][2][1] = 0.0165352109079;
   fEigenVectors_2[2][2][2] = 0.00356082651141;
   fEigenVectors_2[2][2][3] = -0.00670773762555;
   fEigenVectors_2[2][2][4] = 0.0545248966501;
   fEigenVectors_2[2][2][5] = 0.00806942157299;
   fEigenVectors_2[2][2][6] = 0.411897451668;
   fEigenVectors_2[2][2][7] = -0.857981966558;
   fEigenVectors_2[2][2][8] = -0.282770605599;
   fEigenVectors_2[2][2][9] = -0.0696711413185;
   fEigenVectors_2[2][2][10] = 0.0688679087713;
   fEigenVectors_2[2][2][11] = -0.0230436475456;
   fEigenVectors_2[2][2][12] = 0.0177815898955;
   fEigenVectors_2[2][2][13] = -0.00126879062394;
   fEigenVectors_2[2][2][14] = -0.00272645496481;
   fEigenVectors_2[2][2][15] = -0.0205845848196;
   fEigenVectors_2[2][2][16] = -0.00142101266463;
   fEigenVectors_2[2][3][0] = 0.00516392055251;
   fEigenVectors_2[2][3][1] = -0.0703537396429;
   fEigenVectors_2[2][3][2] = 0.000349675923804;
   fEigenVectors_2[2][3][3] = -0.00671149496569;
   fEigenVectors_2[2][3][4] = -0.252736207607;
   fEigenVectors_2[2][3][5] = 0.162051561345;
   fEigenVectors_2[2][3][6] = -0.838511993083;
   fEigenVectors_2[2][3][7] = -0.440053573331;
   fEigenVectors_2[2][3][8] = 0.0530884143634;
   fEigenVectors_2[2][3][9] = 0.0637144620531;
   fEigenVectors_2[2][3][10] = 0.00425805379131;
   fEigenVectors_2[2][3][11] = -0.0255567863996;
   fEigenVectors_2[2][3][12] = -0.00991492998516;
   fEigenVectors_2[2][3][13] = 0.0175568532733;
   fEigenVectors_2[2][3][14] = -0.00168097951507;
   fEigenVectors_2[2][3][15] = -0.00913154293401;
   fEigenVectors_2[2][3][16] = 0.00712441009818;
   fEigenVectors_2[2][4][0] = -2.35759233743e-05;
   fEigenVectors_2[2][4][1] = 0.00238051910585;
   fEigenVectors_2[2][4][2] = 0.00142293167211;
   fEigenVectors_2[2][4][3] = -0.00319861975782;
   fEigenVectors_2[2][4][4] = -0.000365488837887;
   fEigenVectors_2[2][4][5] = 0.000128391216235;
   fEigenVectors_2[2][4][6] = 0.00307424712561;
   fEigenVectors_2[2][4][7] = -0.00197401896128;
   fEigenVectors_2[2][4][8] = 0.0147866913156;
   fEigenVectors_2[2][4][9] = 0.00686885298163;
   fEigenVectors_2[2][4][10] = -0.00211358991282;
   fEigenVectors_2[2][4][11] = 0.00725088172235;
   fEigenVectors_2[2][4][12] = -0.376923135707;
   fEigenVectors_2[2][4][13] = -0.0238909414543;
   fEigenVectors_2[2][4][14] = -0.1890507472;
   fEigenVectors_2[2][4][15] = -0.336481042305;
   fEigenVectors_2[2][4][16] = -0.841453626034;
   fEigenVectors_2[2][5][0] = -6.48201391879e-05;
   fEigenVectors_2[2][5][1] = 0.00332723942784;
   fEigenVectors_2[2][5][2] = 0.00138186884037;
   fEigenVectors_2[2][5][3] = -0.00459529455571;
   fEigenVectors_2[2][5][4] = -0.00137589952073;
   fEigenVectors_2[2][5][5] = 0.00143087303042;
   fEigenVectors_2[2][5][6] = 0.0123968092988;
   fEigenVectors_2[2][5][7] = -0.0252856099223;
   fEigenVectors_2[2][5][8] = -0.00693616900723;
   fEigenVectors_2[2][5][9] = 0.000112537727289;
   fEigenVectors_2[2][5][10] = -0.0176118935272;
   fEigenVectors_2[2][5][11] = 0.0239168707871;
   fEigenVectors_2[2][5][12] = -0.686849575097;
   fEigenVectors_2[2][5][13] = -0.0292707817399;
   fEigenVectors_2[2][5][14] = -0.0343307642542;
   fEigenVectors_2[2][5][15] = 0.723675905536;
   fEigenVectors_2[2][5][16] = 0.0270935753603;
   fEigenVectors_2[2][6][0] = 0.000429698525038;
   fEigenVectors_2[2][6][1] = -0.0042697562908;
   fEigenVectors_2[2][6][2] = -0.00209131842707;
   fEigenVectors_2[2][6][3] = 0.00590651146242;
   fEigenVectors_2[2][6][4] = -0.00125402119639;
   fEigenVectors_2[2][6][5] = 0.00162047820335;
   fEigenVectors_2[2][6][6] = -0.0144497827438;
   fEigenVectors_2[2][6][7] = -0.00479942111052;
   fEigenVectors_2[2][6][8] = -0.0114572708015;
   fEigenVectors_2[2][6][9] = 0.00169337787289;
   fEigenVectors_2[2][6][10] = -0.00788685057997;
   fEigenVectors_2[2][6][11] = -0.00438521474993;
   fEigenVectors_2[2][6][12] = 0.614144728516;
   fEigenVectors_2[2][6][13] = 0.0281666906326;
   fEigenVectors_2[2][6][14] = -0.0360827454989;
   fEigenVectors_2[2][6][15] = 0.601337278233;
   fEigenVectors_2[2][6][16] = -0.508542160517;
   fEigenVectors_2[2][7][0] = 0.00202414221971;
   fEigenVectors_2[2][7][1] = 0.018327922091;
   fEigenVectors_2[2][7][2] = -0.00506500675485;
   fEigenVectors_2[2][7][3] = 0.000290682083433;
   fEigenVectors_2[2][7][4] = 0.0235621480689;
   fEigenVectors_2[2][7][5] = -0.0346047448329;
   fEigenVectors_2[2][7][6] = -0.0167012834953;
   fEigenVectors_2[2][7][7] = -0.0673905220725;
   fEigenVectors_2[2][7][8] = 0.377073550211;
   fEigenVectors_2[2][7][9] = -0.56573899683;
   fEigenVectors_2[2][7][10] = 0.413534231637;
   fEigenVectors_2[2][7][11] = 0.596345171442;
   fEigenVectors_2[2][7][12] = 0.015032112232;
   fEigenVectors_2[2][7][13] = -0.0623071427551;
   fEigenVectors_2[2][7][14] = 0.00696251336297;
   fEigenVectors_2[2][7][15] = 0.00418054931415;
   fEigenVectors_2[2][7][16] = -0.00196869179466;
   fEigenVectors_2[2][8][0] = 0.000939441160972;
   fEigenVectors_2[2][8][1] = 0.00967870247106;
   fEigenVectors_2[2][8][2] = -0.00224836657572;
   fEigenVectors_2[2][8][3] = -0.000674249856945;
   fEigenVectors_2[2][8][4] = 0.0106292740505;
   fEigenVectors_2[2][8][5] = -0.0151703917915;
   fEigenVectors_2[2][8][6] = 0.0081971889139;
   fEigenVectors_2[2][8][7] = -0.085650704922;
   fEigenVectors_2[2][8][8] = 0.131935877352;
   fEigenVectors_2[2][8][9] = -0.363279527464;
   fEigenVectors_2[2][8][10] = -0.899246963751;
   fEigenVectors_2[2][8][11] = 0.18165226681;
   fEigenVectors_2[2][8][12] = 0.014508641139;
   fEigenVectors_2[2][8][13] = -0.0246447975062;
   fEigenVectors_2[2][8][14] = -0.000447625978783;
   fEigenVectors_2[2][8][15] = -0.0171133010127;
   fEigenVectors_2[2][8][16] = 0.00457167129408;
   fEigenVectors_2[2][9][0] = -0.0104061057377;
   fEigenVectors_2[2][9][1] = -0.0319543761788;
   fEigenVectors_2[2][9][2] = 0.0116663361813;
   fEigenVectors_2[2][9][3] = -0.00293379685248;
   fEigenVectors_2[2][9][4] = -0.0544091150789;
   fEigenVectors_2[2][9][5] = 0.0855323394196;
   fEigenVectors_2[2][9][6] = 0.0135605235278;
   fEigenVectors_2[2][9][7] = 0.027667249703;
   fEigenVectors_2[2][9][8] = -0.282562712633;
   fEigenVectors_2[2][9][9] = 0.522985771021;
   fEigenVectors_2[2][9][10] = -0.102163720471;
   fEigenVectors_2[2][9][11] = 0.723800263213;
   fEigenVectors_2[2][9][12] = 0.0288237917097;
   fEigenVectors_2[2][9][13] = -0.313984406204;
   fEigenVectors_2[2][9][14] = 0.0144104146801;
   fEigenVectors_2[2][9][15] = -0.013435108199;
   fEigenVectors_2[2][9][16] = 0.00389772853849;
   fEigenVectors_2[2][10][0] = -0.000585328943397;
   fEigenVectors_2[2][10][1] = -0.419316790888;
   fEigenVectors_2[2][10][2] = -0.0481856049801;
   fEigenVectors_2[2][10][3] = -0.103001517432;
   fEigenVectors_2[2][10][4] = 0.719321542068;
   fEigenVectors_2[2][10][5] = -0.473823570517;
   fEigenVectors_2[2][10][6] = -0.221569175668;
   fEigenVectors_2[2][10][7] = -0.0835808349169;
   fEigenVectors_2[2][10][8] = 0.00206381871616;
   fEigenVectors_2[2][10][9] = 0.0972262737694;
   fEigenVectors_2[2][10][10] = -0.0129070549649;
   fEigenVectors_2[2][10][11] = 0.0450150775914;
   fEigenVectors_2[2][10][12] = -0.00579197657987;
   fEigenVectors_2[2][10][13] = 0.039004478103;
   fEigenVectors_2[2][10][14] = 0.00500626730143;
   fEigenVectors_2[2][10][15] = -0.000938046919457;
   fEigenVectors_2[2][10][16] = 0.000113274172781;
   fEigenVectors_2[2][11][0] = 0.00909012878133;
   fEigenVectors_2[2][11][1] = -0.161434769921;
   fEigenVectors_2[2][11][2] = -0.0332366807483;
   fEigenVectors_2[2][11][3] = 0.985230326381;
   fEigenVectors_2[2][11][4] = 0.0364129534256;
   fEigenVectors_2[2][11][5] = -0.00878938587577;
   fEigenVectors_2[2][11][6] = 9.95573609893e-05;
   fEigenVectors_2[2][11][7] = -0.0117946670092;
   fEigenVectors_2[2][11][8] = 0.00708997672643;
   fEigenVectors_2[2][11][9] = 0.00478171521924;
   fEigenVectors_2[2][11][10] = -0.00135360195172;
   fEigenVectors_2[2][11][11] = 0.00225673219226;
   fEigenVectors_2[2][11][12] = -0.0101980907538;
   fEigenVectors_2[2][11][13] = 0.00311148285108;
   fEigenVectors_2[2][11][14] = 0.018023497343;
   fEigenVectors_2[2][11][15] = -0.00189557862025;
   fEigenVectors_2[2][11][16] = -0.00287252247137;
   fEigenVectors_2[2][12][0] = -0.000913482985833;
   fEigenVectors_2[2][12][1] = -0.542156283946;
   fEigenVectors_2[2][12][2] = -0.0179794478167;
   fEigenVectors_2[2][12][3] = -0.0757554078439;
   fEigenVectors_2[2][12][4] = -0.451839717206;
   fEigenVectors_2[2][12][5] = -0.180053919727;
   fEigenVectors_2[2][12][6] = 0.137408621437;
   fEigenVectors_2[2][12][7] = 0.0335837120683;
   fEigenVectors_2[2][12][8] = -0.0562760959109;
   fEigenVectors_2[2][12][9] = 0.0402272815663;
   fEigenVectors_2[2][12][10] = -0.0151222176313;
   fEigenVectors_2[2][12][11] = 0.183221338577;
   fEigenVectors_2[2][12][12] = -0.0236086672072;
   fEigenVectors_2[2][12][13] = 0.634719905769;
   fEigenVectors_2[2][12][14] = -0.0369832745699;
   fEigenVectors_2[2][12][15] = -0.00521616670473;
   fEigenVectors_2[2][12][16] = 0.00322109929414;
   fEigenVectors_2[2][13][0] = -0.0126544631807;
   fEigenVectors_2[2][13][1] = -0.443528687755;
   fEigenVectors_2[2][13][2] = 0.019265736445;
   fEigenVectors_2[2][13][3] = -0.0755279662356;
   fEigenVectors_2[2][13][4] = 0.311350890716;
   fEigenVectors_2[2][13][5] = 0.826544672987;
   fEigenVectors_2[2][13][6] = 0.0769174964393;
   fEigenVectors_2[2][13][7] = 0.0503186043269;
   fEigenVectors_2[2][13][8] = 0.0350755705514;
   fEigenVectors_2[2][13][9] = -0.0573979145069;
   fEigenVectors_2[2][13][10] = 0.00429204889987;
   fEigenVectors_2[2][13][11] = -0.0157620186289;
   fEigenVectors_2[2][13][12] = -0.00402872012513;
   fEigenVectors_2[2][13][13] = 0.0604545217182;
   fEigenVectors_2[2][13][14] = -0.00447275969065;
   fEigenVectors_2[2][13][15] = 0.000292381639737;
   fEigenVectors_2[2][13][16] = 0.000196519340127;
   fEigenVectors_2[2][14][0] = 0.00139024113791;
   fEigenVectors_2[2][14][1] = -0.546728491725;
   fEigenVectors_2[2][14][2] = -0.026646551669;
   fEigenVectors_2[2][14][3] = -0.0770421473897;
   fEigenVectors_2[2][14][4] = -0.329776190991;
   fEigenVectors_2[2][14][5] = -0.149373664884;
   fEigenVectors_2[2][14][6] = 0.0914756685953;
   fEigenVectors_2[2][14][7] = 0.018445557141;
   fEigenVectors_2[2][14][8] = 0.0402922281024;
   fEigenVectors_2[2][14][9] = -0.134499219914;
   fEigenVectors_2[2][14][10] = 0.0269924102128;
   fEigenVectors_2[2][14][11] = -0.219984778865;
   fEigenVectors_2[2][14][12] = 0.0225935035479;
   fEigenVectors_2[2][14][13] = -0.694719905183;
   fEigenVectors_2[2][14][14] = 0.0510631468925;
   fEigenVectors_2[2][14][15] = 0.00519122784322;
   fEigenVectors_2[2][14][16] = -0.0071849930804;
   fEigenVectors_2[2][15][0] = 0.00049244938817;
   fEigenVectors_2[2][15][1] = -0.0117247625286;
   fEigenVectors_2[2][15][2] = -0.00425636337765;
   fEigenVectors_2[2][15][3] = 0.0173514548176;
   fEigenVectors_2[2][15][4] = 0.00273309128764;
   fEigenVectors_2[2][15][5] = -0.00665727651462;
   fEigenVectors_2[2][15][6] = -0.00327397976277;
   fEigenVectors_2[2][15][7] = 0.00467727070213;
   fEigenVectors_2[2][15][8] = -0.00379281752564;
   fEigenVectors_2[2][15][9] = -0.00805811996319;
   fEigenVectors_2[2][15][10] = 0.00519803548492;
   fEigenVectors_2[2][15][11] = -0.00497792059936;
   fEigenVectors_2[2][15][12] = 0.0765562544225;
   fEigenVectors_2[2][15][13] = -0.0607338998682;
   fEigenVectors_2[2][15][14] = -0.978328436595;
   fEigenVectors_2[2][15][15] = 0.0177261862448;
   fEigenVectors_2[2][15][16] = 0.17982597326;
   fEigenVectors_2[2][16][0] = 0.00710734647405;
   fEigenVectors_2[2][16][1] = 0.0410256930596;
   fEigenVectors_2[2][16][2] = -0.997448003124;
   fEigenVectors_2[2][16][3] = -0.0261192726235;
   fEigenVectors_2[2][16][4] = -0.0136323955169;
   fEigenVectors_2[2][16][5] = 0.0477848423196;
   fEigenVectors_2[2][16][6] = 0.00869836163473;
   fEigenVectors_2[2][16][7] = 0.00200087209083;
   fEigenVectors_2[2][16][8] = -0.00650816345887;
   fEigenVectors_2[2][16][9] = 0.00639583989866;
   fEigenVectors_2[2][16][10] = -0.000736529896142;
   fEigenVectors_2[2][16][11] = 0.00509480351081;
   fEigenVectors_2[2][16][12] = -0.00245750544299;
   fEigenVectors_2[2][16][13] = 0.00311809458702;
   fEigenVectors_2[2][16][14] = 0.00243520816819;
   fEigenVectors_2[2][16][15] = -0.000966869265435;
   fEigenVectors_2[2][16][16] = -0.000595877088593;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::Transform_2( std::vector<double>& iv, int cls ) const
{
   // PCA transformation
   const int nVar = 17;
   double *dv = new double[nVar];
   double *rv = new double[nVar];
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
   } 

   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];

   // Perform PCA and put it into PCAed events tree
   this->X2P_2( dv, rv, cls );
   for (int ivar=0; ivar<nVar; ivar++) iv[indicesPut.at(ivar)] = rv[ivar];

   delete [] dv;
   delete [] rv;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_2x_n-6::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
