// Class: ReadkMLP_pca_ce_200_4(n+2)_no_ev
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_pca_ce_200_4(n+2)_no_ev
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Mon Sep 30 14:30:44 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/hades/user/knowakow/PP/FAT/PPIMPIPPIM/TMVAeval_DataDriven_multiple
Training events: 132550
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "200" [Number of training cycles]
HiddenLayers: "N+2,N+2,N+2,N+2" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [0.000129323248984,568.511230469]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [0.000169199935044,570.143310547]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-12820.3613281,117643.984375]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-30494.9765625,233789.203125]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-35846.2929688,742903.3125]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-4408.59033203,5815.69433594]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-4839.04052734,10528.8847656]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-21899.5410156,32938.125]
oa_lambda                     oa_lambda                     oa_lambda                     oa_lambda                     deg                               'F'    [0.0706751123071,179.984664917]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.00990104675293,3667.81396484]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.052237238735,752596.375]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_pca_ce_200_4(n+2)_no_ev : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_pca_ce_200_4(n+2)_no_ev( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_pca_ce_200_4(n+2)_no_ev" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "oa_lambda", "dist_lambda_ver_pip_pim", "dist_ver_to_ver" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_pca_ce_200_4(n+2)_no_ev() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[6];
   double fWeightMatrix0to1[14][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[14][14];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[14][14];   // weight matrix from layer 3 to 4
   double fWeightMatrix4to5[1][14];   // weight matrix from layer 4 to 5

   double * fWeights[6];
};

inline void ReadkMLP_pca_ce_200_4(n+2)_no_ev::Initialize()
{
   // build network structure
   fLayers = 6;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 14; fWeights[3] = new double[14]; 
   fLayerSize[4] = 14; fWeights[4] = new double[14]; 
   fLayerSize[5] = 1; fWeights[5] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 3.08480178404361;
   fWeightMatrix0to1[1][0] = 7.0878354549744;
   fWeightMatrix0to1[2][0] = 0.215891829580895;
   fWeightMatrix0to1[3][0] = -1.0254694245163;
   fWeightMatrix0to1[4][0] = -1.72914501683683;
   fWeightMatrix0to1[5][0] = -13.1109015432771;
   fWeightMatrix0to1[6][0] = -0.720611895048605;
   fWeightMatrix0to1[7][0] = 7.05467611921929;
   fWeightMatrix0to1[8][0] = -1.7511825934975;
   fWeightMatrix0to1[9][0] = -7.24946078180615;
   fWeightMatrix0to1[10][0] = -7.7083305671212;
   fWeightMatrix0to1[11][0] = -12.499930270521;
   fWeightMatrix0to1[12][0] = 2.59764639253408;
   fWeightMatrix0to1[0][1] = 0.258913639579137;
   fWeightMatrix0to1[1][1] = -0.588821090656232;
   fWeightMatrix0to1[2][1] = 1.56060725398409;
   fWeightMatrix0to1[3][1] = -2.26936222167461;
   fWeightMatrix0to1[4][1] = 4.03857159861674;
   fWeightMatrix0to1[5][1] = -7.79625696370613;
   fWeightMatrix0to1[6][1] = 1.78508481481012;
   fWeightMatrix0to1[7][1] = -0.596612585247296;
   fWeightMatrix0to1[8][1] = -1.94382980382587;
   fWeightMatrix0to1[9][1] = 3.03745122444786;
   fWeightMatrix0to1[10][1] = -3.84281920086913;
   fWeightMatrix0to1[11][1] = -9.82267595180335;
   fWeightMatrix0to1[12][1] = 2.97587292098012;
   fWeightMatrix0to1[0][2] = 1.14833216138433;
   fWeightMatrix0to1[1][2] = -2.58327181632157;
   fWeightMatrix0to1[2][2] = -1.96639400909758;
   fWeightMatrix0to1[3][2] = 0.641195242558563;
   fWeightMatrix0to1[4][2] = -0.335070044120303;
   fWeightMatrix0to1[5][2] = 8.72860211296922;
   fWeightMatrix0to1[6][2] = -0.358146246113264;
   fWeightMatrix0to1[7][2] = -1.118876325705;
   fWeightMatrix0to1[8][2] = 0.688046552620071;
   fWeightMatrix0to1[9][2] = -0.296663527593881;
   fWeightMatrix0to1[10][2] = 0.877556659508299;
   fWeightMatrix0to1[11][2] = 9.31100177408354;
   fWeightMatrix0to1[12][2] = -2.65079984012358;
   fWeightMatrix0to1[0][3] = 0.759859454558693;
   fWeightMatrix0to1[1][3] = -0.195520101813313;
   fWeightMatrix0to1[2][3] = 0.827632944338171;
   fWeightMatrix0to1[3][3] = 2.35367944373291;
   fWeightMatrix0to1[4][3] = 0.324997051558429;
   fWeightMatrix0to1[5][3] = 5.58413660402805;
   fWeightMatrix0to1[6][3] = -1.6567116285993;
   fWeightMatrix0to1[7][3] = -0.123183089223716;
   fWeightMatrix0to1[8][3] = 0.49809381796985;
   fWeightMatrix0to1[9][3] = 1.55513742563489;
   fWeightMatrix0to1[10][3] = 3.64652800696597;
   fWeightMatrix0to1[11][3] = 8.32010115587427;
   fWeightMatrix0to1[12][3] = -0.0131576317729803;
   fWeightMatrix0to1[0][4] = -2.10646205705895;
   fWeightMatrix0to1[1][4] = -0.32686245552556;
   fWeightMatrix0to1[2][4] = -1.91105539690118;
   fWeightMatrix0to1[3][4] = -0.374369052233981;
   fWeightMatrix0to1[4][4] = -2.30896801734257;
   fWeightMatrix0to1[5][4] = 5.63831705462848;
   fWeightMatrix0to1[6][4] = 1.47372184371707;
   fWeightMatrix0to1[7][4] = -0.41076523106298;
   fWeightMatrix0to1[8][4] = -1.11477579790399;
   fWeightMatrix0to1[9][4] = 0.505198714150264;
   fWeightMatrix0to1[10][4] = 2.25384598359685;
   fWeightMatrix0to1[11][4] = 8.54436487351252;
   fWeightMatrix0to1[12][4] = 0.273364487932238;
   fWeightMatrix0to1[0][5] = -0.474120015641383;
   fWeightMatrix0to1[1][5] = -0.0154434397567106;
   fWeightMatrix0to1[2][5] = -1.31862387922934;
   fWeightMatrix0to1[3][5] = 0.503251720731858;
   fWeightMatrix0to1[4][5] = -1.23081300452929;
   fWeightMatrix0to1[5][5] = 0.829678943542044;
   fWeightMatrix0to1[6][5] = -1.42326503571895;
   fWeightMatrix0to1[7][5] = 0.561377818508594;
   fWeightMatrix0to1[8][5] = 1.19698621549531;
   fWeightMatrix0to1[9][5] = 1.44544684205547;
   fWeightMatrix0to1[10][5] = -0.100722609550983;
   fWeightMatrix0to1[11][5] = -0.206648261204433;
   fWeightMatrix0to1[12][5] = -2.09729848037411;
   fWeightMatrix0to1[0][6] = 0.796912048984369;
   fWeightMatrix0to1[1][6] = -0.347536415111669;
   fWeightMatrix0to1[2][6] = 1.93611661424396;
   fWeightMatrix0to1[3][6] = 0.817067203650893;
   fWeightMatrix0to1[4][6] = 1.0857751927765;
   fWeightMatrix0to1[5][6] = 1.94021232622187;
   fWeightMatrix0to1[6][6] = -0.90225020458859;
   fWeightMatrix0to1[7][6] = -0.675744517173572;
   fWeightMatrix0to1[8][6] = 1.24706340878047;
   fWeightMatrix0to1[9][6] = -0.894487332983823;
   fWeightMatrix0to1[10][6] = -0.560221535051207;
   fWeightMatrix0to1[11][6] = 1.10795730597009;
   fWeightMatrix0to1[12][6] = -0.737844079072186;
   fWeightMatrix0to1[0][7] = -0.637094006398916;
   fWeightMatrix0to1[1][7] = 1.96239572119139;
   fWeightMatrix0to1[2][7] = -1.78481545527761;
   fWeightMatrix0to1[3][7] = -1.22006075334417;
   fWeightMatrix0to1[4][7] = 2.07394199432666;
   fWeightMatrix0to1[5][7] = -0.43345590984045;
   fWeightMatrix0to1[6][7] = -1.53808031690871;
   fWeightMatrix0to1[7][7] = -2.27895463053315;
   fWeightMatrix0to1[8][7] = 0.195166751794594;
   fWeightMatrix0to1[9][7] = -1.47706310006919;
   fWeightMatrix0to1[10][7] = -1.48961693136612;
   fWeightMatrix0to1[11][7] = 1.04637343509597;
   fWeightMatrix0to1[12][7] = 1.5173420894629;
   fWeightMatrix0to1[0][8] = -7.54251541186737;
   fWeightMatrix0to1[1][8] = 6.44770737666366;
   fWeightMatrix0to1[2][8] = -2.6455790032182;
   fWeightMatrix0to1[3][8] = -6.14063204884588;
   fWeightMatrix0to1[4][8] = -7.29195760891222;
   fWeightMatrix0to1[5][8] = 0.240339931267745;
   fWeightMatrix0to1[6][8] = -1.86350439641154;
   fWeightMatrix0to1[7][8] = -5.852528247689;
   fWeightMatrix0to1[8][8] = 1.20054221313898;
   fWeightMatrix0to1[9][8] = 0.539229799030169;
   fWeightMatrix0to1[10][8] = -4.12045299596356;
   fWeightMatrix0to1[11][8] = -0.218029551535582;
   fWeightMatrix0to1[12][8] = -0.194314806940913;
   fWeightMatrix0to1[0][9] = -0.373599004079504;
   fWeightMatrix0to1[1][9] = 3.33329326577633;
   fWeightMatrix0to1[2][9] = -0.291593928470596;
   fWeightMatrix0to1[3][9] = -2.77738017530838;
   fWeightMatrix0to1[4][9] = 6.02264230427292;
   fWeightMatrix0to1[5][9] = -14.5892991501251;
   fWeightMatrix0to1[6][9] = 2.60024598549463;
   fWeightMatrix0to1[7][9] = 2.76365995089834;
   fWeightMatrix0to1[8][9] = -0.578650932260498;
   fWeightMatrix0to1[9][9] = 3.28678291715775;
   fWeightMatrix0to1[10][9] = -1.69104535159503;
   fWeightMatrix0to1[11][9] = -18.2645351987721;
   fWeightMatrix0to1[12][9] = 3.37489096693416;
   fWeightMatrix0to1[0][10] = -0.346107292680201;
   fWeightMatrix0to1[1][10] = -3.75209954473836;
   fWeightMatrix0to1[2][10] = 0.610263214763951;
   fWeightMatrix0to1[3][10] = -0.791826831147892;
   fWeightMatrix0to1[4][10] = -1.01631409095739;
   fWeightMatrix0to1[5][10] = 9.5301425242845;
   fWeightMatrix0to1[6][10] = 1.74996187656133;
   fWeightMatrix0to1[7][10] = -3.04749941283061;
   fWeightMatrix0to1[8][10] = 0.883702916243548;
   fWeightMatrix0to1[9][10] = 1.58180879928256;
   fWeightMatrix0to1[10][10] = 4.47438421974578;
   fWeightMatrix0to1[11][10] = 9.04773814420516;
   fWeightMatrix0to1[12][10] = -3.21523840363689;
   fWeightMatrix0to1[0][11] = 0.25168039033107;
   fWeightMatrix0to1[1][11] = 0.417190612604984;
   fWeightMatrix0to1[2][11] = 1.59165198963637;
   fWeightMatrix0to1[3][11] = 0.582527582213388;
   fWeightMatrix0to1[4][11] = 0.602606620374764;
   fWeightMatrix0to1[5][11] = -8.62169372568562;
   fWeightMatrix0to1[6][11] = 0.191886115332972;
   fWeightMatrix0to1[7][11] = -0.198472292247747;
   fWeightMatrix0to1[8][11] = 0.0724787935236851;
   fWeightMatrix0to1[9][11] = 1.65921842668674;
   fWeightMatrix0to1[10][11] = -3.41286027382216;
   fWeightMatrix0to1[11][11] = -9.3332377543565;
   fWeightMatrix0to1[12][11] = 1.9933481241492;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.289001172860509;
   fWeightMatrix1to2[1][0] = 3.81533062245615;
   fWeightMatrix1to2[2][0] = 0.567680575307908;
   fWeightMatrix1to2[3][0] = -2.01097082310114;
   fWeightMatrix1to2[4][0] = 1.9649243380815;
   fWeightMatrix1to2[5][0] = 0.678602146245169;
   fWeightMatrix1to2[6][0] = 2.70738487969454;
   fWeightMatrix1to2[7][0] = 1.98759363940534;
   fWeightMatrix1to2[8][0] = 1.00490527098922;
   fWeightMatrix1to2[9][0] = -1.08074298824385;
   fWeightMatrix1to2[10][0] = -2.00791070464737;
   fWeightMatrix1to2[11][0] = 0.341570978747874;
   fWeightMatrix1to2[12][0] = -0.765069173417682;
   fWeightMatrix1to2[0][1] = 1.66985020596241;
   fWeightMatrix1to2[1][1] = 1.53707906685721;
   fWeightMatrix1to2[2][1] = 0.61079188287066;
   fWeightMatrix1to2[3][1] = -2.40341529320149;
   fWeightMatrix1to2[4][1] = 3.71510001258993;
   fWeightMatrix1to2[5][1] = 3.26908298267963;
   fWeightMatrix1to2[6][1] = -1.09867206497227;
   fWeightMatrix1to2[7][1] = 4.53592239509243;
   fWeightMatrix1to2[8][1] = 0.0288288065645091;
   fWeightMatrix1to2[9][1] = 0.734888365303831;
   fWeightMatrix1to2[10][1] = -4.95421746056043;
   fWeightMatrix1to2[11][1] = -2.48022437975397;
   fWeightMatrix1to2[12][1] = 4.32847112408426;
   fWeightMatrix1to2[0][2] = 1.13020976767771;
   fWeightMatrix1to2[1][2] = -0.677934760271841;
   fWeightMatrix1to2[2][2] = -0.532748297530711;
   fWeightMatrix1to2[3][2] = -1.50651959894944;
   fWeightMatrix1to2[4][2] = -0.678542048451468;
   fWeightMatrix1to2[5][2] = 0.739182500631192;
   fWeightMatrix1to2[6][2] = 2.01977898632497;
   fWeightMatrix1to2[7][2] = -1.39201446821348;
   fWeightMatrix1to2[8][2] = -1.14958705450524;
   fWeightMatrix1to2[9][2] = 0.40521700306864;
   fWeightMatrix1to2[10][2] = 2.32013301759801;
   fWeightMatrix1to2[11][2] = 0.797444337827671;
   fWeightMatrix1to2[12][2] = 0.865404598362286;
   fWeightMatrix1to2[0][3] = -1.61054095409319;
   fWeightMatrix1to2[1][3] = -0.259239635626866;
   fWeightMatrix1to2[2][3] = 1.20027774408674;
   fWeightMatrix1to2[3][3] = -0.909426776148475;
   fWeightMatrix1to2[4][3] = -5.50071517645827;
   fWeightMatrix1to2[5][3] = -2.62610787709082;
   fWeightMatrix1to2[6][3] = 1.68997929426507;
   fWeightMatrix1to2[7][3] = -1.08688326806518;
   fWeightMatrix1to2[8][3] = -2.01686823433346;
   fWeightMatrix1to2[9][3] = 1.84149566613198;
   fWeightMatrix1to2[10][3] = 1.11497223505337;
   fWeightMatrix1to2[11][3] = 0.100493328492993;
   fWeightMatrix1to2[12][3] = 0.000595099518940278;
   fWeightMatrix1to2[0][4] = 1.99681330300641;
   fWeightMatrix1to2[1][4] = 3.38782536761181;
   fWeightMatrix1to2[2][4] = -2.10383325317318;
   fWeightMatrix1to2[3][4] = -0.690084401010863;
   fWeightMatrix1to2[4][4] = -1.02205978534411;
   fWeightMatrix1to2[5][4] = -0.605787366475233;
   fWeightMatrix1to2[6][4] = 2.89272319161046;
   fWeightMatrix1to2[7][4] = 0.448730780653784;
   fWeightMatrix1to2[8][4] = 0.901040849230014;
   fWeightMatrix1to2[9][4] = 0.0504925225999154;
   fWeightMatrix1to2[10][4] = 2.97867459435787;
   fWeightMatrix1to2[11][4] = -3.79331332288035;
   fWeightMatrix1to2[12][4] = -1.26818510168715;
   fWeightMatrix1to2[0][5] = -1.69114698140858;
   fWeightMatrix1to2[1][5] = -3.31235154325187;
   fWeightMatrix1to2[2][5] = 0.208322151705136;
   fWeightMatrix1to2[3][5] = 5.50510187393013;
   fWeightMatrix1to2[4][5] = -1.24111554188117;
   fWeightMatrix1to2[5][5] = 3.17991068079129;
   fWeightMatrix1to2[6][5] = -2.72656372747799;
   fWeightMatrix1to2[7][5] = -2.81467188277889;
   fWeightMatrix1to2[8][5] = -1.00260007431957;
   fWeightMatrix1to2[9][5] = 1.10719868768753;
   fWeightMatrix1to2[10][5] = -1.42772299437505;
   fWeightMatrix1to2[11][5] = 3.09534985018408;
   fWeightMatrix1to2[12][5] = -3.46132942738705;
   fWeightMatrix1to2[0][6] = 1.39313066707987;
   fWeightMatrix1to2[1][6] = -1.57228270271405;
   fWeightMatrix1to2[2][6] = 0.623894596980586;
   fWeightMatrix1to2[3][6] = -0.077422279790748;
   fWeightMatrix1to2[4][6] = -1.96948379272029;
   fWeightMatrix1to2[5][6] = -1.36937960548152;
   fWeightMatrix1to2[6][6] = -1.75843158184494;
   fWeightMatrix1to2[7][6] = -0.00661062691632493;
   fWeightMatrix1to2[8][6] = -1.90027904915895;
   fWeightMatrix1to2[9][6] = -1.63302736094691;
   fWeightMatrix1to2[10][6] = -1.84583749498255;
   fWeightMatrix1to2[11][6] = -0.143776281965479;
   fWeightMatrix1to2[12][6] = -2.00111353822494;
   fWeightMatrix1to2[0][7] = -1.82363860191918;
   fWeightMatrix1to2[1][7] = 4.93137162834114;
   fWeightMatrix1to2[2][7] = -0.824967842734953;
   fWeightMatrix1to2[3][7] = -0.733596906968136;
   fWeightMatrix1to2[4][7] = 0.362598309884661;
   fWeightMatrix1to2[5][7] = -0.0922262928127278;
   fWeightMatrix1to2[6][7] = 4.44987754620724;
   fWeightMatrix1to2[7][7] = 5.19699767946835;
   fWeightMatrix1to2[8][7] = -0.921935881262273;
   fWeightMatrix1to2[9][7] = -2.06210668873479;
   fWeightMatrix1to2[10][7] = -4.2311719599719;
   fWeightMatrix1to2[11][7] = -1.53516584820156;
   fWeightMatrix1to2[12][7] = -2.08291881272211;
   fWeightMatrix1to2[0][8] = 0.136402960461782;
   fWeightMatrix1to2[1][8] = -0.828817104480325;
   fWeightMatrix1to2[2][8] = 1.74176949249577;
   fWeightMatrix1to2[3][8] = -0.509725518028127;
   fWeightMatrix1to2[4][8] = -1.52831199184816;
   fWeightMatrix1to2[5][8] = -1.25549190463421;
   fWeightMatrix1to2[6][8] = -1.46434458760346;
   fWeightMatrix1to2[7][8] = 0.76905641199804;
   fWeightMatrix1to2[8][8] = 1.21137213496348;
   fWeightMatrix1to2[9][8] = -0.75361548097309;
   fWeightMatrix1to2[10][8] = -0.965064607762254;
   fWeightMatrix1to2[11][8] = 0.715605802142173;
   fWeightMatrix1to2[12][8] = 2.24126461927858;
   fWeightMatrix1to2[0][9] = -0.254545797800858;
   fWeightMatrix1to2[1][9] = -1.39899546114708;
   fWeightMatrix1to2[2][9] = -0.970522537553079;
   fWeightMatrix1to2[3][9] = 1.63150784106136;
   fWeightMatrix1to2[4][9] = 1.92085519852839;
   fWeightMatrix1to2[5][9] = 1.47268472327908;
   fWeightMatrix1to2[6][9] = -1.67773243419136;
   fWeightMatrix1to2[7][9] = -4.83024032351976;
   fWeightMatrix1to2[8][9] = -0.156549432326853;
   fWeightMatrix1to2[9][9] = -2.06169655533835;
   fWeightMatrix1to2[10][9] = 1.30793660812973;
   fWeightMatrix1to2[11][9] = -3.66349517743769;
   fWeightMatrix1to2[12][9] = -1.74965092252316;
   fWeightMatrix1to2[0][10] = -4.11439552449308;
   fWeightMatrix1to2[1][10] = 2.56742324484834;
   fWeightMatrix1to2[2][10] = -2.48840104391008;
   fWeightMatrix1to2[3][10] = 3.07972705373348;
   fWeightMatrix1to2[4][10] = -3.07718936585186;
   fWeightMatrix1to2[5][10] = 0.997314857996537;
   fWeightMatrix1to2[6][10] = -1.92669680762812;
   fWeightMatrix1to2[7][10] = -1.04103664674584;
   fWeightMatrix1to2[8][10] = 0.837722360472683;
   fWeightMatrix1to2[9][10] = -2.0150650803341;
   fWeightMatrix1to2[10][10] = 0.252631685244707;
   fWeightMatrix1to2[11][10] = 1.11838678187883;
   fWeightMatrix1to2[12][10] = -1.40964367682938;
   fWeightMatrix1to2[0][11] = -2.85090594298828;
   fWeightMatrix1to2[1][11] = -3.01203219903728;
   fWeightMatrix1to2[2][11] = -1.33048805608965;
   fWeightMatrix1to2[3][11] = 5.87473832955577;
   fWeightMatrix1to2[4][11] = -1.43340568324777;
   fWeightMatrix1to2[5][11] = 3.35998460118567;
   fWeightMatrix1to2[6][11] = -2.76409750766606;
   fWeightMatrix1to2[7][11] = -3.60804470774918;
   fWeightMatrix1to2[8][11] = -1.63058455819305;
   fWeightMatrix1to2[9][11] = -0.773120796293016;
   fWeightMatrix1to2[10][11] = -3.69899222362404;
   fWeightMatrix1to2[11][11] = 4.31036598587453;
   fWeightMatrix1to2[12][11] = -3.56402199127768;
   fWeightMatrix1to2[0][12] = -0.702098961628093;
   fWeightMatrix1to2[1][12] = 0.951841234850676;
   fWeightMatrix1to2[2][12] = -0.234470010297017;
   fWeightMatrix1to2[3][12] = -1.26213116693699;
   fWeightMatrix1to2[4][12] = 2.3249496732281;
   fWeightMatrix1to2[5][12] = -0.888987223960566;
   fWeightMatrix1to2[6][12] = 1.49935939321525;
   fWeightMatrix1to2[7][12] = -0.0442386291704188;
   fWeightMatrix1to2[8][12] = -1.05663745809526;
   fWeightMatrix1to2[9][12] = -1.53464784025363;
   fWeightMatrix1to2[10][12] = 0.26256701869077;
   fWeightMatrix1to2[11][12] = -2.05486550452815;
   fWeightMatrix1to2[12][12] = 1.02291450493124;
   fWeightMatrix1to2[0][13] = 2.2900081462354;
   fWeightMatrix1to2[1][13] = 1.22659595793526;
   fWeightMatrix1to2[2][13] = 1.30440065284847;
   fWeightMatrix1to2[3][13] = -2.98933145543861;
   fWeightMatrix1to2[4][13] = 0.681630720625718;
   fWeightMatrix1to2[5][13] = -3.2471212223795;
   fWeightMatrix1to2[6][13] = 1.64863513545332;
   fWeightMatrix1to2[7][13] = -1.53779505299754;
   fWeightMatrix1to2[8][13] = -1.85341871631102;
   fWeightMatrix1to2[9][13] = -0.29749178893768;
   fWeightMatrix1to2[10][13] = 1.03873389698864;
   fWeightMatrix1to2[11][13] = -0.467976212440781;
   fWeightMatrix1to2[12][13] = 2.63562515981519;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.586098114092493;
   fWeightMatrix2to3[1][0] = -0.0302424667079402;
   fWeightMatrix2to3[2][0] = 0.975840690497246;
   fWeightMatrix2to3[3][0] = -1.30566316715095;
   fWeightMatrix2to3[4][0] = 2.36157641390069;
   fWeightMatrix2to3[5][0] = -0.383643279510168;
   fWeightMatrix2to3[6][0] = -0.316557734673543;
   fWeightMatrix2to3[7][0] = -1.67796821372335;
   fWeightMatrix2to3[8][0] = 0.599154593460471;
   fWeightMatrix2to3[9][0] = 0.576651067258495;
   fWeightMatrix2to3[10][0] = 1.27546969591483;
   fWeightMatrix2to3[11][0] = -1.71329447856875;
   fWeightMatrix2to3[12][0] = 2.79256190399408;
   fWeightMatrix2to3[0][1] = 3.37302130656804;
   fWeightMatrix2to3[1][1] = 0.342673799589059;
   fWeightMatrix2to3[2][1] = -0.461966320127779;
   fWeightMatrix2to3[3][1] = -2.88921800080612;
   fWeightMatrix2to3[4][1] = -2.57398634751834;
   fWeightMatrix2to3[5][1] = -1.03554612727655;
   fWeightMatrix2to3[6][1] = 0.857764083993993;
   fWeightMatrix2to3[7][1] = 0.919297892165892;
   fWeightMatrix2to3[8][1] = 0.105603442985085;
   fWeightMatrix2to3[9][1] = 0.851289355911185;
   fWeightMatrix2to3[10][1] = -1.32186037019807;
   fWeightMatrix2to3[11][1] = -3.17551859336353;
   fWeightMatrix2to3[12][1] = -1.24414496709111;
   fWeightMatrix2to3[0][2] = -0.234729950640939;
   fWeightMatrix2to3[1][2] = -2.786661710537;
   fWeightMatrix2to3[2][2] = -0.766446589300311;
   fWeightMatrix2to3[3][2] = -1.46283858885689;
   fWeightMatrix2to3[4][2] = -0.426319999882711;
   fWeightMatrix2to3[5][2] = -1.58583976453779;
   fWeightMatrix2to3[6][2] = 0.976706300214165;
   fWeightMatrix2to3[7][2] = -2.42478924735213;
   fWeightMatrix2to3[8][2] = -1.29148370783248;
   fWeightMatrix2to3[9][2] = 1.93471560578189;
   fWeightMatrix2to3[10][2] = 0.196351740599666;
   fWeightMatrix2to3[11][2] = 0.287490197190118;
   fWeightMatrix2to3[12][2] = 1.28043506378073;
   fWeightMatrix2to3[0][3] = 0.319360896572358;
   fWeightMatrix2to3[1][3] = 1.81292785963362;
   fWeightMatrix2to3[2][3] = 0.58410952442173;
   fWeightMatrix2to3[3][3] = 2.57632900708469;
   fWeightMatrix2to3[4][3] = -0.14152242918717;
   fWeightMatrix2to3[5][3] = -2.03526541219235;
   fWeightMatrix2to3[6][3] = 0.662397041118244;
   fWeightMatrix2to3[7][3] = 0.0950961015487516;
   fWeightMatrix2to3[8][3] = 0.253574500408425;
   fWeightMatrix2to3[9][3] = 1.21218977688518;
   fWeightMatrix2to3[10][3] = 1.69284678916286;
   fWeightMatrix2to3[11][3] = 4.55054530124368;
   fWeightMatrix2to3[12][3] = -0.997738712998973;
   fWeightMatrix2to3[0][4] = 1.59112041836925;
   fWeightMatrix2to3[1][4] = 0.880746309084268;
   fWeightMatrix2to3[2][4] = -1.87179709892685;
   fWeightMatrix2to3[3][4] = -2.99309822296298;
   fWeightMatrix2to3[4][4] = -2.79013284711765;
   fWeightMatrix2to3[5][4] = 2.6603265151582;
   fWeightMatrix2to3[6][4] = -0.484141633375961;
   fWeightMatrix2to3[7][4] = 3.7154578161528;
   fWeightMatrix2to3[8][4] = 2.39289221857089;
   fWeightMatrix2to3[9][4] = -0.390482517999427;
   fWeightMatrix2to3[10][4] = 2.84102898956166;
   fWeightMatrix2to3[11][4] = 1.32713242221893;
   fWeightMatrix2to3[12][4] = 0.980013585681334;
   fWeightMatrix2to3[0][5] = -0.534973406403682;
   fWeightMatrix2to3[1][5] = 1.40805451327627;
   fWeightMatrix2to3[2][5] = -1.71950920675395;
   fWeightMatrix2to3[3][5] = 2.13878186765667;
   fWeightMatrix2to3[4][5] = 2.87136325344734;
   fWeightMatrix2to3[5][5] = -0.873623262677782;
   fWeightMatrix2to3[6][5] = -2.16411914818721;
   fWeightMatrix2to3[7][5] = 0.280597559479279;
   fWeightMatrix2to3[8][5] = -1.527104173696;
   fWeightMatrix2to3[9][5] = 0.739227154868013;
   fWeightMatrix2to3[10][5] = -2.65860804831546;
   fWeightMatrix2to3[11][5] = 0.93984840258962;
   fWeightMatrix2to3[12][5] = 0.62056791725141;
   fWeightMatrix2to3[0][6] = 3.15796392185884;
   fWeightMatrix2to3[1][6] = 0.827702968443096;
   fWeightMatrix2to3[2][6] = 2.06596390834271;
   fWeightMatrix2to3[3][6] = -1.66540773391974;
   fWeightMatrix2to3[4][6] = -1.1917257646477;
   fWeightMatrix2to3[5][6] = -0.308213141173139;
   fWeightMatrix2to3[6][6] = 3.38259430944304;
   fWeightMatrix2to3[7][6] = -2.38818861904316;
   fWeightMatrix2to3[8][6] = -1.43408550661609;
   fWeightMatrix2to3[9][6] = -0.212058410015905;
   fWeightMatrix2to3[10][6] = -2.4677714242526;
   fWeightMatrix2to3[11][6] = -3.06924348791265;
   fWeightMatrix2to3[12][6] = -2.85163274604997;
   fWeightMatrix2to3[0][7] = 1.35819981423615;
   fWeightMatrix2to3[1][7] = 0.0398120265998425;
   fWeightMatrix2to3[2][7] = -3.67799518048199;
   fWeightMatrix2to3[3][7] = -2.36758106130425;
   fWeightMatrix2to3[4][7] = -1.50059042749426;
   fWeightMatrix2to3[5][7] = 5.72446368318444;
   fWeightMatrix2to3[6][7] = 2.65797325324245;
   fWeightMatrix2to3[7][7] = 2.82260054257404;
   fWeightMatrix2to3[8][7] = -0.845814835391694;
   fWeightMatrix2to3[9][7] = -3.60965303047567;
   fWeightMatrix2to3[10][7] = 0.787794217198593;
   fWeightMatrix2to3[11][7] = -1.74888122823603;
   fWeightMatrix2to3[12][7] = -1.50105988514486;
   fWeightMatrix2to3[0][8] = -0.724126346754594;
   fWeightMatrix2to3[1][8] = 0.0680410140137562;
   fWeightMatrix2to3[2][8] = -1.51614229775286;
   fWeightMatrix2to3[3][8] = 1.4476544445085;
   fWeightMatrix2to3[4][8] = 1.13779516423287;
   fWeightMatrix2to3[5][8] = 0.265723156421181;
   fWeightMatrix2to3[6][8] = -0.656623073479136;
   fWeightMatrix2to3[7][8] = -0.787415200040424;
   fWeightMatrix2to3[8][8] = 1.82516315519739;
   fWeightMatrix2to3[9][8] = -0.645592019748721;
   fWeightMatrix2to3[10][8] = 0.364093205969902;
   fWeightMatrix2to3[11][8] = 1.56707666240971;
   fWeightMatrix2to3[12][8] = 1.541276234194;
   fWeightMatrix2to3[0][9] = -1.30424265938087;
   fWeightMatrix2to3[1][9] = 1.26841148880409;
   fWeightMatrix2to3[2][9] = -1.94725564888332;
   fWeightMatrix2to3[3][9] = 1.14693826311282;
   fWeightMatrix2to3[4][9] = 2.42902265208737;
   fWeightMatrix2to3[5][9] = -0.244123723298968;
   fWeightMatrix2to3[6][9] = -0.21064330800736;
   fWeightMatrix2to3[7][9] = 0.201654350455427;
   fWeightMatrix2to3[8][9] = -0.979120203563879;
   fWeightMatrix2to3[9][9] = 1.38932723745021;
   fWeightMatrix2to3[10][9] = 0.137671019765575;
   fWeightMatrix2to3[11][9] = -1.24549929501116;
   fWeightMatrix2to3[12][9] = -0.852852424093631;
   fWeightMatrix2to3[0][10] = 0.87610906171688;
   fWeightMatrix2to3[1][10] = 2.91416976770664;
   fWeightMatrix2to3[2][10] = 1.08549136855582;
   fWeightMatrix2to3[3][10] = -1.92988153625909;
   fWeightMatrix2to3[4][10] = -3.57205306349837;
   fWeightMatrix2to3[5][10] = 1.83023618443099;
   fWeightMatrix2to3[6][10] = 1.55251414806866;
   fWeightMatrix2to3[7][10] = -1.86815601718894;
   fWeightMatrix2to3[8][10] = 2.07460677826924;
   fWeightMatrix2to3[9][10] = -1.44587651427875;
   fWeightMatrix2to3[10][10] = 2.40420141894761;
   fWeightMatrix2to3[11][10] = 1.58840902972035;
   fWeightMatrix2to3[12][10] = -1.46771830562917;
   fWeightMatrix2to3[0][11] = -2.72164122179584;
   fWeightMatrix2to3[1][11] = 1.8025638680041;
   fWeightMatrix2to3[2][11] = 1.94698024401754;
   fWeightMatrix2to3[3][11] = 3.4245155701914;
   fWeightMatrix2to3[4][11] = 0.101723436015768;
   fWeightMatrix2to3[5][11] = -2.41117100395868;
   fWeightMatrix2to3[6][11] = -1.01834699154123;
   fWeightMatrix2to3[7][11] = 0.0816296663629373;
   fWeightMatrix2to3[8][11] = -0.460030996087333;
   fWeightMatrix2to3[9][11] = 1.30931125572564;
   fWeightMatrix2to3[10][11] = -2.18191735907681;
   fWeightMatrix2to3[11][11] = -0.00832403988005127;
   fWeightMatrix2to3[12][11] = -2.96815335583027;
   fWeightMatrix2to3[0][12] = -1.89878520880699;
   fWeightMatrix2to3[1][12] = -3.46316568732172;
   fWeightMatrix2to3[2][12] = 2.28385742315129;
   fWeightMatrix2to3[3][12] = -3.83209251416485;
   fWeightMatrix2to3[4][12] = 2.75990532804499;
   fWeightMatrix2to3[5][12] = -2.08357915844097;
   fWeightMatrix2to3[6][12] = -3.23579838761408;
   fWeightMatrix2to3[7][12] = 0.953292458065992;
   fWeightMatrix2to3[8][12] = 2.06770032942201;
   fWeightMatrix2to3[9][12] = 3.13910377371516;
   fWeightMatrix2to3[10][12] = 0.439453640992988;
   fWeightMatrix2to3[11][12] = -1.14481360342686;
   fWeightMatrix2to3[12][12] = 3.80253756620304;
   fWeightMatrix2to3[0][13] = -2.33822503229619;
   fWeightMatrix2to3[1][13] = -0.0465651718063982;
   fWeightMatrix2to3[2][13] = -0.307902215582279;
   fWeightMatrix2to3[3][13] = 1.2418761075649;
   fWeightMatrix2to3[4][13] = -0.532110008786611;
   fWeightMatrix2to3[5][13] = -0.196074953090209;
   fWeightMatrix2to3[6][13] = -0.805505980124768;
   fWeightMatrix2to3[7][13] = 0.0370196478089263;
   fWeightMatrix2to3[8][13] = -0.524617487325887;
   fWeightMatrix2to3[9][13] = -0.676089012761571;
   fWeightMatrix2to3[10][13] = -0.0358384177242219;
   fWeightMatrix2to3[11][13] = 0.388793068746031;
   fWeightMatrix2to3[12][13] = 1.37380181098474;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 1.49161321547406;
   fWeightMatrix3to4[1][0] = -3.12122233250574;
   fWeightMatrix3to4[2][0] = 0.448023441786475;
   fWeightMatrix3to4[3][0] = -3.46923572200728;
   fWeightMatrix3to4[4][0] = 0.172950958351176;
   fWeightMatrix3to4[5][0] = 0.445339798329417;
   fWeightMatrix3to4[6][0] = 1.78041772150086;
   fWeightMatrix3to4[7][0] = 1.82913103042123;
   fWeightMatrix3to4[8][0] = 1.53108226208313;
   fWeightMatrix3to4[9][0] = -1.96592349113106;
   fWeightMatrix3to4[10][0] = -1.90304162447135;
   fWeightMatrix3to4[11][0] = -2.28217370109181;
   fWeightMatrix3to4[12][0] = -0.577593632665865;
   fWeightMatrix3to4[0][1] = -1.6575518758276;
   fWeightMatrix3to4[1][1] = -0.0231463830687189;
   fWeightMatrix3to4[2][1] = -1.64301940924954;
   fWeightMatrix3to4[3][1] = -0.966299169307112;
   fWeightMatrix3to4[4][1] = -1.3746972036847;
   fWeightMatrix3to4[5][1] = -1.63823859950844;
   fWeightMatrix3to4[6][1] = -5.21513154204159;
   fWeightMatrix3to4[7][1] = 0.706586820285882;
   fWeightMatrix3to4[8][1] = -1.17792450729876;
   fWeightMatrix3to4[9][1] = -0.759608064833817;
   fWeightMatrix3to4[10][1] = -2.41298012071646;
   fWeightMatrix3to4[11][1] = 0.128706965861364;
   fWeightMatrix3to4[12][1] = -1.25514952921643;
   fWeightMatrix3to4[0][2] = -1.35697623819896;
   fWeightMatrix3to4[1][2] = -1.09928712606505;
   fWeightMatrix3to4[2][2] = 1.68731912385288;
   fWeightMatrix3to4[3][2] = 0.0447306055407677;
   fWeightMatrix3to4[4][2] = 0.342129117552628;
   fWeightMatrix3to4[5][2] = 1.00201227260431;
   fWeightMatrix3to4[6][2] = -1.95802809341971;
   fWeightMatrix3to4[7][2] = -0.0455146345371114;
   fWeightMatrix3to4[8][2] = 0.0608450994997896;
   fWeightMatrix3to4[9][2] = -1.96367581500053;
   fWeightMatrix3to4[10][2] = -1.75394968544002;
   fWeightMatrix3to4[11][2] = -3.43298661786822;
   fWeightMatrix3to4[12][2] = 1.06783465440231;
   fWeightMatrix3to4[0][3] = -2.79038809320075;
   fWeightMatrix3to4[1][3] = 2.81425359084035;
   fWeightMatrix3to4[2][3] = 1.56878365903662;
   fWeightMatrix3to4[3][3] = 3.18304257846615;
   fWeightMatrix3to4[4][3] = 1.24658198755065;
   fWeightMatrix3to4[5][3] = 1.37672033146889;
   fWeightMatrix3to4[6][3] = -1.02335619780298;
   fWeightMatrix3to4[7][3] = 0.629454931211433;
   fWeightMatrix3to4[8][3] = -2.33480680837432;
   fWeightMatrix3to4[9][3] = -1.02541197802916;
   fWeightMatrix3to4[10][3] = -0.515639913026564;
   fWeightMatrix3to4[11][3] = 1.34152763201528;
   fWeightMatrix3to4[12][3] = -0.141684561698051;
   fWeightMatrix3to4[0][4] = 0.323819588176956;
   fWeightMatrix3to4[1][4] = 1.30157691222093;
   fWeightMatrix3to4[2][4] = 1.28530136861225;
   fWeightMatrix3to4[3][4] = -1.55459260339455;
   fWeightMatrix3to4[4][4] = -0.449810309812601;
   fWeightMatrix3to4[5][4] = -1.43195825242095;
   fWeightMatrix3to4[6][4] = -0.740933096762131;
   fWeightMatrix3to4[7][4] = -2.78040313591839;
   fWeightMatrix3to4[8][4] = -0.719274762053245;
   fWeightMatrix3to4[9][4] = -0.16363331325663;
   fWeightMatrix3to4[10][4] = 4.60022957339354;
   fWeightMatrix3to4[11][4] = -2.45366663634336;
   fWeightMatrix3to4[12][4] = 0.018022575726464;
   fWeightMatrix3to4[0][5] = -2.45295336078694;
   fWeightMatrix3to4[1][5] = -0.416243242973701;
   fWeightMatrix3to4[2][5] = 1.19797114428431;
   fWeightMatrix3to4[3][5] = -2.56970954011724;
   fWeightMatrix3to4[4][5] = 0.60035933073962;
   fWeightMatrix3to4[5][5] = -4.05166082998594;
   fWeightMatrix3to4[6][5] = 0.723956348814802;
   fWeightMatrix3to4[7][5] = -1.59847504236081;
   fWeightMatrix3to4[8][5] = 0.491261793628254;
   fWeightMatrix3to4[9][5] = -1.68990419085671;
   fWeightMatrix3to4[10][5] = -3.06931679148398;
   fWeightMatrix3to4[11][5] = 3.17088282743499;
   fWeightMatrix3to4[12][5] = -2.33174500611661;
   fWeightMatrix3to4[0][6] = -2.85026837688934;
   fWeightMatrix3to4[1][6] = -1.51495130541463;
   fWeightMatrix3to4[2][6] = 0.301377257125576;
   fWeightMatrix3to4[3][6] = 1.00300303220741;
   fWeightMatrix3to4[4][6] = 0.827039163925935;
   fWeightMatrix3to4[5][6] = -2.48732075098991;
   fWeightMatrix3to4[6][6] = 1.813037911175;
   fWeightMatrix3to4[7][6] = 3.54583164341306;
   fWeightMatrix3to4[8][6] = -0.378051268969473;
   fWeightMatrix3to4[9][6] = -1.25378819536943;
   fWeightMatrix3to4[10][6] = -3.14334008757697;
   fWeightMatrix3to4[11][6] = -0.498894389050821;
   fWeightMatrix3to4[12][6] = -1.0821819786148;
   fWeightMatrix3to4[0][7] = 3.61630399570502;
   fWeightMatrix3to4[1][7] = -0.622116702437906;
   fWeightMatrix3to4[2][7] = -0.262353749110806;
   fWeightMatrix3to4[3][7] = -1.11483754280685;
   fWeightMatrix3to4[4][7] = 1.29622456341135;
   fWeightMatrix3to4[5][7] = 1.32667816890001;
   fWeightMatrix3to4[6][7] = 1.10726022296818;
   fWeightMatrix3to4[7][7] = -2.27234081251554;
   fWeightMatrix3to4[8][7] = -2.38728576688022;
   fWeightMatrix3to4[9][7] = 1.70853601616241;
   fWeightMatrix3to4[10][7] = 0.0534221389015041;
   fWeightMatrix3to4[11][7] = 3.03747491800494;
   fWeightMatrix3to4[12][7] = -0.586046510702746;
   fWeightMatrix3to4[0][8] = -0.104767906477196;
   fWeightMatrix3to4[1][8] = -1.68227640878938;
   fWeightMatrix3to4[2][8] = -1.82318400385744;
   fWeightMatrix3to4[3][8] = -0.278118420157476;
   fWeightMatrix3to4[4][8] = -2.05286252281336;
   fWeightMatrix3to4[5][8] = 0.0817622675738326;
   fWeightMatrix3to4[6][8] = -0.73517689737072;
   fWeightMatrix3to4[7][8] = -1.65171299163476;
   fWeightMatrix3to4[8][8] = 1.53027570652222;
   fWeightMatrix3to4[9][8] = -1.92320278755145;
   fWeightMatrix3to4[10][8] = -0.581780055638735;
   fWeightMatrix3to4[11][8] = 0.458842916669874;
   fWeightMatrix3to4[12][8] = -1.64975493529274;
   fWeightMatrix3to4[0][9] = 0.595598044488519;
   fWeightMatrix3to4[1][9] = 0.942728489871817;
   fWeightMatrix3to4[2][9] = -2.49853511339384;
   fWeightMatrix3to4[3][9] = 0.44095355978834;
   fWeightMatrix3to4[4][9] = -2.60383377161517;
   fWeightMatrix3to4[5][9] = 3.33207581857105;
   fWeightMatrix3to4[6][9] = -0.233785623023758;
   fWeightMatrix3to4[7][9] = -1.31452340192475;
   fWeightMatrix3to4[8][9] = -1.61670329882997;
   fWeightMatrix3to4[9][9] = -1.5386288776489;
   fWeightMatrix3to4[10][9] = 2.38203312599581;
   fWeightMatrix3to4[11][9] = -1.28697026453335;
   fWeightMatrix3to4[12][9] = 0.159979647090739;
   fWeightMatrix3to4[0][10] = 1.03868667523601;
   fWeightMatrix3to4[1][10] = -1.92977593785137;
   fWeightMatrix3to4[2][10] = -1.74837627781076;
   fWeightMatrix3to4[3][10] = -1.47757864217104;
   fWeightMatrix3to4[4][10] = -0.504598059024022;
   fWeightMatrix3to4[5][10] = 0.684967618777948;
   fWeightMatrix3to4[6][10] = -1.06992273229843;
   fWeightMatrix3to4[7][10] = -2.62338117396176;
   fWeightMatrix3to4[8][10] = 2.04749212362668;
   fWeightMatrix3to4[9][10] = 0.105127409270038;
   fWeightMatrix3to4[10][10] = -0.105480049926578;
   fWeightMatrix3to4[11][10] = 2.40511021726454;
   fWeightMatrix3to4[12][10] = 0.121310912618264;
   fWeightMatrix3to4[0][11] = -2.43364864497677;
   fWeightMatrix3to4[1][11] = -0.0222918431026559;
   fWeightMatrix3to4[2][11] = -1.97257542853547;
   fWeightMatrix3to4[3][11] = 1.66772166831011;
   fWeightMatrix3to4[4][11] = 1.60919978352214;
   fWeightMatrix3to4[5][11] = 1.68001276293424;
   fWeightMatrix3to4[6][11] = -0.303258079364394;
   fWeightMatrix3to4[7][11] = -2.61887381132049;
   fWeightMatrix3to4[8][11] = -1.03926083891546;
   fWeightMatrix3to4[9][11] = -0.733111632184307;
   fWeightMatrix3to4[10][11] = -0.616982437554081;
   fWeightMatrix3to4[11][11] = 2.43650017729723;
   fWeightMatrix3to4[12][11] = -2.02643790424355;
   fWeightMatrix3to4[0][12] = 1.54010336625012;
   fWeightMatrix3to4[1][12] = -1.3510914396833;
   fWeightMatrix3to4[2][12] = 0.019414695539452;
   fWeightMatrix3to4[3][12] = -2.25219542249475;
   fWeightMatrix3to4[4][12] = 0.605237359318254;
   fWeightMatrix3to4[5][12] = 2.01797598446285;
   fWeightMatrix3to4[6][12] = 1.9463223525565;
   fWeightMatrix3to4[7][12] = -4.28805416064538;
   fWeightMatrix3to4[8][12] = 1.25607954484294;
   fWeightMatrix3to4[9][12] = 0.56260934659198;
   fWeightMatrix3to4[10][12] = 3.28482076954536;
   fWeightMatrix3to4[11][12] = -1.22452287541947;
   fWeightMatrix3to4[12][12] = -2.02659590298692;
   fWeightMatrix3to4[0][13] = -2.23181979731694;
   fWeightMatrix3to4[1][13] = 0.0390171786509124;
   fWeightMatrix3to4[2][13] = -0.01872480364656;
   fWeightMatrix3to4[3][13] = 0.703056270058029;
   fWeightMatrix3to4[4][13] = -0.123330639886619;
   fWeightMatrix3to4[5][13] = 0.249604494586931;
   fWeightMatrix3to4[6][13] = -1.76030006026115;
   fWeightMatrix3to4[7][13] = 2.23051805540699;
   fWeightMatrix3to4[8][13] = -0.695064118874656;
   fWeightMatrix3to4[9][13] = -1.8101795861074;
   fWeightMatrix3to4[10][13] = 0.370310613169521;
   fWeightMatrix3to4[11][13] = -0.141748117162706;
   fWeightMatrix3to4[12][13] = 0.471226213426587;
   // weight matrix from layer 4 to 5
   fWeightMatrix4to5[0][0] = 2.26546557108247;
   fWeightMatrix4to5[0][1] = -0.985692149543614;
   fWeightMatrix4to5[0][2] = -1.1483956116012;
   fWeightMatrix4to5[0][3] = -1.51359674674882;
   fWeightMatrix4to5[0][4] = -1.1840084152697;
   fWeightMatrix4to5[0][5] = -3.12536202081209;
   fWeightMatrix4to5[0][6] = 2.59824063786469;
   fWeightMatrix4to5[0][7] = 4.67799375211355;
   fWeightMatrix4to5[0][8] = 1.7753249245494;
   fWeightMatrix4to5[0][9] = 1.16496201551137;
   fWeightMatrix4to5[0][10] = 4.08170843989872;
   fWeightMatrix4to5[0][11] = -4.45589876035495;
   fWeightMatrix4to5[0][12] = -1.01320801718986;
   fWeightMatrix4to5[0][13] = -1.64334627316446;
}

inline double ReadkMLP_pca_ce_200_4(n+2)_no_ev::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]-1; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = ActivationFnc(fWeights[4][o]);
   }
   // layer 4 to 5
   for (int o=0; o<fLayerSize[5]; o++) {
      for (int i=0; i<fLayerSize[4]; i++) {
         double inputVal = fWeightMatrix4to5[o][i] * fWeights[4][i];
         fWeights[5][o] += inputVal;
      }
      fWeights[5][o] = OutputActivationFnc(fWeights[5][o]);
   }

   return fWeights[5][0];
}

double ReadkMLP_pca_ce_200_4(n+2)_no_ev::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_pca_ce_200_4(n+2)_no_ev::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_pca_ce_200_4(n+2)_no_ev::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 6; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_pca_ce_200_4(n+2)_no_ev::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_4(n+2)_no_ev::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00045111172949;
   fMax_1[0][0] = 352.672485352;
   fMin_1[1][0] = 0.000129323248984;
   fMax_1[1][0] = 568.511230469;
   fMin_1[2][0] = 0.000129323248984;
   fMax_1[2][0] = 568.511230469;
   fMin_1[0][1] = 0.000169199935044;
   fMax_1[0][1] = 497.236206055;
   fMin_1[1][1] = 0.000320142251439;
   fMax_1[1][1] = 570.143310547;
   fMin_1[2][1] = 0.000169199935044;
   fMax_1[2][1] = 570.143310547;
   fMin_1[0][2] = -2721.10644531;
   fMax_1[0][2] = 117643.984375;
   fMin_1[1][2] = -12820.3613281;
   fMax_1[1][2] = 36578.3359375;
   fMin_1[2][2] = -12820.3613281;
   fMax_1[2][2] = 117643.984375;
   fMin_1[0][3] = -3268.71240234;
   fMax_1[0][3] = 233789.203125;
   fMin_1[1][3] = -30494.9765625;
   fMax_1[1][3] = 16147.5166016;
   fMin_1[2][3] = -30494.9765625;
   fMax_1[2][3] = 233789.203125;
   fMin_1[0][4] = -6064.61279297;
   fMax_1[0][4] = 742903.3125;
   fMin_1[1][4] = -35846.2929688;
   fMax_1[1][4] = 106605.34375;
   fMin_1[2][4] = -35846.2929688;
   fMax_1[2][4] = 742903.3125;
   fMin_1[0][5] = -965.758056641;
   fMax_1[0][5] = 5815.69433594;
   fMin_1[1][5] = -4408.59033203;
   fMax_1[1][5] = 4246.99316406;
   fMin_1[2][5] = -4408.59033203;
   fMax_1[2][5] = 5815.69433594;
   fMin_1[0][6] = -812.467773438;
   fMax_1[0][6] = 10528.8847656;
   fMin_1[1][6] = -4839.04052734;
   fMax_1[1][6] = 7084.95996094;
   fMin_1[2][6] = -4839.04052734;
   fMax_1[2][6] = 10528.8847656;
   fMin_1[0][7] = -2967.99316406;
   fMax_1[0][7] = 32938.125;
   fMin_1[1][7] = -21899.5410156;
   fMax_1[1][7] = 15671.0107422;
   fMin_1[2][7] = -21899.5410156;
   fMax_1[2][7] = 32938.125;
   fMin_1[0][8] = 0.088986992836;
   fMax_1[0][8] = 179.925033569;
   fMin_1[1][8] = 0.0706751123071;
   fMax_1[1][8] = 179.984664917;
   fMin_1[2][8] = 0.0706751123071;
   fMax_1[2][8] = 179.984664917;
   fMin_1[0][9] = 0.00990104675293;
   fMax_1[0][9] = 3667.81396484;
   fMin_1[1][9] = 0.0195769127458;
   fMax_1[1][9] = 3115.00610352;
   fMin_1[2][9] = 0.00990104675293;
   fMax_1[2][9] = 3667.81396484;
   fMin_1[0][10] = 0.345140367746;
   fMax_1[0][10] = 752596.375;
   fMin_1[1][10] = 0.052237238735;
   fMax_1[1][10] = 115775.875;
   fMin_1[2][10] = 0.052237238735;
   fMax_1[2][10] = 752596.375;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_4(n+2)_no_ev::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_4(n+2)_no_ev::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_200_4(n+2)_no_ev::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
