###############################################################################
#
#  The global Makefile to build all Hydra modules from scratch.
#
#  Examples and explanations can be found in the file README
#
###############################################################################

MODULES ?=	wall

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.rules.mk

