// Class: ReadkMLP_pca_ce_600_4(n+2)_no_ev
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_pca_ce_600_4(n+2)_no_ev
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Mon Aug 12 15:38:14 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/nyx/hades/user/knowakow/PP/FAT/TMVA
Training events: 400568
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+2,N+2,N+2,N+2" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N,P" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [4.45244913863e-05,591.79876709]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [2.60141878243e-05,680.619262695]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-27109.4433594,117643.984375]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-30494.9765625,336199.4375]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-848390.4375,742903.3125]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-4408.59033203,5815.69433594]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-10921.9150391,10528.8847656]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-36484.0898438,32938.125]
oa_lambda                     oa_lambda                     oa_lambda                     oa_lambda                     deg                               'F'    [0.0153690213338,179.980255127]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.0131534170359,76398.515625]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.0941462889314,914557.375]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_pca_ce_600_4(n+2)_no_ev : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_pca_ce_600_4(n+2)_no_ev( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_pca_ce_600_4(n+2)_no_ev" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "oa_lambda", "dist_lambda_ver_pip_pim", "dist_ver_to_ver" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.970137178897858;
      fVmax[0] = 1.03263676166534;
      fVmin[1] = -0.0487020127475262;
      fVmax[1] = 1.89828264713287;
      fVmin[2] = -1.87950766086578;
      fVmax[2] = 0.487048923969269;
      fVmin[3] = -0.791524469852448;
      fVmax[3] = 2.47808957099915;
      fVmin[4] = -0.526382446289062;
      fVmax[4] = 2.18375658988953;
      fVmin[5] = -1.46485781669617;
      fVmax[5] = 0.606749951839447;
      fVmin[6] = -2.02398252487183;
      fVmax[6] = 0.181860625743866;
      fVmin[7] = -0.336992591619492;
      fVmax[7] = 0.529070675373077;
      fVmin[8] = -0.720848262310028;
      fVmax[8] = 0.691642463207245;
      fVmin[9] = -0.485793143510818;
      fVmax[9] = 0.339316040277481;
      fVmin[10] = -0.179725304245949;
      fVmax[10] = 0.0395826622843742;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_pca_ce_600_4(n+2)_no_ev() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];

   void X2P_2( const double*, double*, int ) const;
   double fMeanValues_2[3][11];
   double fEigenVectors_2[3][11][11];

   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[6];
   double fWeightMatrix0to1[14][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][14];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[14][14];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[14][14];   // weight matrix from layer 3 to 4
   double fWeightMatrix4to5[1][14];   // weight matrix from layer 4 to 5

   double * fWeights[6];
};

inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::Initialize()
{
   // build network structure
   fLayers = 6;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 14; fWeights[3] = new double[14]; 
   fLayerSize[4] = 14; fWeights[4] = new double[14]; 
   fLayerSize[5] = 1; fWeights[5] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.970667759178328;
   fWeightMatrix0to1[1][0] = 1.80507571494719;
   fWeightMatrix0to1[2][0] = 0.753225807039102;
   fWeightMatrix0to1[3][0] = 2.90911161915678;
   fWeightMatrix0to1[4][0] = -1.26873149800124;
   fWeightMatrix0to1[5][0] = -0.739115277105199;
   fWeightMatrix0to1[6][0] = -1.81051303005803;
   fWeightMatrix0to1[7][0] = 3.65133223673251;
   fWeightMatrix0to1[8][0] = -1.39313659868324;
   fWeightMatrix0to1[9][0] = -1.69909696505095;
   fWeightMatrix0to1[10][0] = -2.5922052786312;
   fWeightMatrix0to1[11][0] = -0.530685375815563;
   fWeightMatrix0to1[12][0] = 0.0736196269778422;
   fWeightMatrix0to1[0][1] = -1.80712954724283;
   fWeightMatrix0to1[1][1] = -0.247281952562221;
   fWeightMatrix0to1[2][1] = -0.724987874284978;
   fWeightMatrix0to1[3][1] = -0.765513363772195;
   fWeightMatrix0to1[4][1] = 6.39512785308523;
   fWeightMatrix0to1[5][1] = -5.4417016509382;
   fWeightMatrix0to1[6][1] = 0.96743886758395;
   fWeightMatrix0to1[7][1] = 1.63694598796603;
   fWeightMatrix0to1[8][1] = -1.71779042373505;
   fWeightMatrix0to1[9][1] = 3.04619791059443;
   fWeightMatrix0to1[10][1] = 0.636039069805966;
   fWeightMatrix0to1[11][1] = -8.3534049808601;
   fWeightMatrix0to1[12][1] = 6.49542239126498;
   fWeightMatrix0to1[0][2] = 1.79963249763771;
   fWeightMatrix0to1[1][2] = -0.607448206173862;
   fWeightMatrix0to1[2][2] = -1.08165773200275;
   fWeightMatrix0to1[3][2] = 0.576314669551538;
   fWeightMatrix0to1[4][2] = 0.178264918601201;
   fWeightMatrix0to1[5][2] = 2.66754152621392;
   fWeightMatrix0to1[6][2] = 0.225579307540433;
   fWeightMatrix0to1[7][2] = 0.711623997781345;
   fWeightMatrix0to1[8][2] = 0.307719456571079;
   fWeightMatrix0to1[9][2] = -0.580421516734667;
   fWeightMatrix0to1[10][2] = -2.04866391914719;
   fWeightMatrix0to1[11][2] = 2.69352639093423;
   fWeightMatrix0to1[12][2] = -2.15619398088237;
   fWeightMatrix0to1[0][3] = 1.05597295246926;
   fWeightMatrix0to1[1][3] = 1.22438056277122;
   fWeightMatrix0to1[2][3] = 0.70804242190122;
   fWeightMatrix0to1[3][3] = 1.7853635418017;
   fWeightMatrix0to1[4][3] = 1.45238534092837;
   fWeightMatrix0to1[5][3] = -1.00198809145829;
   fWeightMatrix0to1[6][3] = -1.60921149687718;
   fWeightMatrix0to1[7][3] = 0.80182155946811;
   fWeightMatrix0to1[8][3] = 0.0547653447436251;
   fWeightMatrix0to1[9][3] = 1.5447848711681;
   fWeightMatrix0to1[10][3] = 1.54296889894138;
   fWeightMatrix0to1[11][3] = 1.24687373358014;
   fWeightMatrix0to1[12][3] = 1.58173882509943;
   fWeightMatrix0to1[0][4] = -1.81680067334478;
   fWeightMatrix0to1[1][4] = 1.33610174078487;
   fWeightMatrix0to1[2][4] = -2.07394222543336;
   fWeightMatrix0to1[3][4] = -1.04649401214841;
   fWeightMatrix0to1[4][4] = -0.827965917178909;
   fWeightMatrix0to1[5][4] = -2.35525631339976;
   fWeightMatrix0to1[6][4] = 1.48724341259624;
   fWeightMatrix0to1[7][4] = 0.699878177541551;
   fWeightMatrix0to1[8][4] = -1.71270323054275;
   fWeightMatrix0to1[9][4] = 0.515063710478921;
   fWeightMatrix0to1[10][4] = -0.238105455905363;
   fWeightMatrix0to1[11][4] = -0.0487199074778387;
   fWeightMatrix0to1[12][4] = 2.43110525274537;
   fWeightMatrix0to1[0][5] = -0.611385702170483;
   fWeightMatrix0to1[1][5] = 0.180921713406865;
   fWeightMatrix0to1[2][5] = -1.54559506051982;
   fWeightMatrix0to1[3][5] = 0.579925334288543;
   fWeightMatrix0to1[4][5] = -0.142691886914807;
   fWeightMatrix0to1[5][5] = -1.68097659030266;
   fWeightMatrix0to1[6][5] = -1.44080734864351;
   fWeightMatrix0to1[7][5] = 0.748878983307313;
   fWeightMatrix0to1[8][5] = 1.00954653270718;
   fWeightMatrix0to1[9][5] = 1.57210129762848;
   fWeightMatrix0to1[10][5] = -0.152508105773396;
   fWeightMatrix0to1[11][5] = -3.05888698808189;
   fWeightMatrix0to1[12][5] = -0.925494769392919;
   fWeightMatrix0to1[0][6] = 1.1774701095628;
   fWeightMatrix0to1[1][6] = 0.52736156618962;
   fWeightMatrix0to1[2][6] = 2.07195698746772;
   fWeightMatrix0to1[3][6] = 0.686662125755461;
   fWeightMatrix0to1[4][6] = 0.499517584127581;
   fWeightMatrix0to1[5][6] = -0.295379805373286;
   fWeightMatrix0to1[6][6] = -0.858132972242556;
   fWeightMatrix0to1[7][6] = -0.255425396389743;
   fWeightMatrix0to1[8][6] = 1.31868946087563;
   fWeightMatrix0to1[9][6] = -1.33211691346178;
   fWeightMatrix0to1[10][6] = -1.59619169107493;
   fWeightMatrix0to1[11][6] = -0.993537406811585;
   fWeightMatrix0to1[12][6] = -0.807004399831585;
   fWeightMatrix0to1[0][7] = -0.46623326672927;
   fWeightMatrix0to1[1][7] = 1.66935185492206;
   fWeightMatrix0to1[2][7] = -1.95812190565444;
   fWeightMatrix0to1[3][7] = -0.991437786815914;
   fWeightMatrix0to1[4][7] = 2.50012969679292;
   fWeightMatrix0to1[5][7] = -1.9946318071387;
   fWeightMatrix0to1[6][7] = -1.55685992244886;
   fWeightMatrix0to1[7][7] = -1.40978345303554;
   fWeightMatrix0to1[8][7] = -0.126563175001382;
   fWeightMatrix0to1[9][7] = -1.59271831613667;
   fWeightMatrix0to1[10][7] = -1.58700275261649;
   fWeightMatrix0to1[11][7] = -0.70346371110211;
   fWeightMatrix0to1[12][7] = 2.85624053467803;
   fWeightMatrix0to1[0][8] = -1.00135734722192;
   fWeightMatrix0to1[1][8] = 1.61088343665876;
   fWeightMatrix0to1[2][8] = -0.711472383219651;
   fWeightMatrix0to1[3][8] = -0.675342651996513;
   fWeightMatrix0to1[4][8] = -0.517357349265001;
   fWeightMatrix0to1[5][8] = 0.924937692572275;
   fWeightMatrix0to1[6][8] = -1.77235788602063;
   fWeightMatrix0to1[7][8] = 0.210606874882492;
   fWeightMatrix0to1[8][8] = 0.385400306192672;
   fWeightMatrix0to1[9][8] = 0.319145456415197;
   fWeightMatrix0to1[10][8] = -1.5200231415071;
   fWeightMatrix0to1[11][8] = 2.55534192218282;
   fWeightMatrix0to1[12][8] = -0.245187613224503;
   fWeightMatrix0to1[0][9] = -0.922941021805611;
   fWeightMatrix0to1[1][9] = 0.805178197095278;
   fWeightMatrix0to1[2][9] = -1.04438392967908;
   fWeightMatrix0to1[3][9] = -1.57501175743332;
   fWeightMatrix0to1[4][9] = 0.0753948619854601;
   fWeightMatrix0to1[5][9] = -0.252638515686167;
   fWeightMatrix0to1[6][9] = 1.79310608445466;
   fWeightMatrix0to1[7][9] = 0.829102970159978;
   fWeightMatrix0to1[8][9] = -0.0124113040572898;
   fWeightMatrix0to1[9][9] = -0.370492454950179;
   fWeightMatrix0to1[10][9] = 0.15998297817275;
   fWeightMatrix0to1[11][9] = -1.70637663349649;
   fWeightMatrix0to1[12][9] = 0.988605722243339;
   fWeightMatrix0to1[0][10] = 0.163451620790144;
   fWeightMatrix0to1[1][10] = -1.82776890776577;
   fWeightMatrix0to1[2][10] = 0.6861469522828;
   fWeightMatrix0to1[3][10] = -1.42641495744179;
   fWeightMatrix0to1[4][10] = -0.0230178105359871;
   fWeightMatrix0to1[5][10] = 1.25924786171586;
   fWeightMatrix0to1[6][10] = 1.78407763119239;
   fWeightMatrix0to1[7][10] = -1.9338862609667;
   fWeightMatrix0to1[8][10] = 0.362163886174876;
   fWeightMatrix0to1[9][10] = 1.50920738478612;
   fWeightMatrix0to1[10][10] = 1.59876711551399;
   fWeightMatrix0to1[11][10] = 0.285156228816602;
   fWeightMatrix0to1[12][10] = -1.56081719025601;
   fWeightMatrix0to1[0][11] = -0.651516679308542;
   fWeightMatrix0to1[1][11] = -1.84944156677891;
   fWeightMatrix0to1[2][11] = 0.851107806380004;
   fWeightMatrix0to1[3][11] = 0.601840607568549;
   fWeightMatrix0to1[4][11] = 0.62963800399637;
   fWeightMatrix0to1[5][11] = -0.859040882780909;
   fWeightMatrix0to1[6][11] = -0.890192497932546;
   fWeightMatrix0to1[7][11] = -3.77561151832259;
   fWeightMatrix0to1[8][11] = -0.26337004494524;
   fWeightMatrix0to1[9][11] = 0.306268208140826;
   fWeightMatrix0to1[10][11] = -1.5497911757848;
   fWeightMatrix0to1[11][11] = -0.712169318347102;
   fWeightMatrix0to1[12][11] = 0.0198236259908791;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.0073347110754;
   fWeightMatrix1to2[1][0] = -0.206443159118388;
   fWeightMatrix1to2[2][0] = 0.878679898388893;
   fWeightMatrix1to2[3][0] = -1.92444248327008;
   fWeightMatrix1to2[4][0] = 1.21756168014681;
   fWeightMatrix1to2[5][0] = 1.59457971485908;
   fWeightMatrix1to2[6][0] = 0.202628762704117;
   fWeightMatrix1to2[7][0] = -0.356478204515983;
   fWeightMatrix1to2[8][0] = 0.98104756486321;
   fWeightMatrix1to2[9][0] = -0.130586794014974;
   fWeightMatrix1to2[10][0] = -1.27769579162742;
   fWeightMatrix1to2[11][0] = 1.92319533840936;
   fWeightMatrix1to2[12][0] = -0.900589284997414;
   fWeightMatrix1to2[0][1] = -0.543797068170516;
   fWeightMatrix1to2[1][1] = 1.98824006262831;
   fWeightMatrix1to2[2][1] = 0.969237533378022;
   fWeightMatrix1to2[3][1] = -0.383054208940907;
   fWeightMatrix1to2[4][1] = 1.32842718027641;
   fWeightMatrix1to2[5][1] = 2.01570027721704;
   fWeightMatrix1to2[6][1] = -1.97906713573629;
   fWeightMatrix1to2[7][1] = 0.70609084755587;
   fWeightMatrix1to2[8][1] = -0.00437326110286525;
   fWeightMatrix1to2[9][1] = 0.628948309141407;
   fWeightMatrix1to2[10][1] = -2.00736553940075;
   fWeightMatrix1to2[11][1] = -1.20436991784056;
   fWeightMatrix1to2[12][1] = 1.19653099753634;
   fWeightMatrix1to2[0][2] = 1.7557692050696;
   fWeightMatrix1to2[1][2] = -1.5517453488974;
   fWeightMatrix1to2[2][2] = -0.255694679508;
   fWeightMatrix1to2[3][2] = -0.695753951331634;
   fWeightMatrix1to2[4][2] = 0.39114302289766;
   fWeightMatrix1to2[5][2] = 1.79184263316052;
   fWeightMatrix1to2[6][2] = -0.701443803083911;
   fWeightMatrix1to2[7][2] = -0.282872289691653;
   fWeightMatrix1to2[8][2] = -1.10855864013433;
   fWeightMatrix1to2[9][2] = 1.75474192489845;
   fWeightMatrix1to2[10][2] = 0.998730195967918;
   fWeightMatrix1to2[11][2] = 1.05310038798285;
   fWeightMatrix1to2[12][2] = 0.264456052978626;
   fWeightMatrix1to2[0][3] = -0.813027584972007;
   fWeightMatrix1to2[1][3] = -2.13209253654938;
   fWeightMatrix1to2[2][3] = 1.02296187532922;
   fWeightMatrix1to2[3][3] = 0.30230664815434;
   fWeightMatrix1to2[4][3] = -1.19544066539677;
   fWeightMatrix1to2[5][3] = -0.576539976602806;
   fWeightMatrix1to2[6][3] = -0.407827268074593;
   fWeightMatrix1to2[7][3] = -0.0419595470850074;
   fWeightMatrix1to2[8][3] = -1.97406856701026;
   fWeightMatrix1to2[9][3] = 2.88748656790412;
   fWeightMatrix1to2[10][3] = 0.786360063013707;
   fWeightMatrix1to2[11][3] = -0.562049741940273;
   fWeightMatrix1to2[12][3] = -0.155286141822043;
   fWeightMatrix1to2[0][4] = 1.63021010161169;
   fWeightMatrix1to2[1][4] = 1.20869353386467;
   fWeightMatrix1to2[2][4] = 0.502411452751544;
   fWeightMatrix1to2[3][4] = -0.0188471766701011;
   fWeightMatrix1to2[4][4] = -1.1128346619513;
   fWeightMatrix1to2[5][4] = -1.82551296411247;
   fWeightMatrix1to2[6][4] = 2.33855389753687;
   fWeightMatrix1to2[7][4] = 2.81423873165665;
   fWeightMatrix1to2[8][4] = 0.672032313462812;
   fWeightMatrix1to2[9][4] = -0.550600604190349;
   fWeightMatrix1to2[10][4] = 2.06919322447289;
   fWeightMatrix1to2[11][4] = -3.16460062566483;
   fWeightMatrix1to2[12][4] = -1.58598963277345;
   fWeightMatrix1to2[0][5] = -0.125661153102802;
   fWeightMatrix1to2[1][5] = -2.45243243948462;
   fWeightMatrix1to2[2][5] = 0.904719219843736;
   fWeightMatrix1to2[3][5] = 1.17781156295315;
   fWeightMatrix1to2[4][5] = -1.71616318267632;
   fWeightMatrix1to2[5][5] = 2.09187164377498;
   fWeightMatrix1to2[6][5] = -0.667153136446636;
   fWeightMatrix1to2[7][5] = -3.22812153280794;
   fWeightMatrix1to2[8][5] = -1.0786116789567;
   fWeightMatrix1to2[9][5] = 1.68047940065705;
   fWeightMatrix1to2[10][5] = -0.628210463608313;
   fWeightMatrix1to2[11][5] = 2.50978364241342;
   fWeightMatrix1to2[12][5] = -1.09174036502479;
   fWeightMatrix1to2[0][6] = 1.65544186322291;
   fWeightMatrix1to2[1][6] = -1.76275836660203;
   fWeightMatrix1to2[2][6] = 0.869964918008381;
   fWeightMatrix1to2[3][6] = 0.0354688957558575;
   fWeightMatrix1to2[4][6] = -1.42865147105386;
   fWeightMatrix1to2[5][6] = -1.44474747284394;
   fWeightMatrix1to2[6][6] = -1.5709358345465;
   fWeightMatrix1to2[7][6] = 0.125904347350029;
   fWeightMatrix1to2[8][6] = -1.97051672357881;
   fWeightMatrix1to2[9][6] = -2.1360505664603;
   fWeightMatrix1to2[10][6] = -2.30208691603604;
   fWeightMatrix1to2[11][6] = -0.250248708694941;
   fWeightMatrix1to2[12][6] = -1.15202747206593;
   fWeightMatrix1to2[0][7] = -1.4391479061883;
   fWeightMatrix1to2[1][7] = 2.48747054283405;
   fWeightMatrix1to2[2][7] = -0.839718107317962;
   fWeightMatrix1to2[3][7] = 0.0398503609021775;
   fWeightMatrix1to2[4][7] = -1.63066425298326;
   fWeightMatrix1to2[5][7] = 0.557205546049429;
   fWeightMatrix1to2[6][7] = 2.45270512116881;
   fWeightMatrix1to2[7][7] = 1.74268023241299;
   fWeightMatrix1to2[8][7] = -0.886855341211991;
   fWeightMatrix1to2[9][7] = -1.57841324333668;
   fWeightMatrix1to2[10][7] = -2.03390578544229;
   fWeightMatrix1to2[11][7] = -0.407206599698619;
   fWeightMatrix1to2[12][7] = -1.56315753805526;
   fWeightMatrix1to2[0][8] = 0.295911919270259;
   fWeightMatrix1to2[1][8] = -0.210608523110115;
   fWeightMatrix1to2[2][8] = 1.85849335910331;
   fWeightMatrix1to2[3][8] = -0.690245417170592;
   fWeightMatrix1to2[4][8] = -0.122712415070941;
   fWeightMatrix1to2[5][8] = 0.115339945963899;
   fWeightMatrix1to2[6][8] = -2.15756494925735;
   fWeightMatrix1to2[7][8] = 0.572734514141575;
   fWeightMatrix1to2[8][8] = 1.14700194208302;
   fWeightMatrix1to2[9][8] = -0.423383382270666;
   fWeightMatrix1to2[10][8] = -2.06893191432077;
   fWeightMatrix1to2[11][8] = 1.50503855206614;
   fWeightMatrix1to2[12][8] = 1.25533228795304;
   fWeightMatrix1to2[0][9] = 0.379967930068128;
   fWeightMatrix1to2[1][9] = -0.576177228602647;
   fWeightMatrix1to2[2][9] = -0.309770101463079;
   fWeightMatrix1to2[3][9] = 1.33305809631235;
   fWeightMatrix1to2[4][9] = 1.52987480883651;
   fWeightMatrix1to2[5][9] = 0.56112665167668;
   fWeightMatrix1to2[6][9] = -0.096750407972079;
   fWeightMatrix1to2[7][9] = 0.944242315669564;
   fWeightMatrix1to2[8][9] = -0.373417140224254;
   fWeightMatrix1to2[9][9] = -1.87972106393764;
   fWeightMatrix1to2[10][9] = -0.599870802462275;
   fWeightMatrix1to2[11][9] = -2.49438322406918;
   fWeightMatrix1to2[12][9] = -1.58106330238246;
   fWeightMatrix1to2[0][10] = -1.58509035563977;
   fWeightMatrix1to2[1][10] = 2.0615870199327;
   fWeightMatrix1to2[2][10] = -1.83166640667964;
   fWeightMatrix1to2[3][10] = 1.53340612232093;
   fWeightMatrix1to2[4][10] = -1.98931090786218;
   fWeightMatrix1to2[5][10] = 1.19306077488328;
   fWeightMatrix1to2[6][10] = -0.640298696557857;
   fWeightMatrix1to2[7][10] = 0.654080427018382;
   fWeightMatrix1to2[8][10] = 0.774655586225798;
   fWeightMatrix1to2[9][10] = -2.54476167104141;
   fWeightMatrix1to2[10][10] = -0.636783861830923;
   fWeightMatrix1to2[11][10] = 0.703611477306964;
   fWeightMatrix1to2[12][10] = -2.03818816741584;
   fWeightMatrix1to2[0][11] = -1.50692688247535;
   fWeightMatrix1to2[1][11] = -3.17517126210408;
   fWeightMatrix1to2[2][11] = -0.919368123474882;
   fWeightMatrix1to2[3][11] = 1.04635838794232;
   fWeightMatrix1to2[4][11] = -1.54611046080391;
   fWeightMatrix1to2[5][11] = 2.1579530370525;
   fWeightMatrix1to2[6][11] = -1.80996971930396;
   fWeightMatrix1to2[7][11] = -3.65260701672688;
   fWeightMatrix1to2[8][11] = -1.68966341200552;
   fWeightMatrix1to2[9][11] = 0.224380536974482;
   fWeightMatrix1to2[10][11] = -2.45577044697658;
   fWeightMatrix1to2[11][11] = 3.22217526307829;
   fWeightMatrix1to2[12][11] = -1.16081455128152;
   fWeightMatrix1to2[0][12] = -1.24306868128584;
   fWeightMatrix1to2[1][12] = 1.98356078900268;
   fWeightMatrix1to2[2][12] = 0.317135986783684;
   fWeightMatrix1to2[3][12] = -0.409021839271515;
   fWeightMatrix1to2[4][12] = 2.29036899048518;
   fWeightMatrix1to2[5][12] = -2.71314191739648;
   fWeightMatrix1to2[6][12] = 1.6470815530778;
   fWeightMatrix1to2[7][12] = 2.27681430555683;
   fWeightMatrix1to2[8][12] = -1.12672823672864;
   fWeightMatrix1to2[9][12] = -0.967643613262502;
   fWeightMatrix1to2[10][12] = -0.210268549048975;
   fWeightMatrix1to2[11][12] = -2.56036637702576;
   fWeightMatrix1to2[12][12] = 0.26414952523122;
   fWeightMatrix1to2[0][13] = 1.88186879810743;
   fWeightMatrix1to2[1][13] = 1.07150909575146;
   fWeightMatrix1to2[2][13] = 1.5250735828602;
   fWeightMatrix1to2[3][13] = -1.67095206934953;
   fWeightMatrix1to2[4][13] = 1.0256765938672;
   fWeightMatrix1to2[5][13] = -1.75123425070015;
   fWeightMatrix1to2[6][13] = 0.36790826660007;
   fWeightMatrix1to2[7][13] = -1.66686453250055;
   fWeightMatrix1to2[8][13] = -1.92643655900281;
   fWeightMatrix1to2[9][13] = 0.562093101379796;
   fWeightMatrix1to2[10][13] = 0.321537830652146;
   fWeightMatrix1to2[11][13] = 0.441948392666328;
   fWeightMatrix1to2[12][13] = 0.961164860563131;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.419282833343967;
   fWeightMatrix2to3[1][0] = 0.0675338120742744;
   fWeightMatrix2to3[2][0] = -0.752743380788511;
   fWeightMatrix2to3[3][0] = -0.309988639284236;
   fWeightMatrix2to3[4][0] = 2.32583277852466;
   fWeightMatrix2to3[5][0] = -1.30004362029356;
   fWeightMatrix2to3[6][0] = -0.0211462381306461;
   fWeightMatrix2to3[7][0] = -1.87943091190656;
   fWeightMatrix2to3[8][0] = -0.021670693984139;
   fWeightMatrix2to3[9][0] = 0.297472659469393;
   fWeightMatrix2to3[10][0] = 0.230475667868026;
   fWeightMatrix2to3[11][0] = -0.603299126841501;
   fWeightMatrix2to3[12][0] = 1.0295746197084;
   fWeightMatrix2to3[0][1] = 2.8227804128041;
   fWeightMatrix2to3[1][1] = 0.783438443952983;
   fWeightMatrix2to3[2][1] = -0.16613660550855;
   fWeightMatrix2to3[3][1] = -2.12161468680756;
   fWeightMatrix2to3[4][1] = -1.53753498793098;
   fWeightMatrix2to3[5][1] = -1.59381331837132;
   fWeightMatrix2to3[6][1] = 1.54848733856333;
   fWeightMatrix2to3[7][1] = -0.694196230416632;
   fWeightMatrix2to3[8][1] = -0.977655410230437;
   fWeightMatrix2to3[9][1] = 0.369991385517503;
   fWeightMatrix2to3[10][1] = -1.81189322371903;
   fWeightMatrix2to3[11][1] = -1.38352845472991;
   fWeightMatrix2to3[12][1] = -1.51053744227793;
   fWeightMatrix2to3[0][2] = 0.97068152753719;
   fWeightMatrix2to3[1][2] = -1.10963858481605;
   fWeightMatrix2to3[2][2] = -1.75519610494923;
   fWeightMatrix2to3[3][2] = -0.823141402230139;
   fWeightMatrix2to3[4][2] = -0.639830599918306;
   fWeightMatrix2to3[5][2] = -1.45766922699836;
   fWeightMatrix2to3[6][2] = 0.740882941880648;
   fWeightMatrix2to3[7][2] = -1.89986620884653;
   fWeightMatrix2to3[8][2] = -0.816353584387087;
   fWeightMatrix2to3[9][2] = 2.0005653447727;
   fWeightMatrix2to3[10][2] = 0.379192815463241;
   fWeightMatrix2to3[11][2] = 0.685343030183579;
   fWeightMatrix2to3[12][2] = 0.101955433978123;
   fWeightMatrix2to3[0][3] = 0.573003578143097;
   fWeightMatrix2to3[1][3] = 1.80028011382684;
   fWeightMatrix2to3[2][3] = 0.470577213933147;
   fWeightMatrix2to3[3][3] = -0.286764993872465;
   fWeightMatrix2to3[4][3] = -0.192836615850378;
   fWeightMatrix2to3[5][3] = -1.72919330729757;
   fWeightMatrix2to3[6][3] = 0.213970820381179;
   fWeightMatrix2to3[7][3] = 0.709836917171172;
   fWeightMatrix2to3[8][3] = 0.13997115807492;
   fWeightMatrix2to3[9][3] = 1.41630222507431;
   fWeightMatrix2to3[10][3] = 0.545329063144093;
   fWeightMatrix2to3[11][3] = 1.49384213347472;
   fWeightMatrix2to3[12][3] = -1.46118866911457;
   fWeightMatrix2to3[0][4] = 1.68181340842001;
   fWeightMatrix2to3[1][4] = 0.863220329065709;
   fWeightMatrix2to3[2][4] = -1.94495578351901;
   fWeightMatrix2to3[3][4] = -0.212769247854177;
   fWeightMatrix2to3[4][4] = -1.04704867797638;
   fWeightMatrix2to3[5][4] = 1.12841712010267;
   fWeightMatrix2to3[6][4] = 0.203641094696548;
   fWeightMatrix2to3[7][4] = 0.805265915245102;
   fWeightMatrix2to3[8][4] = 2.10215888871884;
   fWeightMatrix2to3[9][4] = -0.392371918442169;
   fWeightMatrix2to3[10][4] = 2.00721157835893;
   fWeightMatrix2to3[11][4] = 2.37671657924145;
   fWeightMatrix2to3[12][4] = 0.231853564047727;
   fWeightMatrix2to3[0][5] = -1.80517479128812;
   fWeightMatrix2to3[1][5] = 1.76366929264391;
   fWeightMatrix2to3[2][5] = -1.9718862168938;
   fWeightMatrix2to3[3][5] = 0.906640977428626;
   fWeightMatrix2to3[4][5] = 1.76599709333082;
   fWeightMatrix2to3[5][5] = -0.651321752802054;
   fWeightMatrix2to3[6][5] = -1.47803907994536;
   fWeightMatrix2to3[7][5] = -0.314698654660502;
   fWeightMatrix2to3[8][5] = -1.28099997629893;
   fWeightMatrix2to3[9][5] = 0.57034130678597;
   fWeightMatrix2to3[10][5] = -2.52602541276815;
   fWeightMatrix2to3[11][5] = -0.136655807033841;
   fWeightMatrix2to3[12][5] = -0.310595495864731;
   fWeightMatrix2to3[0][6] = 2.18079080278704;
   fWeightMatrix2to3[1][6] = 1.27805109486285;
   fWeightMatrix2to3[2][6] = 1.67179537123757;
   fWeightMatrix2to3[3][6] = -1.06522628557294;
   fWeightMatrix2to3[4][6] = -0.525370195335572;
   fWeightMatrix2to3[5][6] = 0.727630432298942;
   fWeightMatrix2to3[6][6] = 2.08135391046068;
   fWeightMatrix2to3[7][6] = -1.94821508620858;
   fWeightMatrix2to3[8][6] = -1.19260806179451;
   fWeightMatrix2to3[9][6] = -0.804684270395289;
   fWeightMatrix2to3[10][6] = -1.27964164894678;
   fWeightMatrix2to3[11][6] = -1.34051452121514;
   fWeightMatrix2to3[12][6] = -1.3839622210351;
   fWeightMatrix2to3[0][7] = 1.95176178131177;
   fWeightMatrix2to3[1][7] = 0.160225775590549;
   fWeightMatrix2to3[2][7] = -1.96289970096406;
   fWeightMatrix2to3[3][7] = -3.02445603516354;
   fWeightMatrix2to3[4][7] = -0.0315258722419416;
   fWeightMatrix2to3[5][7] = 2.00067716438272;
   fWeightMatrix2to3[6][7] = 2.29537887140318;
   fWeightMatrix2to3[7][7] = 1.09795587044711;
   fWeightMatrix2to3[8][7] = -0.400038648763147;
   fWeightMatrix2to3[9][7] = -1.86746416924271;
   fWeightMatrix2to3[10][7] = 0.110104948528;
   fWeightMatrix2to3[11][7] = -1.06727137022564;
   fWeightMatrix2to3[12][7] = -1.4312082709957;
   fWeightMatrix2to3[0][8] = -0.653748532155086;
   fWeightMatrix2to3[1][8] = 0.0158313555236681;
   fWeightMatrix2to3[2][8] = -1.47635228139336;
   fWeightMatrix2to3[3][8] = 1.52905113899877;
   fWeightMatrix2to3[4][8] = 1.24540794675486;
   fWeightMatrix2to3[5][8] = 0.11414100995853;
   fWeightMatrix2to3[6][8] = -0.616365917023124;
   fWeightMatrix2to3[7][8] = -0.878579096041156;
   fWeightMatrix2to3[8][8] = 1.7609477412516;
   fWeightMatrix2to3[9][8] = -0.567584023986292;
   fWeightMatrix2to3[10][8] = 0.302858029794853;
   fWeightMatrix2to3[11][8] = 1.55379947691727;
   fWeightMatrix2to3[12][8] = 1.51650320382171;
   fWeightMatrix2to3[0][9] = -1.60435759746058;
   fWeightMatrix2to3[1][9] = 1.41415055870738;
   fWeightMatrix2to3[2][9] = -1.90391575396273;
   fWeightMatrix2to3[3][9] = 2.05583497719711;
   fWeightMatrix2to3[4][9] = 1.78678482956757;
   fWeightMatrix2to3[5][9] = -0.542112327087092;
   fWeightMatrix2to3[6][9] = -0.836671378775619;
   fWeightMatrix2to3[7][9] = 0.0510584228402469;
   fWeightMatrix2to3[8][9] = -0.427911191656544;
   fWeightMatrix2to3[9][9] = 1.40927631622224;
   fWeightMatrix2to3[10][9] = -0.2829626411067;
   fWeightMatrix2to3[11][9] = -1.06969433453791;
   fWeightMatrix2to3[12][9] = -1.59755999980702;
   fWeightMatrix2to3[0][10] = 0.595169838051248;
   fWeightMatrix2to3[1][10] = 1.92596243683946;
   fWeightMatrix2to3[2][10] = 0.37981386219904;
   fWeightMatrix2to3[3][10] = -1.5171907672177;
   fWeightMatrix2to3[4][10] = -1.8415836626661;
   fWeightMatrix2to3[5][10] = 2.46510310671528;
   fWeightMatrix2to3[6][10] = 0.551853852588758;
   fWeightMatrix2to3[7][10] = -1.38422248809493;
   fWeightMatrix2to3[8][10] = 0.122745968400287;
   fWeightMatrix2to3[9][10] = -1.14707529800958;
   fWeightMatrix2to3[10][10] = 1.87737378847171;
   fWeightMatrix2to3[11][10] = 2.40147608416564;
   fWeightMatrix2to3[12][10] = -0.684421362276322;
   fWeightMatrix2to3[0][11] = -2.50855777238279;
   fWeightMatrix2to3[1][11] = 1.67248450637228;
   fWeightMatrix2to3[2][11] = 1.25105752601444;
   fWeightMatrix2to3[3][11] = 1.62386698508232;
   fWeightMatrix2to3[4][11] = 0.594672623663547;
   fWeightMatrix2to3[5][11] = -1.39389023371571;
   fWeightMatrix2to3[6][11] = -2.32641862595512;
   fWeightMatrix2to3[7][11] = 0.874856267685848;
   fWeightMatrix2to3[8][11] = 0.399045566361072;
   fWeightMatrix2to3[9][11] = 0.750223350933363;
   fWeightMatrix2to3[10][11] = -2.42996675502819;
   fWeightMatrix2to3[11][11] = -1.92177414663535;
   fWeightMatrix2to3[12][11] = -2.13144186810166;
   fWeightMatrix2to3[0][12] = -0.446198720952486;
   fWeightMatrix2to3[1][12] = -1.78404777905486;
   fWeightMatrix2to3[2][12] = 0.717368223146856;
   fWeightMatrix2to3[3][12] = -0.356621014324435;
   fWeightMatrix2to3[4][12] = 1.53092931460241;
   fWeightMatrix2to3[5][12] = 0.306513132488876;
   fWeightMatrix2to3[6][12] = -2.07353766326197;
   fWeightMatrix2to3[7][12] = 1.40630248008262;
   fWeightMatrix2to3[8][12] = 2.09534268070177;
   fWeightMatrix2to3[9][12] = 1.13009802698887;
   fWeightMatrix2to3[10][12] = -0.497176012666256;
   fWeightMatrix2to3[11][12] = -0.842667292094871;
   fWeightMatrix2to3[12][12] = 1.8774637894467;
   fWeightMatrix2to3[0][13] = -1.68154706860589;
   fWeightMatrix2to3[1][13] = 0.669353791163995;
   fWeightMatrix2to3[2][13] = -1.39112038591189;
   fWeightMatrix2to3[3][13] = 1.02536936589419;
   fWeightMatrix2to3[4][13] = -0.841569555270887;
   fWeightMatrix2to3[5][13] = 0.438702458113008;
   fWeightMatrix2to3[6][13] = -0.808659393472082;
   fWeightMatrix2to3[7][13] = 0.0270687565906131;
   fWeightMatrix2to3[8][13] = -0.193950081308531;
   fWeightMatrix2to3[9][13] = -0.572990803495668;
   fWeightMatrix2to3[10][13] = 0.574078388455449;
   fWeightMatrix2to3[11][13] = 0.672562692045823;
   fWeightMatrix2to3[12][13] = 0.793864483007748;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 1.31485569496649;
   fWeightMatrix3to4[1][0] = -2.85409112164709;
   fWeightMatrix3to4[2][0] = 1.0525895706624;
   fWeightMatrix3to4[3][0] = -2.24641264421857;
   fWeightMatrix3to4[4][0] = 0.442781374797485;
   fWeightMatrix3to4[5][0] = 0.468358718335009;
   fWeightMatrix3to4[6][0] = 0.366536222408798;
   fWeightMatrix3to4[7][0] = 1.37945371729781;
   fWeightMatrix3to4[8][0] = 0.808018022781201;
   fWeightMatrix3to4[9][0] = -1.9746857047753;
   fWeightMatrix3to4[10][0] = -0.853920640524839;
   fWeightMatrix3to4[11][0] = -1.36738516683934;
   fWeightMatrix3to4[12][0] = 0.0292911959282916;
   fWeightMatrix3to4[0][1] = -0.143015080218884;
   fWeightMatrix3to4[1][1] = -0.915858689631142;
   fWeightMatrix3to4[2][1] = -1.32007103797831;
   fWeightMatrix3to4[3][1] = -1.11589619873193;
   fWeightMatrix3to4[4][1] = -2.43686093177685;
   fWeightMatrix3to4[5][1] = -1.28274345019565;
   fWeightMatrix3to4[6][1] = -2.80223529359741;
   fWeightMatrix3to4[7][1] = -0.396266872222456;
   fWeightMatrix3to4[8][1] = -0.967199978264036;
   fWeightMatrix3to4[9][1] = -0.737632354020183;
   fWeightMatrix3to4[10][1] = -2.14722922038464;
   fWeightMatrix3to4[11][1] = -1.04715067496898;
   fWeightMatrix3to4[12][1] = -1.1459541770275;
   fWeightMatrix3to4[0][2] = -0.28024813503643;
   fWeightMatrix3to4[1][2] = -1.32543194793591;
   fWeightMatrix3to4[2][2] = 1.8885688573572;
   fWeightMatrix3to4[3][2] = -0.321751083944301;
   fWeightMatrix3to4[4][2] = 0.702547293450865;
   fWeightMatrix3to4[5][2] = 0.727422417678682;
   fWeightMatrix3to4[6][2] = -1.20887857458657;
   fWeightMatrix3to4[7][2] = -0.907796829086613;
   fWeightMatrix3to4[8][2] = -0.300765627324368;
   fWeightMatrix3to4[9][2] = -1.96003314054895;
   fWeightMatrix3to4[10][2] = -0.631066833704047;
   fWeightMatrix3to4[11][2] = -1.1255432524649;
   fWeightMatrix3to4[12][2] = 1.18128170138797;
   fWeightMatrix3to4[0][3] = -2.21752165892956;
   fWeightMatrix3to4[1][3] = 1.78681329310984;
   fWeightMatrix3to4[2][3] = 1.42549784669509;
   fWeightMatrix3to4[3][3] = 1.48675782615321;
   fWeightMatrix3to4[4][3] = 0.802243603722335;
   fWeightMatrix3to4[5][3] = 0.619946044082557;
   fWeightMatrix3to4[6][3] = -0.230391779109423;
   fWeightMatrix3to4[7][3] = -0.892486322514881;
   fWeightMatrix3to4[8][3] = -2.20970300319699;
   fWeightMatrix3to4[9][3] = -1.0010245067439;
   fWeightMatrix3to4[10][3] = -1.12523025886257;
   fWeightMatrix3to4[11][3] = 0.884417603041597;
   fWeightMatrix3to4[12][3] = -0.222062646962628;
   fWeightMatrix3to4[0][4] = -0.0645848150108074;
   fWeightMatrix3to4[1][4] = 1.99579718022424;
   fWeightMatrix3to4[2][4] = 0.970229590920769;
   fWeightMatrix3to4[3][4] = -1.37994439854259;
   fWeightMatrix3to4[4][4] = -0.165819079375549;
   fWeightMatrix3to4[5][4] = -1.68446793641625;
   fWeightMatrix3to4[6][4] = 0.655094365450832;
   fWeightMatrix3to4[7][4] = -1.21069161755241;
   fWeightMatrix3to4[8][4] = -0.258746818124656;
   fWeightMatrix3to4[9][4] = -0.237944547548144;
   fWeightMatrix3to4[10][4] = 0.691096551530462;
   fWeightMatrix3to4[11][4] = -2.82553238835176;
   fWeightMatrix3to4[12][4] = -0.0669092999249028;
   fWeightMatrix3to4[0][5] = -1.82651267384791;
   fWeightMatrix3to4[1][5] = -0.883878066443622;
   fWeightMatrix3to4[2][5] = 1.08191797128983;
   fWeightMatrix3to4[3][5] = -0.707501772372878;
   fWeightMatrix3to4[4][5] = 0.615282325839076;
   fWeightMatrix3to4[5][5] = -1.81529072689451;
   fWeightMatrix3to4[6][5] = 1.00198983056101;
   fWeightMatrix3to4[7][5] = -0.930107837504591;
   fWeightMatrix3to4[8][5] = 0.796983356833844;
   fWeightMatrix3to4[9][5] = -1.68085061014603;
   fWeightMatrix3to4[10][5] = -1.04869779141467;
   fWeightMatrix3to4[11][5] = 2.34927389021761;
   fWeightMatrix3to4[12][5] = -1.94868508156412;
   fWeightMatrix3to4[0][6] = -0.840552392894714;
   fWeightMatrix3to4[1][6] = -2.25297273773205;
   fWeightMatrix3to4[2][6] = 0.736293464409161;
   fWeightMatrix3to4[3][6] = 0.845238389946548;
   fWeightMatrix3to4[4][6] = 0.306620566689973;
   fWeightMatrix3to4[5][6] = -2.78391099290996;
   fWeightMatrix3to4[6][6] = 0.0906979195319306;
   fWeightMatrix3to4[7][6] = 0.574573190181449;
   fWeightMatrix3to4[8][6] = -0.620327454169681;
   fWeightMatrix3to4[9][6] = -1.24318110381705;
   fWeightMatrix3to4[10][6] = -1.6346009481546;
   fWeightMatrix3to4[11][6] = -0.906620700706513;
   fWeightMatrix3to4[12][6] = -1.28570292931381;
   fWeightMatrix3to4[0][7] = 1.53457623980605;
   fWeightMatrix3to4[1][7] = -0.298428876416424;
   fWeightMatrix3to4[2][7] = -0.148763566086226;
   fWeightMatrix3to4[3][7] = -1.10962532209597;
   fWeightMatrix3to4[4][7] = 1.28543823037703;
   fWeightMatrix3to4[5][7] = 0.450820062549519;
   fWeightMatrix3to4[6][7] = 1.16363104529044;
   fWeightMatrix3to4[7][7] = -0.878767972646297;
   fWeightMatrix3to4[8][7] = -1.58826096733534;
   fWeightMatrix3to4[9][7] = 1.65946415691162;
   fWeightMatrix3to4[10][7] = -0.00317058845758809;
   fWeightMatrix3to4[11][7] = 1.46791569831695;
   fWeightMatrix3to4[12][7] = -0.307158005161885;
   fWeightMatrix3to4[0][8] = -1.19249294623306;
   fWeightMatrix3to4[1][8] = -0.990233447927656;
   fWeightMatrix3to4[2][8] = -1.66067311380086;
   fWeightMatrix3to4[3][8] = -0.238335102709313;
   fWeightMatrix3to4[4][8] = -1.26521986066815;
   fWeightMatrix3to4[5][8] = -0.00472470773633874;
   fWeightMatrix3to4[6][8] = -0.120463814379282;
   fWeightMatrix3to4[7][8] = -0.903418022083613;
   fWeightMatrix3to4[8][8] = 0.868437166656928;
   fWeightMatrix3to4[9][8] = -1.96886236360479;
   fWeightMatrix3to4[10][8] = -1.29770695450934;
   fWeightMatrix3to4[11][8] = -0.14724137237178;
   fWeightMatrix3to4[12][8] = -1.10671921818738;
   fWeightMatrix3to4[0][9] = 0.616599046180809;
   fWeightMatrix3to4[1][9] = 1.58616091949566;
   fWeightMatrix3to4[2][9] = -2.23321569240794;
   fWeightMatrix3to4[3][9] = -0.748850406910775;
   fWeightMatrix3to4[4][9] = -2.58785021298274;
   fWeightMatrix3to4[5][9] = -0.0446865437331996;
   fWeightMatrix3to4[6][9] = -0.300198043428543;
   fWeightMatrix3to4[7][9] = -0.527600502495255;
   fWeightMatrix3to4[8][9] = -1.58773761835104;
   fWeightMatrix3to4[9][9] = -1.60527751081054;
   fWeightMatrix3to4[10][9] = 0.899968420916222;
   fWeightMatrix3to4[11][9] = -1.86139245446363;
   fWeightMatrix3to4[12][9] = 0.119248171322435;
   fWeightMatrix3to4[0][10] = -0.351262546094137;
   fWeightMatrix3to4[1][10] = -1.80374432976534;
   fWeightMatrix3to4[2][10] = -2.01297136905947;
   fWeightMatrix3to4[3][10] = -1.60638473708334;
   fWeightMatrix3to4[4][10] = -0.099383877001649;
   fWeightMatrix3to4[5][10] = 0.198768794757116;
   fWeightMatrix3to4[6][10] = -0.390665030290934;
   fWeightMatrix3to4[7][10] = -2.19294309452151;
   fWeightMatrix3to4[8][10] = 0.0798588512126668;
   fWeightMatrix3to4[9][10] = 0.0374921962657646;
   fWeightMatrix3to4[10][10] = -1.7360724046188;
   fWeightMatrix3to4[11][10] = 1.58281887487648;
   fWeightMatrix3to4[12][10] = 0.148761348764193;
   fWeightMatrix3to4[0][11] = -1.52940326316883;
   fWeightMatrix3to4[1][11] = -1.4923586525415;
   fWeightMatrix3to4[2][11] = -2.39663908501899;
   fWeightMatrix3to4[3][11] = -0.320119600048957;
   fWeightMatrix3to4[4][11] = 0.767356885284437;
   fWeightMatrix3to4[5][11] = 0.598135849926548;
   fWeightMatrix3to4[6][11] = 0.256647292056449;
   fWeightMatrix3to4[7][11] = -2.37386778115517;
   fWeightMatrix3to4[8][11] = -1.37383292868682;
   fWeightMatrix3to4[9][11] = -0.706029428722547;
   fWeightMatrix3to4[10][11] = -0.867787449654755;
   fWeightMatrix3to4[11][11] = 0.760972957535112;
   fWeightMatrix3to4[12][11] = -2.59930271234559;
   fWeightMatrix3to4[0][12] = 1.33238917495918;
   fWeightMatrix3to4[1][12] = -0.768656883951869;
   fWeightMatrix3to4[2][12] = 0.0656590421921713;
   fWeightMatrix3to4[3][12] = -2.04870755132176;
   fWeightMatrix3to4[4][12] = 1.33225437560771;
   fWeightMatrix3to4[5][12] = 0.414067445706627;
   fWeightMatrix3to4[6][12] = 1.68280761925946;
   fWeightMatrix3to4[7][12] = -1.30892808562805;
   fWeightMatrix3to4[8][12] = 1.21707369029693;
   fWeightMatrix3to4[9][12] = 0.500926335482871;
   fWeightMatrix3to4[10][12] = 1.35958013161249;
   fWeightMatrix3to4[11][12] = -0.922439221635325;
   fWeightMatrix3to4[12][12] = -1.74459410011139;
   fWeightMatrix3to4[0][13] = -1.81551825913458;
   fWeightMatrix3to4[1][13] = -0.210763078718636;
   fWeightMatrix3to4[2][13] = 0.112715907794904;
   fWeightMatrix3to4[3][13] = 0.149465279560901;
   fWeightMatrix3to4[4][13] = -0.403356094943395;
   fWeightMatrix3to4[5][13] = -0.533637542294049;
   fWeightMatrix3to4[6][13] = -1.2890210591429;
   fWeightMatrix3to4[7][13] = 1.16087804275827;
   fWeightMatrix3to4[8][13] = -0.301600264706631;
   fWeightMatrix3to4[9][13] = -1.86786349475588;
   fWeightMatrix3to4[10][13] = -0.32813924305393;
   fWeightMatrix3to4[11][13] = -0.514996615987707;
   fWeightMatrix3to4[12][13] = 0.455980571625087;
   // weight matrix from layer 4 to 5
   fWeightMatrix4to5[0][0] = 1.09994699412479;
   fWeightMatrix4to5[0][1] = -0.953905890708624;
   fWeightMatrix4to5[0][2] = 0.630946841575624;
   fWeightMatrix4to5[0][3] = 0.0364725031161133;
   fWeightMatrix4to5[0][4] = -0.503495955285938;
   fWeightMatrix4to5[0][5] = -0.359506303121246;
   fWeightMatrix4to5[0][6] = -0.0219919960297292;
   fWeightMatrix4to5[0][7] = 1.24520722443848;
   fWeightMatrix4to5[0][8] = -0.456073863793589;
   fWeightMatrix4to5[0][9] = 1.11036104200524;
   fWeightMatrix4to5[0][10] = 0.400376676783181;
   fWeightMatrix4to5[0][11] = -1.28292743849258;
   fWeightMatrix4to5[0][12] = -0.0934015905755232;
   fWeightMatrix4to5[0][13] = 0.115670551007486;
}

inline double ReadkMLP_pca_ce_600_4(n+2)_no_ev::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]-1; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = ActivationFnc(fWeights[4][o]);
   }
   // layer 4 to 5
   for (int o=0; o<fLayerSize[5]; o++) {
      for (int i=0; i<fLayerSize[4]; i++) {
         double inputVal = fWeightMatrix4to5[o][i] * fWeights[4][i];
         fWeights[5][o] += inputVal;
      }
      fWeights[5][o] = OutputActivationFnc(fWeights[5][o]);
   }

   return fWeights[5][0];
}

double ReadkMLP_pca_ce_600_4(n+2)_no_ev::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_pca_ce_600_4(n+2)_no_ev::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 6; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_pca_ce_600_4(n+2)_no_ev::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00020475036581;
   fMax_1[0][0] = 520.089416504;
   fMin_1[1][0] = 4.45244913863e-05;
   fMax_1[1][0] = 591.79876709;
   fMin_1[2][0] = 4.45244913863e-05;
   fMax_1[2][0] = 591.79876709;
   fMin_1[0][1] = 6.05733257544e-05;
   fMax_1[0][1] = 447.772735596;
   fMin_1[1][1] = 2.60141878243e-05;
   fMax_1[1][1] = 680.619262695;
   fMin_1[2][1] = 2.60141878243e-05;
   fMax_1[2][1] = 680.619262695;
   fMin_1[0][2] = -7820.53808594;
   fMax_1[0][2] = 62832.4140625;
   fMin_1[1][2] = -27109.4433594;
   fMax_1[1][2] = 117643.984375;
   fMin_1[2][2] = -27109.4433594;
   fMax_1[2][2] = 117643.984375;
   fMin_1[0][3] = -4486.09814453;
   fMax_1[0][3] = 336199.4375;
   fMin_1[1][3] = -30494.9765625;
   fMax_1[1][3] = 233789.203125;
   fMin_1[2][3] = -30494.9765625;
   fMax_1[2][3] = 336199.4375;
   fMin_1[0][4] = -848390.4375;
   fMax_1[0][4] = 21884.8886719;
   fMin_1[1][4] = -129755.617188;
   fMax_1[1][4] = 742903.3125;
   fMin_1[2][4] = -848390.4375;
   fMax_1[2][4] = 742903.3125;
   fMin_1[0][5] = -1816.70861816;
   fMax_1[0][5] = 876.452758789;
   fMin_1[1][5] = -4408.59033203;
   fMax_1[1][5] = 5815.69433594;
   fMin_1[2][5] = -4408.59033203;
   fMax_1[2][5] = 5815.69433594;
   fMin_1[0][6] = -667.623535156;
   fMax_1[0][6] = 2655.89135742;
   fMin_1[1][6] = -10921.9150391;
   fMax_1[1][6] = 10528.8847656;
   fMin_1[2][6] = -10921.9150391;
   fMax_1[2][6] = 10528.8847656;
   fMin_1[0][7] = -6113.18701172;
   fMax_1[0][7] = 4820.41601562;
   fMin_1[1][7] = -36484.0898438;
   fMax_1[1][7] = 32938.125;
   fMin_1[2][7] = -36484.0898438;
   fMax_1[2][7] = 32938.125;
   fMin_1[0][8] = 0.0162057429552;
   fMax_1[0][8] = 179.977890015;
   fMin_1[1][8] = 0.0153690213338;
   fMax_1[1][8] = 179.980255127;
   fMin_1[2][8] = 0.0153690213338;
   fMax_1[2][8] = 179.980255127;
   fMin_1[0][9] = 0.0196817759424;
   fMax_1[0][9] = 3842.51171875;
   fMin_1[1][9] = 0.0131534170359;
   fMax_1[1][9] = 76398.515625;
   fMin_1[2][9] = 0.0131534170359;
   fMax_1[2][9] = 76398.515625;
   fMin_1[0][10] = 0.263680070639;
   fMax_1[0][10] = 914557.375;
   fMin_1[1][10] = 0.0941462889314;
   fMax_1[1][10] = 752596.375;
   fMin_1[2][10] = 0.0941462889314;
   fMax_1[2][10] = 914557.375;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::X2P_2( const double* x, double* p, int index ) const
{
   // Calculate the principal components from the original data vector
   // x, and return it in p (function extracted from TPrincipal::X2P)
   // It's the users responsibility to make sure that both x and p are
   // of the right size (i.e., memory must be allocated for p).
   const int nVar = 11;

   for (int i = 0; i < nVar; i++) {
      p[i] = 0;
      for (int j = 0; j < nVar; j++) p[i] += (x[j] - fMeanValues_2[index][j]) * fEigenVectors_2[index][j][i];
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::InitTransform_2()
{
   // PCA transformation, initialisation
   // initialise vector of mean values
   fMeanValues_2[0][0] = -0.955631178092;
   fMeanValues_2[0][1] = -0.960562362655;
   fMeanValues_2[0][2] = -0.625429721055;
   fMeanValues_2[0][3] = -0.833646823028;
   fMeanValues_2[0][4] = 0.0662344895832;
   fMeanValues_2[0][5] = -0.137688739778;
   fMeanValues_2[0][6] = 0.0183553754278;
   fMeanValues_2[0][7] = 0.0503883368015;
   fMeanValues_2[0][8] = -0.058544710889;
   fMeanValues_2[0][9] = -0.99923571065;
   fMeanValues_2[0][10] = -0.999816184737;
   fMeanValues_2[1][0] = -0.960047413504;
   fMeanValues_2[1][1] = -0.965126158216;
   fMeanValues_2[1][2] = -0.625437107469;
   fMeanValues_2[1][3] = -0.833682760356;
   fMeanValues_2[1][4] = 0.066254497838;
   fMeanValues_2[1][5] = -0.137689963785;
   fMeanValues_2[1][6] = 0.0183274331275;
   fMeanValues_2[1][7] = 0.0501719019501;
   fMeanValues_2[1][8] = -0.0264143476865;
   fMeanValues_2[1][9] = -0.999302976516;
   fMeanValues_2[1][10] = -0.999889302607;
   fMeanValues_2[2][0] = -0.959558700269;
   fMeanValues_2[2][1] = -0.964621115552;
   fMeanValues_2[2][2] = -0.625436290067;
   fMeanValues_2[2][3] = -0.833678783429;
   fMeanValues_2[2][4] = 0.0662522836673;
   fMeanValues_2[2][5] = -0.137689828333;
   fMeanValues_2[2][6] = 0.0183305253023;
   fMeanValues_2[2][7] = 0.0501958532495;
   fMeanValues_2[2][8] = -0.0299699855308;
   fMeanValues_2[2][9] = -0.999295532683;
   fMeanValues_2[2][10] = -0.999881211174;

   // initialise matrix of eigenvectors
   fEigenVectors_2[0][0][0] = -0.00124548751491;
   fEigenVectors_2[0][0][1] = 0.972066211403;
   fEigenVectors_2[0][0][2] = -0.234625407714;
   fEigenVectors_2[0][0][3] = 0.000432365142958;
   fEigenVectors_2[0][0][4] = 0.00210035113886;
   fEigenVectors_2[0][0][5] = -0.00225641633836;
   fEigenVectors_2[0][0][6] = -0.00274537684688;
   fEigenVectors_2[0][0][7] = -0.00439793701113;
   fEigenVectors_2[0][0][8] = 0.000190350302269;
   fEigenVectors_2[0][0][9] = 0.000201307884843;
   fEigenVectors_2[0][0][10] = 4.39665972435e-05;
   fEigenVectors_2[0][1][0] = -0.00324131085559;
   fEigenVectors_2[0][1][1] = 0.234565103413;
   fEigenVectors_2[0][1][2] = 0.972048758192;
   fEigenVectors_2[0][1][3] = 0.00349042993415;
   fEigenVectors_2[0][1][4] = 0.00193762385968;
   fEigenVectors_2[0][1][5] = -0.00139139092605;
   fEigenVectors_2[0][1][6] = -0.00205631043734;
   fEigenVectors_2[0][1][7] = -0.0082273492638;
   fEigenVectors_2[0][1][8] = -0.000352870157756;
   fEigenVectors_2[0][1][9] = 3.14742663408e-05;
   fEigenVectors_2[0][1][10] = 3.4780858864e-05;
   fEigenVectors_2[0][2][0] = 0.000112807016303;
   fEigenVectors_2[0][2][1] = 4.47462082388e-05;
   fEigenVectors_2[0][2][2] = 0.00108260392193;
   fEigenVectors_2[0][2][3] = -0.287874540571;
   fEigenVectors_2[0][2][4] = -0.0205690262582;
   fEigenVectors_2[0][2][5] = -0.042871072691;
   fEigenVectors_2[0][2][6] = 0.0136475438522;
   fEigenVectors_2[0][2][7] = -0.0340065759678;
   fEigenVectors_2[0][2][8] = 0.940519778376;
   fEigenVectors_2[0][2][9] = -0.0801411217939;
   fEigenVectors_2[0][2][10] = 0.150077622701;
   fEigenVectors_2[0][3][0] = 0.000106930658603;
   fEigenVectors_2[0][3][1] = 0.000203809481941;
   fEigenVectors_2[0][3][2] = 0.00149113448797;
   fEigenVectors_2[0][3][3] = -0.601949882274;
   fEigenVectors_2[0][3][4] = 0.0115824529268;
   fEigenVectors_2[0][3][5] = -0.00166065891462;
   fEigenVectors_2[0][3][6] = -0.00937375811389;
   fEigenVectors_2[0][3][7] = -0.0555718572058;
   fEigenVectors_2[0][3][8] = -0.193284856367;
   fEigenVectors_2[0][3][9] = 0.66149779391;
   fEigenVectors_2[0][3][10] = 0.399252659438;
   fEigenVectors_2[0][4][0] = -0.000132963805879;
   fEigenVectors_2[0][4][1] = -7.86854111227e-05;
   fEigenVectors_2[0][4][2] = -0.000904220975404;
   fEigenVectors_2[0][4][3] = 0.350321496706;
   fEigenVectors_2[0][4][4] = -0.00280007904874;
   fEigenVectors_2[0][4][5] = 0.012283621877;
   fEigenVectors_2[0][4][6] = 0.0299119956073;
   fEigenVectors_2[0][4][7] = 0.0346841025262;
   fEigenVectors_2[0][4][8] = -0.0558504754512;
   fEigenVectors_2[0][4][9] = -0.238927671054;
   fEigenVectors_2[0][4][10] = 0.90266929581;
   fEigenVectors_2[0][5][0] = -0.000150350544091;
   fEigenVectors_2[0][5][1] = -0.00215647232069;
   fEigenVectors_2[0][5][2] = -0.00127336927959;
   fEigenVectors_2[0][5][3] = 0.00249422790541;
   fEigenVectors_2[0][5][4] = 0.995345651209;
   fEigenVectors_2[0][5][5] = 0.0795956954302;
   fEigenVectors_2[0][5][6] = 0.0475813805935;
   fEigenVectors_2[0][5][7] = -0.0028474526824;
   fEigenVectors_2[0][5][8] = 0.0248977936456;
   fEigenVectors_2[0][5][9] = -0.00682357274465;
   fEigenVectors_2[0][5][10] = -0.000698017642293;
   fEigenVectors_2[0][6][0] = 0.000109431448307;
   fEigenVectors_2[0][6][1] = 0.000859107843496;
   fEigenVectors_2[0][6][2] = 0.000204957251734;
   fEigenVectors_2[0][6][3] = -0.00181763278097;
   fEigenVectors_2[0][6][4] = -0.0483862833447;
   fEigenVectors_2[0][6][5] = 0.876645408239;
   fEigenVectors_2[0][6][6] = -0.476513455166;
   fEigenVectors_2[0][6][7] = 0.00547855850608;
   fEigenVectors_2[0][6][8] = 0.0444914489321;
   fEigenVectors_2[0][6][9] = 0.0033637248372;
   fEigenVectors_2[0][6][10] = 0.00784912284359;
   fEigenVectors_2[0][7][0] = 0.0010476137372;
   fEigenVectors_2[0][7][1] = 0.0038465830385;
   fEigenVectors_2[0][7][2] = 0.00135819330933;
   fEigenVectors_2[0][7][3] = 0.00203914108195;
   fEigenVectors_2[0][7][4] = -0.0798229515813;
   fEigenVectors_2[0][7][5] = 0.471472385068;
   fEigenVectors_2[0][7][6] = 0.875925949159;
   fEigenVectors_2[0][7][7] = -0.0474012511197;
   fEigenVectors_2[0][7][8] = 0.0127196774019;
   fEigenVectors_2[0][7][9] = 0.0319222261034;
   fEigenVectors_2[0][7][10] = -0.025420942299;
   fEigenVectors_2[0][8][0] = -0.999993343511;
   fEigenVectors_2[0][8][1] = -0.00196805076002;
   fEigenVectors_2[0][8][2] = -0.00285808259214;
   fEigenVectors_2[0][8][3] = -0.000218593031116;
   fEigenVectors_2[0][8][4] = -0.000247938999078;
   fEigenVectors_2[0][8][5] = 0.000577478749069;
   fEigenVectors_2[0][8][6] = 0.00085608666149;
   fEigenVectors_2[0][8][7] = -0.000288793701447;
   fEigenVectors_2[0][8][8] = 6.96967863304e-05;
   fEigenVectors_2[0][8][9] = 3.13595067431e-05;
   fEigenVectors_2[0][8][10] = -7.87857916008e-05;
   fEigenVectors_2[0][9][0] = -0.000267510176352;
   fEigenVectors_2[0][9][1] = 0.00631219937576;
   fEigenVectors_2[0][9][2] = 0.00702078944386;
   fEigenVectors_2[0][9][3] = -0.00465760119175;
   fEigenVectors_2[0][9][4] = -0.0006679697213;
   fEigenVectors_2[0][9][5] = 0.01386202279;
   fEigenVectors_2[0][9][6] = 0.0417011496323;
   fEigenVectors_2[0][9][7] = 0.993100436406;
   fEigenVectors_2[0][9][8] = 0.044322377719;
   fEigenVectors_2[0][9][9] = 0.0982888412533;
   fEigenVectors_2[0][9][10] = -0.00915782905;
   fEigenVectors_2[0][10][0] = 0.000100606956675;
   fEigenVectors_2[0][10][1] = 0.00159419344138;
   fEigenVectors_2[0][10][2] = 0.00263596982959;
   fEigenVectors_2[0][10][3] = -0.657275926028;
   fEigenVectors_2[0][10][4] = 0.000588715692572;
   fEigenVectors_2[0][10][5] = 0.0260778264391;
   fEigenVectors_2[0][10][6] = 0.022457433268;
   fEigenVectors_2[0][10][7] = 0.0770178031015;
   fEigenVectors_2[0][10][8] = -0.264987579048;
   fEigenVectors_2[0][10][9] = -0.698694492702;
   fEigenVectors_2[0][10][10] = 0.049698773126;
   fEigenVectors_2[1][0][0] = 0.00032241293771;
   fEigenVectors_2[1][0][1] = 0.971571408917;
   fEigenVectors_2[1][0][2] = 0.236663383929;
   fEigenVectors_2[1][0][3] = 0.00214737749669;
   fEigenVectors_2[1][0][4] = -0.00312328992915;
   fEigenVectors_2[1][0][5] = 0.00474941708482;
   fEigenVectors_2[1][0][6] = 0.000650487041638;
   fEigenVectors_2[1][0][7] = 0.00122876718287;
   fEigenVectors_2[1][0][8] = -0.000594887278687;
   fEigenVectors_2[1][0][9] = -0.000349718535171;
   fEigenVectors_2[1][0][10] = -6.1673078362e-05;
   fEigenVectors_2[1][1][0] = 0.00315749321481;
   fEigenVectors_2[1][1][1] = 0.236606986372;
   fEigenVectors_2[1][1][2] = -0.971555603909;
   fEigenVectors_2[1][1][3] = 0.000718619023197;
   fEigenVectors_2[1][1][4] = -0.00133579128776;
   fEigenVectors_2[1][1][5] = 0.00905329802753;
   fEigenVectors_2[1][1][6] = -0.00020298587431;
   fEigenVectors_2[1][1][7] = 0.000393044599391;
   fEigenVectors_2[1][1][8] = -0.00153836265604;
   fEigenVectors_2[1][1][9] = -0.000182805908062;
   fEigenVectors_2[1][1][10] = 0.000118859086583;
   fEigenVectors_2[1][2][0] = -2.66444597084e-05;
   fEigenVectors_2[1][2][1] = 1.39100732648e-05;
   fEigenVectors_2[1][2][2] = 5.86791506338e-05;
   fEigenVectors_2[1][2][3] = 0.171255340031;
   fEigenVectors_2[1][2][4] = 0.43561713026;
   fEigenVectors_2[1][2][5] = 0.172461048142;
   fEigenVectors_2[1][2][6] = 0.467806881279;
   fEigenVectors_2[1][2][7] = 0.123816745359;
   fEigenVectors_2[1][2][8] = 0.670179892688;
   fEigenVectors_2[1][2][9] = -0.232543900357;
   fEigenVectors_2[1][2][10] = -0.117366469242;
   fEigenVectors_2[1][3][0] = 9.31672040827e-06;
   fEigenVectors_2[1][3][1] = -5.2118779653e-05;
   fEigenVectors_2[1][3][2] = 0.00019213527661;
   fEigenVectors_2[1][3][3] = 0.152938575828;
   fEigenVectors_2[1][3][4] = 0.256671926929;
   fEigenVectors_2[1][3][5] = -0.0577640376257;
   fEigenVectors_2[1][3][6] = 0.227440327393;
   fEigenVectors_2[1][3][7] = 0.0685567050258;
   fEigenVectors_2[1][3][8] = -0.525998610038;
   fEigenVectors_2[1][3][9] = -0.659582765031;
   fEigenVectors_2[1][3][10] = 0.373148099516;
   fEigenVectors_2[1][4][0] = 6.52523037421e-05;
   fEigenVectors_2[1][4][1] = 0.000198333025668;
   fEigenVectors_2[1][4][2] = -6.84533086083e-05;
   fEigenVectors_2[1][4][3] = 0.109203912194;
   fEigenVectors_2[1][4][4] = 0.197460982586;
   fEigenVectors_2[1][4][5] = -0.0481641869648;
   fEigenVectors_2[1][4][6] = 0.149788235515;
   fEigenVectors_2[1][4][7] = 0.031469950342;
   fEigenVectors_2[1][4][8] = -0.408341602898;
   fEigenVectors_2[1][4][9] = -0.00513776477813;
   fEigenVectors_2[1][4][10] = -0.869808998674;
   fEigenVectors_2[1][5][0] = 0.000166498311363;
   fEigenVectors_2[1][5][1] = -0.00282693309107;
   fEigenVectors_2[1][5][2] = 0.000327049772095;
   fEigenVectors_2[1][5][3] = 0.934561168027;
   fEigenVectors_2[1][5][4] = -0.298661547;
   fEigenVectors_2[1][5][5] = 0.00470644263156;
   fEigenVectors_2[1][5][6] = -0.094396484607;
   fEigenVectors_2[1][5][7] = -0.15975522003;
   fEigenVectors_2[1][5][8] = 0.0532505518726;
   fEigenVectors_2[1][5][9] = 0.00967628321731;
   fEigenVectors_2[1][5][10] = 0.00217907280905;
   fEigenVectors_2[1][6][0] = -4.3190293195e-05;
   fEigenVectors_2[1][6][1] = 0.0007058410765;
   fEigenVectors_2[1][6][2] = 7.05555359048e-06;
   fEigenVectors_2[1][6][3] = 0.166899698559;
   fEigenVectors_2[1][6][4] = 0.419139365379;
   fEigenVectors_2[1][6][5] = -0.00293676774225;
   fEigenVectors_2[1][6][6] = -0.661612590123;
   fEigenVectors_2[1][6][7] = 0.597521618141;
   fEigenVectors_2[1][6][8] = 0.0403025666849;
   fEigenVectors_2[1][6][9] = 0.00671121929186;
   fEigenVectors_2[1][6][10] = 0.00499173096344;
   fEigenVectors_2[1][7][0] = -0.000784549970505;
   fEigenVectors_2[1][7][1] = 0.00309347392569;
   fEigenVectors_2[1][7][2] = -0.000377250054355;
   fEigenVectors_2[1][7][3] = 0.00543889314825;
   fEigenVectors_2[1][7][4] = 0.541557667908;
   fEigenVectors_2[1][7][5] = -0.0104999458449;
   fEigenVectors_2[1][7][6] = -0.344672074982;
   fEigenVectors_2[1][7][7] = -0.765592215055;
   fEigenVectors_2[1][7][8] = 0.0345730671332;
   fEigenVectors_2[1][7][9] = -0.00123367784393;
   fEigenVectors_2[1][7][10] = 0.0209293223642;
   fEigenVectors_2[1][8][0] = 0.999994606341;
   fEigenVectors_2[1][8][1] = -0.00105913956291;
   fEigenVectors_2[1][8][2] = 0.00299301230285;
   fEigenVectors_2[1][8][3] = -0.000155574910639;
   fEigenVectors_2[1][8][4] = 0.000484325901734;
   fEigenVectors_2[1][8][5] = 0.000216294993185;
   fEigenVectors_2[1][8][6] = -0.000298136361642;
   fEigenVectors_2[1][8][7] = -0.000554520096001;
   fEigenVectors_2[1][8][8] = 3.13727496898e-05;
   fEigenVectors_2[1][8][9] = 8.92853045558e-07;
   fEigenVectors_2[1][8][10] = 6.68445479484e-05;
   fEigenVectors_2[1][9][0] = 0.000250880120752;
   fEigenVectors_2[1][9][1] = 0.00674261101053;
   fEigenVectors_2[1][9][2] = -0.00777117784469;
   fEigenVectors_2[1][9][3] = 0.00190737014994;
   fEigenVectors_2[1][9][4] = 0.00632243393631;
   fEigenVectors_2[1][9][5] = -0.977455933056;
   fEigenVectors_2[1][9][6] = 0.030692250821;
   fEigenVectors_2[1][9][7] = 0.0121732936854;
   fEigenVectors_2[1][9][8] = 0.193712301486;
   fEigenVectors_2[1][9][9] = -0.0705332741431;
   fEigenVectors_2[1][9][10] = -0.0289960153198;
   fEigenVectors_2[1][10][0] = 2.17785669182e-05;
   fEigenVectors_2[1][10][1] = 0.00120216744707;
   fEigenVectors_2[1][10][2] = -0.000712402950174;
   fEigenVectors_2[1][10][3] = 0.184546602423;
   fEigenVectors_2[1][10][4] = 0.383605808284;
   fEigenVectors_2[1][10][5] = -0.094525249733;
   fEigenVectors_2[1][10][6] = 0.374977041078;
   fEigenVectors_2[1][10][7] = 0.100715534255;
   fEigenVectors_2[1][10][8] = -0.253493819863;
   fEigenVectors_2[1][10][9] = 0.711148523509;
   fEigenVectors_2[1][10][10] = 0.298512009768;
   fEigenVectors_2[2][0][0] = 0.000389372067861;
   fEigenVectors_2[2][0][1] = 0.971447590234;
   fEigenVectors_2[2][0][2] = 0.237171797666;
   fEigenVectors_2[2][0][3] = 0.00163551287592;
   fEigenVectors_2[2][0][4] = -0.00298864404236;
   fEigenVectors_2[2][0][5] = -0.00114899432185;
   fEigenVectors_2[2][0][6] = 0.00490647134824;
   fEigenVectors_2[2][0][7] = -0.00118706442018;
   fEigenVectors_2[2][0][8] = 0.000300703033577;
   fEigenVectors_2[2][0][9] = 0.000577994695923;
   fEigenVectors_2[2][0][10] = 0.000363377857948;
   fEigenVectors_2[2][1][0] = 0.00312774388488;
   fEigenVectors_2[2][1][1] = 0.237115111756;
   fEigenVectors_2[2][1][2] = -0.971432216781;
   fEigenVectors_2[2][1][3] = 0.000388739073184;
   fEigenVectors_2[2][1][4] = -0.00179007346794;
   fEigenVectors_2[2][1][5] = 0.000827567705969;
   fEigenVectors_2[2][1][6] = 0.00890183162844;
   fEigenVectors_2[2][1][7] = -0.000695539516227;
   fEigenVectors_2[2][1][8] = -0.000650848956431;
   fEigenVectors_2[2][1][9] = 0.00136268232536;
   fEigenVectors_2[2][1][10] = 0.000204835421369;
   fEigenVectors_2[2][2][0] = -3.64440451388e-05;
   fEigenVectors_2[2][2][1] = 1.74347248114e-05;
   fEigenVectors_2[2][2][2] = -7.03169643011e-05;
   fEigenVectors_2[2][2][3] = 0.241544614895;
   fEigenVectors_2[2][2][4] = 0.401063898439;
   fEigenVectors_2[2][2][5] = -0.0257503825597;
   fEigenVectors_2[2][2][6] = 0.198631502763;
   fEigenVectors_2[2][2][7] = 0.112897865047;
   fEigenVectors_2[2][2][8] = 0.601005139086;
   fEigenVectors_2[2][2][9] = -0.565110312077;
   fEigenVectors_2[2][2][10] = 0.217677779664;
   fEigenVectors_2[2][3][0] = -4.12900928917e-06;
   fEigenVectors_2[2][3][1] = -2.13180999275e-05;
   fEigenVectors_2[2][3][2] = 2.90850743421e-06;
   fEigenVectors_2[2][3][3] = 0.272033252244;
   fEigenVectors_2[2][3][4] = 0.411394688001;
   fEigenVectors_2[2][3][5] = -0.28812211906;
   fEigenVectors_2[2][3][6] = -0.00134500363304;
   fEigenVectors_2[2][3][7] = -0.0737622756106;
   fEigenVectors_2[2][3][8] = -0.256642781555;
   fEigenVectors_2[2][3][9] = 0.3913986434;
   fEigenVectors_2[2][3][10] = 0.670251345891;
   fEigenVectors_2[2][4][0] = 7.30568393954e-05;
   fEigenVectors_2[2][4][1] = 0.000166079562268;
   fEigenVectors_2[2][4][2] = 4.01888792738e-05;
   fEigenVectors_2[2][4][3] = 0.0446329160614;
   fEigenVectors_2[2][4][4] = -0.0354763460954;
   fEigenVectors_2[2][4][5] = 0.303015696125;
   fEigenVectors_2[2][4][6] = -0.0807013948757;
   fEigenVectors_2[2][4][7] = 0.161570592454;
   fEigenVectors_2[2][4][8] = 0.646647629313;
   fEigenVectors_2[2][4][9] = 0.673890416239;
   fEigenVectors_2[2][4][10] = 0.0056181814512;
   fEigenVectors_2[2][5][0] = 0.000164617951091;
   fEigenVectors_2[2][5][1] = -0.00274906275542;
   fEigenVectors_2[2][5][2] = 0.000432087405995;
   fEigenVectors_2[2][5][3] = 0.856804968831;
   fEigenVectors_2[2][5][4] = -0.490773901532;
   fEigenVectors_2[2][5][5] = 0.0549553968289;
   fEigenVectors_2[2][5][6] = -0.00946611358111;
   fEigenVectors_2[2][5][7] = 0.109526952303;
   fEigenVectors_2[2][5][8] = -0.0815754771512;
   fEigenVectors_2[2][5][9] = -0.056333329679;
   fEigenVectors_2[2][5][10] = -0.00919744988898;
   fEigenVectors_2[2][6][0] = -5.09058868663e-05;
   fEigenVectors_2[2][6][1] = 0.0007248654058;
   fEigenVectors_2[2][6][2] = -1.87358738191e-05;
   fEigenVectors_2[2][6][3] = 0.164686607205;
   fEigenVectors_2[2][6][4] = 0.208377163073;
   fEigenVectors_2[2][6][5] = 0.607730927407;
   fEigenVectors_2[2][6][6] = -0.0966490070495;
   fEigenVectors_2[2][6][7] = -0.738026942362;
   fEigenVectors_2[2][6][8] = -0.0567622254154;
   fEigenVectors_2[2][6][9] = -0.0533176585339;
   fEigenVectors_2[2][6][10] = -0.00550905215721;
   fEigenVectors_2[2][7][0] = -0.000815900146009;
   fEigenVectors_2[2][7][1] = 0.00319134228778;
   fEigenVectors_2[2][7][2] = -0.000500267663168;
   fEigenVectors_2[2][7][3] = 0.0331250198333;
   fEigenVectors_2[2][7][4] = 0.33373119129;
   fEigenVectors_2[2][7][5] = 0.588123149501;
   fEigenVectors_2[2][7][6] = -0.0954673712094;
   fEigenVectors_2[2][7][7] = 0.630874462793;
   fEigenVectors_2[2][7][8] = -0.360827967473;
   fEigenVectors_2[2][7][9] = -0.0655571087164;
   fEigenVectors_2[2][7][10] = 0.00388870573117;
   fEigenVectors_2[2][8][0] = 0.999994649945;
   fEigenVectors_2[2][8][1] = -0.00111851265344;
   fEigenVectors_2[2][8][2] = 0.00294751642832;
   fEigenVectors_2[2][8][3] = -0.000104730784576;
   fEigenVectors_2[2][8][4] = 0.000381122956135;
   fEigenVectors_2[2][8][5] = 0.000512608101755;
   fEigenVectors_2[2][8][6] = 0.000146069054933;
   fEigenVectors_2[2][8][7] = 0.000448643891397;
   fEigenVectors_2[2][8][8] = -0.000336640867898;
   fEigenVectors_2[2][8][9] = -7.88619013105e-05;
   fEigenVectors_2[2][8][10] = 1.86206092217e-06;
   fEigenVectors_2[2][9][0] = 0.000252129103952;
   fEigenVectors_2[2][9][1] = 0.00670006547991;
   fEigenVectors_2[2][9][2] = -0.00768052600197;
   fEigenVectors_2[2][9][3] = 0.00616067771188;
   fEigenVectors_2[2][9][4] = 0.017500464208;
   fEigenVectors_2[2][9][5] = -0.139264529746;
   fEigenVectors_2[2][9][6] = -0.966559594504;
   fEigenVectors_2[2][9][7] = 0.0210575893459;
   fEigenVectors_2[2][9][8] = 0.11347928411;
   fEigenVectors_2[2][9][9] = -0.167127357091;
   fEigenVectors_2[2][9][10] = 0.0683172922703;
   fEigenVectors_2[2][10][0] = 7.32562710098e-06;
   fEigenVectors_2[2][10][1] = 0.00125118968172;
   fEigenVectors_2[2][10][2] = -0.000929716907795;
   fEigenVectors_2[2][10][3] = 0.321383758782;
   fEigenVectors_2[2][10][4] = 0.522176664079;
   fEigenVectors_2[2][10][5] = -0.294722510835;
   fEigenVectors_2[2][10][6] = -0.0338460924301;
   fEigenVectors_2[2][10][7] = -0.0240856271109;
   fEigenVectors_2[2][10][8] = -0.0426924217948;
   fEigenVectors_2[2][10][9] = 0.187300406015;
   fEigenVectors_2[2][10][10] = -0.706081059375;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::Transform_2( std::vector<double>& iv, int cls ) const
{
   // PCA transformation
   const int nVar = 11;
   double *dv = new double[nVar];
   double *rv = new double[nVar];
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];

   // Perform PCA and put it into PCAed events tree
   this->X2P_2( dv, rv, cls );
   for (int ivar=0; ivar<nVar; ivar++) iv[indicesPut.at(ivar)] = rv[ivar];

   delete [] dv;
   delete [] rv;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_4(n+2)_no_ev::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
