// Class: ReadkMLP_pca_ce_600_n2_no_ev
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_pca_ce_600_n2_no_ev
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Mon Aug 12 13:10:38 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/nyx/hades/user/knowakow/PP/FAT/TMVA
Training events: 400568
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N,P" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [4.45244913863e-05,591.79876709]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [2.60141878243e-05,680.619262695]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-27109.4433594,117643.984375]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-30494.9765625,336199.4375]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-848390.4375,742903.3125]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-4408.59033203,5815.69433594]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-10921.9150391,10528.8847656]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-36484.0898438,32938.125]
oa_lambda                     oa_lambda                     oa_lambda                     oa_lambda                     deg                               'F'    [0.0153690213338,179.980255127]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.0131534170359,76398.515625]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.0941462889314,914557.375]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_pca_ce_600_n2_no_ev : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_pca_ce_600_n2_no_ev( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_pca_ce_600_n2_no_ev" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "oa_lambda", "dist_lambda_ver_pip_pim", "dist_ver_to_ver" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.970137178897858;
      fVmax[0] = 1.03263676166534;
      fVmin[1] = -0.0487020127475262;
      fVmax[1] = 1.89828264713287;
      fVmin[2] = -1.87950766086578;
      fVmax[2] = 0.487048923969269;
      fVmin[3] = -0.791524469852448;
      fVmax[3] = 2.47808957099915;
      fVmin[4] = -0.526382446289062;
      fVmax[4] = 2.18375658988953;
      fVmin[5] = -1.46485781669617;
      fVmax[5] = 0.606749951839447;
      fVmin[6] = -2.02398252487183;
      fVmax[6] = 0.181860625743866;
      fVmin[7] = -0.336992591619492;
      fVmax[7] = 0.529070675373077;
      fVmin[8] = -0.720848262310028;
      fVmax[8] = 0.691642463207245;
      fVmin[9] = -0.485793143510818;
      fVmax[9] = 0.339316040277481;
      fVmin[10] = -0.179725304245949;
      fVmax[10] = 0.0395826622843742;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_pca_ce_600_n2_no_ev() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];

   void X2P_2( const double*, double*, int ) const;
   double fMeanValues_2[3][11];
   double fEigenVectors_2[3][11][11];

   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][12];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadkMLP_pca_ce_600_n2_no_ev::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.496448940029209;
   fWeightMatrix0to1[1][0] = 1.30682258085873;
   fWeightMatrix0to1[2][0] = 1.34126097900625;
   fWeightMatrix0to1[3][0] = 2.82963531666467;
   fWeightMatrix0to1[4][0] = -1.72130260221978;
   fWeightMatrix0to1[5][0] = -0.94384004596644;
   fWeightMatrix0to1[6][0] = 0.353294177842878;
   fWeightMatrix0to1[7][0] = 2.72409437531653;
   fWeightMatrix0to1[8][0] = -1.7703121442756;
   fWeightMatrix0to1[9][0] = -0.860309664122254;
   fWeightMatrix0to1[10][0] = -2.50065277101169;
   fWeightMatrix0to1[0][1] = 4.5737671713533;
   fWeightMatrix0to1[1][1] = -2.09970700995891;
   fWeightMatrix0to1[2][1] = 1.01191534394713;
   fWeightMatrix0to1[3][1] = -2.81988762629796;
   fWeightMatrix0to1[4][1] = -1.78870660723771;
   fWeightMatrix0to1[5][1] = -3.722978673245;
   fWeightMatrix0to1[6][1] = 12.3334660538037;
   fWeightMatrix0to1[7][1] = -0.223803961895653;
   fWeightMatrix0to1[8][1] = 3.70690223004094;
   fWeightMatrix0to1[9][1] = -3.91201023814451;
   fWeightMatrix0to1[10][1] = 0.954898401671319;
   fWeightMatrix0to1[0][2] = -0.125033589578479;
   fWeightMatrix0to1[1][2] = -0.364462658533595;
   fWeightMatrix0to1[2][2] = -1.74983619157263;
   fWeightMatrix0to1[3][2] = 0.367400353830976;
   fWeightMatrix0to1[4][2] = 1.17832719218738;
   fWeightMatrix0to1[5][2] = -1.07220406830904;
   fWeightMatrix0to1[6][2] = -4.54737464361556;
   fWeightMatrix0to1[7][2] = 0.669309044216192;
   fWeightMatrix0to1[8][2] = 0.025774140788548;
   fWeightMatrix0to1[9][2] = 1.28114024511647;
   fWeightMatrix0to1[10][2] = -1.11123712423181;
   fWeightMatrix0to1[0][3] = -0.0973003836113914;
   fWeightMatrix0to1[1][3] = 0.188889536986368;
   fWeightMatrix0to1[2][3] = -0.21926519636073;
   fWeightMatrix0to1[3][3] = -1.55091969449351;
   fWeightMatrix0to1[4][3] = 1.71862842814566;
   fWeightMatrix0to1[5][3] = -1.34044822978525;
   fWeightMatrix0to1[6][3] = 1.59653424867486;
   fWeightMatrix0to1[7][3] = 1.20218829141278;
   fWeightMatrix0to1[8][3] = 0.916539118195337;
   fWeightMatrix0to1[9][3] = 1.76436085026545;
   fWeightMatrix0to1[10][3] = 1.36131135811377;
   fWeightMatrix0to1[0][4] = -0.583928877602891;
   fWeightMatrix0to1[1][4] = -1.72735372532566;
   fWeightMatrix0to1[2][4] = 0.928046049586782;
   fWeightMatrix0to1[3][4] = -0.147341489514585;
   fWeightMatrix0to1[4][4] = 1.46285522919592;
   fWeightMatrix0to1[5][4] = 1.23660090708923;
   fWeightMatrix0to1[6][4] = 2.51387914499112;
   fWeightMatrix0to1[7][4] = 1.27014154243861;
   fWeightMatrix0to1[8][4] = -1.51181318931053;
   fWeightMatrix0to1[9][4] = 1.1441860461272;
   fWeightMatrix0to1[10][4] = -1.54641579229252;
   fWeightMatrix0to1[0][5] = -0.53523313966504;
   fWeightMatrix0to1[1][5] = -1.45102663105802;
   fWeightMatrix0to1[2][5] = -1.48759799626429;
   fWeightMatrix0to1[3][5] = 1.06882812349251;
   fWeightMatrix0to1[4][5] = 0.611932769412761;
   fWeightMatrix0to1[5][5] = -2.01028749091417;
   fWeightMatrix0to1[6][5] = 1.96972249904088;
   fWeightMatrix0to1[7][5] = -0.340745291847394;
   fWeightMatrix0to1[8][5] = 0.973302094729128;
   fWeightMatrix0to1[9][5] = 1.54316220205815;
   fWeightMatrix0to1[10][5] = 0.0050915839132389;
   fWeightMatrix0to1[0][6] = -0.207959422886973;
   fWeightMatrix0to1[1][6] = -1.08817915220714;
   fWeightMatrix0to1[2][6] = 0.61798068660957;
   fWeightMatrix0to1[3][6] = -0.598336763069256;
   fWeightMatrix0to1[4][6] = -0.56917928549494;
   fWeightMatrix0to1[5][6] = -1.15472783437725;
   fWeightMatrix0to1[6][6] = -0.205679433050251;
   fWeightMatrix0to1[7][6] = 1.23415537440582;
   fWeightMatrix0to1[8][6] = 1.05519603752392;
   fWeightMatrix0to1[9][6] = -0.057183073165836;
   fWeightMatrix0to1[10][6] = -2.00605791373387;
   fWeightMatrix0to1[0][7] = -1.33733475653688;
   fWeightMatrix0to1[1][7] = 0.833130898450584;
   fWeightMatrix0to1[2][7] = 0.830364979065436;
   fWeightMatrix0to1[3][7] = 1.51403319639056;
   fWeightMatrix0to1[4][7] = 0.460587668397255;
   fWeightMatrix0to1[5][7] = 0.510237251807838;
   fWeightMatrix0to1[6][7] = 1.05373228961075;
   fWeightMatrix0to1[7][7] = -0.911939345473591;
   fWeightMatrix0to1[8][7] = 0.12825007140148;
   fWeightMatrix0to1[9][7] = 0.700481114263731;
   fWeightMatrix0to1[10][7] = -0.778628310659998;
   fWeightMatrix0to1[0][8] = -1.81916477155146;
   fWeightMatrix0to1[1][8] = -1.61245886788078;
   fWeightMatrix0to1[2][8] = -0.382382110330761;
   fWeightMatrix0to1[3][8] = 0.146404137806356;
   fWeightMatrix0to1[4][8] = 1.70981462973275;
   fWeightMatrix0to1[5][8] = -1.3471241129534;
   fWeightMatrix0to1[6][8] = -1.83892156301799;
   fWeightMatrix0to1[7][8] = 1.63317903776841;
   fWeightMatrix0to1[8][8] = -1.02076252550517;
   fWeightMatrix0to1[9][8] = -1.29884378447634;
   fWeightMatrix0to1[10][8] = -1.73371703354465;
   fWeightMatrix0to1[0][9] = 0.0798619944116438;
   fWeightMatrix0to1[1][9] = -1.91375913212194;
   fWeightMatrix0to1[2][9] = -1.70463902921394;
   fWeightMatrix0to1[3][9] = 0.766669516576324;
   fWeightMatrix0to1[4][9] = 1.65784413808508;
   fWeightMatrix0to1[5][9] = -1.14770050711378;
   fWeightMatrix0to1[6][9] = 1.51824181362272;
   fWeightMatrix0to1[7][9] = -0.926476030239993;
   fWeightMatrix0to1[8][9] = -0.840343335171237;
   fWeightMatrix0to1[9][9] = -0.0320549840116316;
   fWeightMatrix0to1[10][9] = 0.300992507545757;
   fWeightMatrix0to1[0][10] = -1.84182898134069;
   fWeightMatrix0to1[1][10] = 0.282811961203607;
   fWeightMatrix0to1[2][10] = 0.279330538162128;
   fWeightMatrix0to1[3][10] = 0.484198830627899;
   fWeightMatrix0to1[4][10] = -1.38135667169226;
   fWeightMatrix0to1[5][10] = 1.89493559514025;
   fWeightMatrix0to1[6][10] = 0.187455905794852;
   fWeightMatrix0to1[7][10] = -0.960523094921252;
   fWeightMatrix0to1[8][10] = 0.776988753028679;
   fWeightMatrix0to1[9][10] = -1.01518716165742;
   fWeightMatrix0to1[10][10] = -1.61641149143257;
   fWeightMatrix0to1[0][11] = -0.180771177076637;
   fWeightMatrix0to1[1][11] = -0.940144521879079;
   fWeightMatrix0to1[2][11] = 0.463476903170134;
   fWeightMatrix0to1[3][11] = 0.206885453567482;
   fWeightMatrix0to1[4][11] = 0.730341635137779;
   fWeightMatrix0to1[5][11] = 0.327862104704837;
   fWeightMatrix0to1[6][11] = 0.492598050631414;
   fWeightMatrix0to1[7][11] = -2.6200642377487;
   fWeightMatrix0to1[8][11] = 0.694381906903971;
   fWeightMatrix0to1[9][11] = 0.552138818876672;
   fWeightMatrix0to1[10][11] = -1.4186373766512;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0122904516071411;
   fWeightMatrix1to2[1][0] = -1.65106426043311;
   fWeightMatrix1to2[2][0] = -0.323598648100521;
   fWeightMatrix1to2[3][0] = 0.706820663956527;
   fWeightMatrix1to2[4][0] = 1.25999100047848;
   fWeightMatrix1to2[5][0] = -3.20387319554475;
   fWeightMatrix1to2[6][0] = -0.0877058924852241;
   fWeightMatrix1to2[7][0] = 1.04469802756916;
   fWeightMatrix1to2[8][0] = 1.62046261567641;
   fWeightMatrix1to2[9][0] = 0.054994803163173;
   fWeightMatrix1to2[10][0] = -2.01134252807531;
   fWeightMatrix1to2[0][1] = -0.781723668223499;
   fWeightMatrix1to2[1][1] = -1.35587858898757;
   fWeightMatrix1to2[2][1] = 1.48365775369584;
   fWeightMatrix1to2[3][1] = 0.913004979520009;
   fWeightMatrix1to2[4][1] = -0.562366804513012;
   fWeightMatrix1to2[5][1] = 1.3871729101406;
   fWeightMatrix1to2[6][1] = -0.778688543982124;
   fWeightMatrix1to2[7][1] = -1.6147261067074;
   fWeightMatrix1to2[8][1] = 0.117259577808852;
   fWeightMatrix1to2[9][1] = 0.761844488427108;
   fWeightMatrix1to2[10][1] = -1.16795304742197;
   fWeightMatrix1to2[0][2] = -1.60477182147611;
   fWeightMatrix1to2[1][2] = -0.160962111540821;
   fWeightMatrix1to2[2][2] = 0.680810996574019;
   fWeightMatrix1to2[3][2] = 0.00310861852701298;
   fWeightMatrix1to2[4][2] = 0.764836631231953;
   fWeightMatrix1to2[5][2] = -1.6349388035283;
   fWeightMatrix1to2[6][2] = 0.0737932466949449;
   fWeightMatrix1to2[7][2] = -0.00660894827343608;
   fWeightMatrix1to2[8][2] = -0.445746708271906;
   fWeightMatrix1to2[9][2] = -0.696682572061816;
   fWeightMatrix1to2[10][2] = -0.153819606018571;
   fWeightMatrix1to2[0][3] = -1.43238851705551;
   fWeightMatrix1to2[1][3] = -0.718886425599723;
   fWeightMatrix1to2[2][3] = 0.640828707241262;
   fWeightMatrix1to2[3][3] = -1.39162834546309;
   fWeightMatrix1to2[4][3] = -1.22175678760246;
   fWeightMatrix1to2[5][3] = 2.69839620731293;
   fWeightMatrix1to2[6][3] = -0.264734628616301;
   fWeightMatrix1to2[7][3] = -0.87629392063305;
   fWeightMatrix1to2[8][3] = 0.745936264264958;
   fWeightMatrix1to2[9][3] = 0.608459681574571;
   fWeightMatrix1to2[10][3] = -2.68699999098838;
   fWeightMatrix1to2[0][4] = -0.140219406312202;
   fWeightMatrix1to2[1][4] = -0.611409467177625;
   fWeightMatrix1to2[2][4] = 0.396283400206415;
   fWeightMatrix1to2[3][4] = -2.14820390892995;
   fWeightMatrix1to2[4][4] = -1.74229037817431;
   fWeightMatrix1to2[5][4] = 1.96533234336212;
   fWeightMatrix1to2[6][4] = 0.923719187245205;
   fWeightMatrix1to2[7][4] = -2.28162816622619;
   fWeightMatrix1to2[8][4] = -1.47763945109308;
   fWeightMatrix1to2[9][4] = -1.62481320941779;
   fWeightMatrix1to2[10][4] = -0.0697310020974985;
   fWeightMatrix1to2[0][5] = 1.25205984440121;
   fWeightMatrix1to2[1][5] = -0.862175648972021;
   fWeightMatrix1to2[2][5] = -0.12317997054177;
   fWeightMatrix1to2[3][5] = -1.30896734006155;
   fWeightMatrix1to2[4][5] = 1.02820085591944;
   fWeightMatrix1to2[5][5] = 2.78072803573736;
   fWeightMatrix1to2[6][5] = 0.276112769024444;
   fWeightMatrix1to2[7][5] = -0.305936744229386;
   fWeightMatrix1to2[8][5] = -2.19261591057103;
   fWeightMatrix1to2[9][5] = -3.00587559458883;
   fWeightMatrix1to2[10][5] = 0.493611005970629;
   fWeightMatrix1to2[0][6] = 0.134496457998113;
   fWeightMatrix1to2[1][6] = -2.68622161411039;
   fWeightMatrix1to2[2][6] = -1.9368100919255;
   fWeightMatrix1to2[3][6] = 0.241444787738319;
   fWeightMatrix1to2[4][6] = 1.5854283984288;
   fWeightMatrix1to2[5][6] = -9.0753152149381;
   fWeightMatrix1to2[6][6] = 0.59942405807282;
   fWeightMatrix1to2[7][6] = 0.435114867992051;
   fWeightMatrix1to2[8][6] = -0.462887941865966;
   fWeightMatrix1to2[9][6] = -0.598336987593284;
   fWeightMatrix1to2[10][6] = 0.834045046567293;
   fWeightMatrix1to2[0][7] = 0.971561414576981;
   fWeightMatrix1to2[1][7] = 0.412893542572916;
   fWeightMatrix1to2[2][7] = -0.852696060607042;
   fWeightMatrix1to2[3][7] = -1.90224210921709;
   fWeightMatrix1to2[4][7] = -1.1732451136063;
   fWeightMatrix1to2[5][7] = 1.88695531751176;
   fWeightMatrix1to2[6][7] = 0.94476599929286;
   fWeightMatrix1to2[7][7] = 1.03207199467965;
   fWeightMatrix1to2[8][7] = 1.12141418451645;
   fWeightMatrix1to2[9][7] = 2.17106084640135;
   fWeightMatrix1to2[10][7] = -1.96765311374927;
   fWeightMatrix1to2[0][8] = -2.14644075966793;
   fWeightMatrix1to2[1][8] = -0.920448785086603;
   fWeightMatrix1to2[2][8] = -2.11102930884421;
   fWeightMatrix1to2[3][8] = 0.469147060750048;
   fWeightMatrix1to2[4][8] = 1.672035971333;
   fWeightMatrix1to2[5][8] = -2.69402076780754;
   fWeightMatrix1to2[6][8] = -0.237541882135893;
   fWeightMatrix1to2[7][8] = -0.727093205480399;
   fWeightMatrix1to2[8][8] = -2.29121083892687;
   fWeightMatrix1to2[9][8] = -1.79874777183498;
   fWeightMatrix1to2[10][8] = 0.204828311137981;
   fWeightMatrix1to2[0][9] = -0.773769928019062;
   fWeightMatrix1to2[1][9] = 0.634828406569591;
   fWeightMatrix1to2[2][9] = -1.10446337524976;
   fWeightMatrix1to2[3][9] = 1.21686599038092;
   fWeightMatrix1to2[4][9] = -2.03632795452777;
   fWeightMatrix1to2[5][9] = 2.67120813609148;
   fWeightMatrix1to2[6][9] = -0.934470188145856;
   fWeightMatrix1to2[7][9] = -2.04180915262625;
   fWeightMatrix1to2[8][9] = -2.64994110549608;
   fWeightMatrix1to2[9][9] = -3.08140518672961;
   fWeightMatrix1to2[10][9] = -0.80876676672817;
   fWeightMatrix1to2[0][10] = -2.18764624667178;
   fWeightMatrix1to2[1][10] = -1.81633272009526;
   fWeightMatrix1to2[2][10] = -1.82683018874446;
   fWeightMatrix1to2[3][10] = -0.184918493304163;
   fWeightMatrix1to2[4][10] = -2.0959789396092;
   fWeightMatrix1to2[5][10] = -0.524016476682033;
   fWeightMatrix1to2[6][10] = 1.44053217639775;
   fWeightMatrix1to2[7][10] = -0.889607183538578;
   fWeightMatrix1to2[8][10] = -0.120763405458868;
   fWeightMatrix1to2[9][10] = -1.28563846484922;
   fWeightMatrix1to2[10][10] = 0.092291115725504;
   fWeightMatrix1to2[0][11] = 0.593343876611095;
   fWeightMatrix1to2[1][11] = 0.733923234740303;
   fWeightMatrix1to2[2][11] = -1.36191711531431;
   fWeightMatrix1to2[3][11] = -2.21279193285743;
   fWeightMatrix1to2[4][11] = -1.38421110805248;
   fWeightMatrix1to2[5][11] = -0.0138389991568283;
   fWeightMatrix1to2[6][11] = -3.32041669508325;
   fWeightMatrix1to2[7][11] = -0.57221764046391;
   fWeightMatrix1to2[8][11] = -0.976842395992499;
   fWeightMatrix1to2[9][11] = 0.260065333512435;
   fWeightMatrix1to2[10][11] = -1.61019183385481;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.46590774543663;
   fWeightMatrix2to3[0][1] = -0.759854552310554;
   fWeightMatrix2to3[0][2] = -1.14006505500002;
   fWeightMatrix2to3[0][3] = -0.154363021978904;
   fWeightMatrix2to3[0][4] = -0.861166112562837;
   fWeightMatrix2to3[0][5] = -2.88225812551424;
   fWeightMatrix2to3[0][6] = 0.730773889361068;
   fWeightMatrix2to3[0][7] = 0.207384734176976;
   fWeightMatrix2to3[0][8] = 1.25888547018451;
   fWeightMatrix2to3[0][9] = 1.2063983528136;
   fWeightMatrix2to3[0][10] = 0.530443116726613;
   fWeightMatrix2to3[0][11] = 0.401927705718105;
}

inline double ReadkMLP_pca_ce_600_n2_no_ev::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadkMLP_pca_ce_600_n2_no_ev::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_pca_ce_600_n2_no_ev::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_pca_ce_600_n2_no_ev::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_pca_ce_600_n2_no_ev::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.00020475036581;
   fMax_1[0][0] = 520.089416504;
   fMin_1[1][0] = 4.45244913863e-05;
   fMax_1[1][0] = 591.79876709;
   fMin_1[2][0] = 4.45244913863e-05;
   fMax_1[2][0] = 591.79876709;
   fMin_1[0][1] = 6.05733257544e-05;
   fMax_1[0][1] = 447.772735596;
   fMin_1[1][1] = 2.60141878243e-05;
   fMax_1[1][1] = 680.619262695;
   fMin_1[2][1] = 2.60141878243e-05;
   fMax_1[2][1] = 680.619262695;
   fMin_1[0][2] = -7820.53808594;
   fMax_1[0][2] = 62832.4140625;
   fMin_1[1][2] = -27109.4433594;
   fMax_1[1][2] = 117643.984375;
   fMin_1[2][2] = -27109.4433594;
   fMax_1[2][2] = 117643.984375;
   fMin_1[0][3] = -4486.09814453;
   fMax_1[0][3] = 336199.4375;
   fMin_1[1][3] = -30494.9765625;
   fMax_1[1][3] = 233789.203125;
   fMin_1[2][3] = -30494.9765625;
   fMax_1[2][3] = 336199.4375;
   fMin_1[0][4] = -848390.4375;
   fMax_1[0][4] = 21884.8886719;
   fMin_1[1][4] = -129755.617188;
   fMax_1[1][4] = 742903.3125;
   fMin_1[2][4] = -848390.4375;
   fMax_1[2][4] = 742903.3125;
   fMin_1[0][5] = -1816.70861816;
   fMax_1[0][5] = 876.452758789;
   fMin_1[1][5] = -4408.59033203;
   fMax_1[1][5] = 5815.69433594;
   fMin_1[2][5] = -4408.59033203;
   fMax_1[2][5] = 5815.69433594;
   fMin_1[0][6] = -667.623535156;
   fMax_1[0][6] = 2655.89135742;
   fMin_1[1][6] = -10921.9150391;
   fMax_1[1][6] = 10528.8847656;
   fMin_1[2][6] = -10921.9150391;
   fMax_1[2][6] = 10528.8847656;
   fMin_1[0][7] = -6113.18701172;
   fMax_1[0][7] = 4820.41601562;
   fMin_1[1][7] = -36484.0898438;
   fMax_1[1][7] = 32938.125;
   fMin_1[2][7] = -36484.0898438;
   fMax_1[2][7] = 32938.125;
   fMin_1[0][8] = 0.0162057429552;
   fMax_1[0][8] = 179.977890015;
   fMin_1[1][8] = 0.0153690213338;
   fMax_1[1][8] = 179.980255127;
   fMin_1[2][8] = 0.0153690213338;
   fMax_1[2][8] = 179.980255127;
   fMin_1[0][9] = 0.0196817759424;
   fMax_1[0][9] = 3842.51171875;
   fMin_1[1][9] = 0.0131534170359;
   fMax_1[1][9] = 76398.515625;
   fMin_1[2][9] = 0.0131534170359;
   fMax_1[2][9] = 76398.515625;
   fMin_1[0][10] = 0.263680070639;
   fMax_1[0][10] = 914557.375;
   fMin_1[1][10] = 0.0941462889314;
   fMax_1[1][10] = 752596.375;
   fMin_1[2][10] = 0.0941462889314;
   fMax_1[2][10] = 914557.375;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::X2P_2( const double* x, double* p, int index ) const
{
   // Calculate the principal components from the original data vector
   // x, and return it in p (function extracted from TPrincipal::X2P)
   // It's the users responsibility to make sure that both x and p are
   // of the right size (i.e., memory must be allocated for p).
   const int nVar = 11;

   for (int i = 0; i < nVar; i++) {
      p[i] = 0;
      for (int j = 0; j < nVar; j++) p[i] += (x[j] - fMeanValues_2[index][j]) * fEigenVectors_2[index][j][i];
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::InitTransform_2()
{
   // PCA transformation, initialisation
   // initialise vector of mean values
   fMeanValues_2[0][0] = -0.955631178092;
   fMeanValues_2[0][1] = -0.960562362655;
   fMeanValues_2[0][2] = -0.625429721055;
   fMeanValues_2[0][3] = -0.833646823028;
   fMeanValues_2[0][4] = 0.0662344895832;
   fMeanValues_2[0][5] = -0.137688739778;
   fMeanValues_2[0][6] = 0.0183553754278;
   fMeanValues_2[0][7] = 0.0503883368015;
   fMeanValues_2[0][8] = -0.058544710889;
   fMeanValues_2[0][9] = -0.99923571065;
   fMeanValues_2[0][10] = -0.999816184737;
   fMeanValues_2[1][0] = -0.960047413504;
   fMeanValues_2[1][1] = -0.965126158216;
   fMeanValues_2[1][2] = -0.625437107469;
   fMeanValues_2[1][3] = -0.833682760356;
   fMeanValues_2[1][4] = 0.066254497838;
   fMeanValues_2[1][5] = -0.137689963785;
   fMeanValues_2[1][6] = 0.0183274331275;
   fMeanValues_2[1][7] = 0.0501719019501;
   fMeanValues_2[1][8] = -0.0264143476865;
   fMeanValues_2[1][9] = -0.999302976516;
   fMeanValues_2[1][10] = -0.999889302607;
   fMeanValues_2[2][0] = -0.959558700269;
   fMeanValues_2[2][1] = -0.964621115552;
   fMeanValues_2[2][2] = -0.625436290067;
   fMeanValues_2[2][3] = -0.833678783429;
   fMeanValues_2[2][4] = 0.0662522836673;
   fMeanValues_2[2][5] = -0.137689828333;
   fMeanValues_2[2][6] = 0.0183305253023;
   fMeanValues_2[2][7] = 0.0501958532495;
   fMeanValues_2[2][8] = -0.0299699855308;
   fMeanValues_2[2][9] = -0.999295532683;
   fMeanValues_2[2][10] = -0.999881211174;

   // initialise matrix of eigenvectors
   fEigenVectors_2[0][0][0] = -0.00124548751491;
   fEigenVectors_2[0][0][1] = 0.972066211403;
   fEigenVectors_2[0][0][2] = -0.234625407714;
   fEigenVectors_2[0][0][3] = 0.000432365142958;
   fEigenVectors_2[0][0][4] = 0.00210035113886;
   fEigenVectors_2[0][0][5] = -0.00225641633836;
   fEigenVectors_2[0][0][6] = -0.00274537684688;
   fEigenVectors_2[0][0][7] = -0.00439793701113;
   fEigenVectors_2[0][0][8] = 0.000190350302269;
   fEigenVectors_2[0][0][9] = 0.000201307884843;
   fEigenVectors_2[0][0][10] = 4.39665972435e-05;
   fEigenVectors_2[0][1][0] = -0.00324131085559;
   fEigenVectors_2[0][1][1] = 0.234565103413;
   fEigenVectors_2[0][1][2] = 0.972048758192;
   fEigenVectors_2[0][1][3] = 0.00349042993415;
   fEigenVectors_2[0][1][4] = 0.00193762385968;
   fEigenVectors_2[0][1][5] = -0.00139139092605;
   fEigenVectors_2[0][1][6] = -0.00205631043734;
   fEigenVectors_2[0][1][7] = -0.0082273492638;
   fEigenVectors_2[0][1][8] = -0.000352870157756;
   fEigenVectors_2[0][1][9] = 3.14742663408e-05;
   fEigenVectors_2[0][1][10] = 3.4780858864e-05;
   fEigenVectors_2[0][2][0] = 0.000112807016303;
   fEigenVectors_2[0][2][1] = 4.47462082388e-05;
   fEigenVectors_2[0][2][2] = 0.00108260392193;
   fEigenVectors_2[0][2][3] = -0.287874540571;
   fEigenVectors_2[0][2][4] = -0.0205690262582;
   fEigenVectors_2[0][2][5] = -0.042871072691;
   fEigenVectors_2[0][2][6] = 0.0136475438522;
   fEigenVectors_2[0][2][7] = -0.0340065759678;
   fEigenVectors_2[0][2][8] = 0.940519778376;
   fEigenVectors_2[0][2][9] = -0.0801411217939;
   fEigenVectors_2[0][2][10] = 0.150077622701;
   fEigenVectors_2[0][3][0] = 0.000106930658603;
   fEigenVectors_2[0][3][1] = 0.000203809481941;
   fEigenVectors_2[0][3][2] = 0.00149113448797;
   fEigenVectors_2[0][3][3] = -0.601949882274;
   fEigenVectors_2[0][3][4] = 0.0115824529268;
   fEigenVectors_2[0][3][5] = -0.00166065891462;
   fEigenVectors_2[0][3][6] = -0.00937375811389;
   fEigenVectors_2[0][3][7] = -0.0555718572058;
   fEigenVectors_2[0][3][8] = -0.193284856367;
   fEigenVectors_2[0][3][9] = 0.66149779391;
   fEigenVectors_2[0][3][10] = 0.399252659438;
   fEigenVectors_2[0][4][0] = -0.000132963805879;
   fEigenVectors_2[0][4][1] = -7.86854111227e-05;
   fEigenVectors_2[0][4][2] = -0.000904220975404;
   fEigenVectors_2[0][4][3] = 0.350321496706;
   fEigenVectors_2[0][4][4] = -0.00280007904874;
   fEigenVectors_2[0][4][5] = 0.012283621877;
   fEigenVectors_2[0][4][6] = 0.0299119956073;
   fEigenVectors_2[0][4][7] = 0.0346841025262;
   fEigenVectors_2[0][4][8] = -0.0558504754512;
   fEigenVectors_2[0][4][9] = -0.238927671054;
   fEigenVectors_2[0][4][10] = 0.90266929581;
   fEigenVectors_2[0][5][0] = -0.000150350544091;
   fEigenVectors_2[0][5][1] = -0.00215647232069;
   fEigenVectors_2[0][5][2] = -0.00127336927959;
   fEigenVectors_2[0][5][3] = 0.00249422790541;
   fEigenVectors_2[0][5][4] = 0.995345651209;
   fEigenVectors_2[0][5][5] = 0.0795956954302;
   fEigenVectors_2[0][5][6] = 0.0475813805935;
   fEigenVectors_2[0][5][7] = -0.0028474526824;
   fEigenVectors_2[0][5][8] = 0.0248977936456;
   fEigenVectors_2[0][5][9] = -0.00682357274465;
   fEigenVectors_2[0][5][10] = -0.000698017642293;
   fEigenVectors_2[0][6][0] = 0.000109431448307;
   fEigenVectors_2[0][6][1] = 0.000859107843496;
   fEigenVectors_2[0][6][2] = 0.000204957251734;
   fEigenVectors_2[0][6][3] = -0.00181763278097;
   fEigenVectors_2[0][6][4] = -0.0483862833447;
   fEigenVectors_2[0][6][5] = 0.876645408239;
   fEigenVectors_2[0][6][6] = -0.476513455166;
   fEigenVectors_2[0][6][7] = 0.00547855850608;
   fEigenVectors_2[0][6][8] = 0.0444914489321;
   fEigenVectors_2[0][6][9] = 0.0033637248372;
   fEigenVectors_2[0][6][10] = 0.00784912284359;
   fEigenVectors_2[0][7][0] = 0.0010476137372;
   fEigenVectors_2[0][7][1] = 0.0038465830385;
   fEigenVectors_2[0][7][2] = 0.00135819330933;
   fEigenVectors_2[0][7][3] = 0.00203914108195;
   fEigenVectors_2[0][7][4] = -0.0798229515813;
   fEigenVectors_2[0][7][5] = 0.471472385068;
   fEigenVectors_2[0][7][6] = 0.875925949159;
   fEigenVectors_2[0][7][7] = -0.0474012511197;
   fEigenVectors_2[0][7][8] = 0.0127196774019;
   fEigenVectors_2[0][7][9] = 0.0319222261034;
   fEigenVectors_2[0][7][10] = -0.025420942299;
   fEigenVectors_2[0][8][0] = -0.999993343511;
   fEigenVectors_2[0][8][1] = -0.00196805076002;
   fEigenVectors_2[0][8][2] = -0.00285808259214;
   fEigenVectors_2[0][8][3] = -0.000218593031116;
   fEigenVectors_2[0][8][4] = -0.000247938999078;
   fEigenVectors_2[0][8][5] = 0.000577478749069;
   fEigenVectors_2[0][8][6] = 0.00085608666149;
   fEigenVectors_2[0][8][7] = -0.000288793701447;
   fEigenVectors_2[0][8][8] = 6.96967863304e-05;
   fEigenVectors_2[0][8][9] = 3.13595067431e-05;
   fEigenVectors_2[0][8][10] = -7.87857916008e-05;
   fEigenVectors_2[0][9][0] = -0.000267510176352;
   fEigenVectors_2[0][9][1] = 0.00631219937576;
   fEigenVectors_2[0][9][2] = 0.00702078944386;
   fEigenVectors_2[0][9][3] = -0.00465760119175;
   fEigenVectors_2[0][9][4] = -0.0006679697213;
   fEigenVectors_2[0][9][5] = 0.01386202279;
   fEigenVectors_2[0][9][6] = 0.0417011496323;
   fEigenVectors_2[0][9][7] = 0.993100436406;
   fEigenVectors_2[0][9][8] = 0.044322377719;
   fEigenVectors_2[0][9][9] = 0.0982888412533;
   fEigenVectors_2[0][9][10] = -0.00915782905;
   fEigenVectors_2[0][10][0] = 0.000100606956675;
   fEigenVectors_2[0][10][1] = 0.00159419344138;
   fEigenVectors_2[0][10][2] = 0.00263596982959;
   fEigenVectors_2[0][10][3] = -0.657275926028;
   fEigenVectors_2[0][10][4] = 0.000588715692572;
   fEigenVectors_2[0][10][5] = 0.0260778264391;
   fEigenVectors_2[0][10][6] = 0.022457433268;
   fEigenVectors_2[0][10][7] = 0.0770178031015;
   fEigenVectors_2[0][10][8] = -0.264987579048;
   fEigenVectors_2[0][10][9] = -0.698694492702;
   fEigenVectors_2[0][10][10] = 0.049698773126;
   fEigenVectors_2[1][0][0] = 0.00032241293771;
   fEigenVectors_2[1][0][1] = 0.971571408917;
   fEigenVectors_2[1][0][2] = 0.236663383929;
   fEigenVectors_2[1][0][3] = 0.00214737749669;
   fEigenVectors_2[1][0][4] = -0.00312328992915;
   fEigenVectors_2[1][0][5] = 0.00474941708482;
   fEigenVectors_2[1][0][6] = 0.000650487041638;
   fEigenVectors_2[1][0][7] = 0.00122876718287;
   fEigenVectors_2[1][0][8] = -0.000594887278687;
   fEigenVectors_2[1][0][9] = -0.000349718535171;
   fEigenVectors_2[1][0][10] = -6.1673078362e-05;
   fEigenVectors_2[1][1][0] = 0.00315749321481;
   fEigenVectors_2[1][1][1] = 0.236606986372;
   fEigenVectors_2[1][1][2] = -0.971555603909;
   fEigenVectors_2[1][1][3] = 0.000718619023197;
   fEigenVectors_2[1][1][4] = -0.00133579128776;
   fEigenVectors_2[1][1][5] = 0.00905329802753;
   fEigenVectors_2[1][1][6] = -0.00020298587431;
   fEigenVectors_2[1][1][7] = 0.000393044599391;
   fEigenVectors_2[1][1][8] = -0.00153836265604;
   fEigenVectors_2[1][1][9] = -0.000182805908062;
   fEigenVectors_2[1][1][10] = 0.000118859086583;
   fEigenVectors_2[1][2][0] = -2.66444597084e-05;
   fEigenVectors_2[1][2][1] = 1.39100732648e-05;
   fEigenVectors_2[1][2][2] = 5.86791506338e-05;
   fEigenVectors_2[1][2][3] = 0.171255340031;
   fEigenVectors_2[1][2][4] = 0.43561713026;
   fEigenVectors_2[1][2][5] = 0.172461048142;
   fEigenVectors_2[1][2][6] = 0.467806881279;
   fEigenVectors_2[1][2][7] = 0.123816745359;
   fEigenVectors_2[1][2][8] = 0.670179892688;
   fEigenVectors_2[1][2][9] = -0.232543900357;
   fEigenVectors_2[1][2][10] = -0.117366469242;
   fEigenVectors_2[1][3][0] = 9.31672040827e-06;
   fEigenVectors_2[1][3][1] = -5.2118779653e-05;
   fEigenVectors_2[1][3][2] = 0.00019213527661;
   fEigenVectors_2[1][3][3] = 0.152938575828;
   fEigenVectors_2[1][3][4] = 0.256671926929;
   fEigenVectors_2[1][3][5] = -0.0577640376257;
   fEigenVectors_2[1][3][6] = 0.227440327393;
   fEigenVectors_2[1][3][7] = 0.0685567050258;
   fEigenVectors_2[1][3][8] = -0.525998610038;
   fEigenVectors_2[1][3][9] = -0.659582765031;
   fEigenVectors_2[1][3][10] = 0.373148099516;
   fEigenVectors_2[1][4][0] = 6.52523037421e-05;
   fEigenVectors_2[1][4][1] = 0.000198333025668;
   fEigenVectors_2[1][4][2] = -6.84533086083e-05;
   fEigenVectors_2[1][4][3] = 0.109203912194;
   fEigenVectors_2[1][4][4] = 0.197460982586;
   fEigenVectors_2[1][4][5] = -0.0481641869648;
   fEigenVectors_2[1][4][6] = 0.149788235515;
   fEigenVectors_2[1][4][7] = 0.031469950342;
   fEigenVectors_2[1][4][8] = -0.408341602898;
   fEigenVectors_2[1][4][9] = -0.00513776477813;
   fEigenVectors_2[1][4][10] = -0.869808998674;
   fEigenVectors_2[1][5][0] = 0.000166498311363;
   fEigenVectors_2[1][5][1] = -0.00282693309107;
   fEigenVectors_2[1][5][2] = 0.000327049772095;
   fEigenVectors_2[1][5][3] = 0.934561168027;
   fEigenVectors_2[1][5][4] = -0.298661547;
   fEigenVectors_2[1][5][5] = 0.00470644263156;
   fEigenVectors_2[1][5][6] = -0.094396484607;
   fEigenVectors_2[1][5][7] = -0.15975522003;
   fEigenVectors_2[1][5][8] = 0.0532505518726;
   fEigenVectors_2[1][5][9] = 0.00967628321731;
   fEigenVectors_2[1][5][10] = 0.00217907280905;
   fEigenVectors_2[1][6][0] = -4.3190293195e-05;
   fEigenVectors_2[1][6][1] = 0.0007058410765;
   fEigenVectors_2[1][6][2] = 7.05555359048e-06;
   fEigenVectors_2[1][6][3] = 0.166899698559;
   fEigenVectors_2[1][6][4] = 0.419139365379;
   fEigenVectors_2[1][6][5] = -0.00293676774225;
   fEigenVectors_2[1][6][6] = -0.661612590123;
   fEigenVectors_2[1][6][7] = 0.597521618141;
   fEigenVectors_2[1][6][8] = 0.0403025666849;
   fEigenVectors_2[1][6][9] = 0.00671121929186;
   fEigenVectors_2[1][6][10] = 0.00499173096344;
   fEigenVectors_2[1][7][0] = -0.000784549970505;
   fEigenVectors_2[1][7][1] = 0.00309347392569;
   fEigenVectors_2[1][7][2] = -0.000377250054355;
   fEigenVectors_2[1][7][3] = 0.00543889314825;
   fEigenVectors_2[1][7][4] = 0.541557667908;
   fEigenVectors_2[1][7][5] = -0.0104999458449;
   fEigenVectors_2[1][7][6] = -0.344672074982;
   fEigenVectors_2[1][7][7] = -0.765592215055;
   fEigenVectors_2[1][7][8] = 0.0345730671332;
   fEigenVectors_2[1][7][9] = -0.00123367784393;
   fEigenVectors_2[1][7][10] = 0.0209293223642;
   fEigenVectors_2[1][8][0] = 0.999994606341;
   fEigenVectors_2[1][8][1] = -0.00105913956291;
   fEigenVectors_2[1][8][2] = 0.00299301230285;
   fEigenVectors_2[1][8][3] = -0.000155574910639;
   fEigenVectors_2[1][8][4] = 0.000484325901734;
   fEigenVectors_2[1][8][5] = 0.000216294993185;
   fEigenVectors_2[1][8][6] = -0.000298136361642;
   fEigenVectors_2[1][8][7] = -0.000554520096001;
   fEigenVectors_2[1][8][8] = 3.13727496898e-05;
   fEigenVectors_2[1][8][9] = 8.92853045558e-07;
   fEigenVectors_2[1][8][10] = 6.68445479484e-05;
   fEigenVectors_2[1][9][0] = 0.000250880120752;
   fEigenVectors_2[1][9][1] = 0.00674261101053;
   fEigenVectors_2[1][9][2] = -0.00777117784469;
   fEigenVectors_2[1][9][3] = 0.00190737014994;
   fEigenVectors_2[1][9][4] = 0.00632243393631;
   fEigenVectors_2[1][9][5] = -0.977455933056;
   fEigenVectors_2[1][9][6] = 0.030692250821;
   fEigenVectors_2[1][9][7] = 0.0121732936854;
   fEigenVectors_2[1][9][8] = 0.193712301486;
   fEigenVectors_2[1][9][9] = -0.0705332741431;
   fEigenVectors_2[1][9][10] = -0.0289960153198;
   fEigenVectors_2[1][10][0] = 2.17785669182e-05;
   fEigenVectors_2[1][10][1] = 0.00120216744707;
   fEigenVectors_2[1][10][2] = -0.000712402950174;
   fEigenVectors_2[1][10][3] = 0.184546602423;
   fEigenVectors_2[1][10][4] = 0.383605808284;
   fEigenVectors_2[1][10][5] = -0.094525249733;
   fEigenVectors_2[1][10][6] = 0.374977041078;
   fEigenVectors_2[1][10][7] = 0.100715534255;
   fEigenVectors_2[1][10][8] = -0.253493819863;
   fEigenVectors_2[1][10][9] = 0.711148523509;
   fEigenVectors_2[1][10][10] = 0.298512009768;
   fEigenVectors_2[2][0][0] = 0.000389372067861;
   fEigenVectors_2[2][0][1] = 0.971447590234;
   fEigenVectors_2[2][0][2] = 0.237171797666;
   fEigenVectors_2[2][0][3] = 0.00163551287592;
   fEigenVectors_2[2][0][4] = -0.00298864404236;
   fEigenVectors_2[2][0][5] = -0.00114899432185;
   fEigenVectors_2[2][0][6] = 0.00490647134824;
   fEigenVectors_2[2][0][7] = -0.00118706442018;
   fEigenVectors_2[2][0][8] = 0.000300703033577;
   fEigenVectors_2[2][0][9] = 0.000577994695923;
   fEigenVectors_2[2][0][10] = 0.000363377857948;
   fEigenVectors_2[2][1][0] = 0.00312774388488;
   fEigenVectors_2[2][1][1] = 0.237115111756;
   fEigenVectors_2[2][1][2] = -0.971432216781;
   fEigenVectors_2[2][1][3] = 0.000388739073184;
   fEigenVectors_2[2][1][4] = -0.00179007346794;
   fEigenVectors_2[2][1][5] = 0.000827567705969;
   fEigenVectors_2[2][1][6] = 0.00890183162844;
   fEigenVectors_2[2][1][7] = -0.000695539516227;
   fEigenVectors_2[2][1][8] = -0.000650848956431;
   fEigenVectors_2[2][1][9] = 0.00136268232536;
   fEigenVectors_2[2][1][10] = 0.000204835421369;
   fEigenVectors_2[2][2][0] = -3.64440451388e-05;
   fEigenVectors_2[2][2][1] = 1.74347248114e-05;
   fEigenVectors_2[2][2][2] = -7.03169643011e-05;
   fEigenVectors_2[2][2][3] = 0.241544614895;
   fEigenVectors_2[2][2][4] = 0.401063898439;
   fEigenVectors_2[2][2][5] = -0.0257503825597;
   fEigenVectors_2[2][2][6] = 0.198631502763;
   fEigenVectors_2[2][2][7] = 0.112897865047;
   fEigenVectors_2[2][2][8] = 0.601005139086;
   fEigenVectors_2[2][2][9] = -0.565110312077;
   fEigenVectors_2[2][2][10] = 0.217677779664;
   fEigenVectors_2[2][3][0] = -4.12900928917e-06;
   fEigenVectors_2[2][3][1] = -2.13180999275e-05;
   fEigenVectors_2[2][3][2] = 2.90850743421e-06;
   fEigenVectors_2[2][3][3] = 0.272033252244;
   fEigenVectors_2[2][3][4] = 0.411394688001;
   fEigenVectors_2[2][3][5] = -0.28812211906;
   fEigenVectors_2[2][3][6] = -0.00134500363304;
   fEigenVectors_2[2][3][7] = -0.0737622756106;
   fEigenVectors_2[2][3][8] = -0.256642781555;
   fEigenVectors_2[2][3][9] = 0.3913986434;
   fEigenVectors_2[2][3][10] = 0.670251345891;
   fEigenVectors_2[2][4][0] = 7.30568393954e-05;
   fEigenVectors_2[2][4][1] = 0.000166079562268;
   fEigenVectors_2[2][4][2] = 4.01888792738e-05;
   fEigenVectors_2[2][4][3] = 0.0446329160614;
   fEigenVectors_2[2][4][4] = -0.0354763460954;
   fEigenVectors_2[2][4][5] = 0.303015696125;
   fEigenVectors_2[2][4][6] = -0.0807013948757;
   fEigenVectors_2[2][4][7] = 0.161570592454;
   fEigenVectors_2[2][4][8] = 0.646647629313;
   fEigenVectors_2[2][4][9] = 0.673890416239;
   fEigenVectors_2[2][4][10] = 0.0056181814512;
   fEigenVectors_2[2][5][0] = 0.000164617951091;
   fEigenVectors_2[2][5][1] = -0.00274906275542;
   fEigenVectors_2[2][5][2] = 0.000432087405995;
   fEigenVectors_2[2][5][3] = 0.856804968831;
   fEigenVectors_2[2][5][4] = -0.490773901532;
   fEigenVectors_2[2][5][5] = 0.0549553968289;
   fEigenVectors_2[2][5][6] = -0.00946611358111;
   fEigenVectors_2[2][5][7] = 0.109526952303;
   fEigenVectors_2[2][5][8] = -0.0815754771512;
   fEigenVectors_2[2][5][9] = -0.056333329679;
   fEigenVectors_2[2][5][10] = -0.00919744988898;
   fEigenVectors_2[2][6][0] = -5.09058868663e-05;
   fEigenVectors_2[2][6][1] = 0.0007248654058;
   fEigenVectors_2[2][6][2] = -1.87358738191e-05;
   fEigenVectors_2[2][6][3] = 0.164686607205;
   fEigenVectors_2[2][6][4] = 0.208377163073;
   fEigenVectors_2[2][6][5] = 0.607730927407;
   fEigenVectors_2[2][6][6] = -0.0966490070495;
   fEigenVectors_2[2][6][7] = -0.738026942362;
   fEigenVectors_2[2][6][8] = -0.0567622254154;
   fEigenVectors_2[2][6][9] = -0.0533176585339;
   fEigenVectors_2[2][6][10] = -0.00550905215721;
   fEigenVectors_2[2][7][0] = -0.000815900146009;
   fEigenVectors_2[2][7][1] = 0.00319134228778;
   fEigenVectors_2[2][7][2] = -0.000500267663168;
   fEigenVectors_2[2][7][3] = 0.0331250198333;
   fEigenVectors_2[2][7][4] = 0.33373119129;
   fEigenVectors_2[2][7][5] = 0.588123149501;
   fEigenVectors_2[2][7][6] = -0.0954673712094;
   fEigenVectors_2[2][7][7] = 0.630874462793;
   fEigenVectors_2[2][7][8] = -0.360827967473;
   fEigenVectors_2[2][7][9] = -0.0655571087164;
   fEigenVectors_2[2][7][10] = 0.00388870573117;
   fEigenVectors_2[2][8][0] = 0.999994649945;
   fEigenVectors_2[2][8][1] = -0.00111851265344;
   fEigenVectors_2[2][8][2] = 0.00294751642832;
   fEigenVectors_2[2][8][3] = -0.000104730784576;
   fEigenVectors_2[2][8][4] = 0.000381122956135;
   fEigenVectors_2[2][8][5] = 0.000512608101755;
   fEigenVectors_2[2][8][6] = 0.000146069054933;
   fEigenVectors_2[2][8][7] = 0.000448643891397;
   fEigenVectors_2[2][8][8] = -0.000336640867898;
   fEigenVectors_2[2][8][9] = -7.88619013105e-05;
   fEigenVectors_2[2][8][10] = 1.86206092217e-06;
   fEigenVectors_2[2][9][0] = 0.000252129103952;
   fEigenVectors_2[2][9][1] = 0.00670006547991;
   fEigenVectors_2[2][9][2] = -0.00768052600197;
   fEigenVectors_2[2][9][3] = 0.00616067771188;
   fEigenVectors_2[2][9][4] = 0.017500464208;
   fEigenVectors_2[2][9][5] = -0.139264529746;
   fEigenVectors_2[2][9][6] = -0.966559594504;
   fEigenVectors_2[2][9][7] = 0.0210575893459;
   fEigenVectors_2[2][9][8] = 0.11347928411;
   fEigenVectors_2[2][9][9] = -0.167127357091;
   fEigenVectors_2[2][9][10] = 0.0683172922703;
   fEigenVectors_2[2][10][0] = 7.32562710098e-06;
   fEigenVectors_2[2][10][1] = 0.00125118968172;
   fEigenVectors_2[2][10][2] = -0.000929716907795;
   fEigenVectors_2[2][10][3] = 0.321383758782;
   fEigenVectors_2[2][10][4] = 0.522176664079;
   fEigenVectors_2[2][10][5] = -0.294722510835;
   fEigenVectors_2[2][10][6] = -0.0338460924301;
   fEigenVectors_2[2][10][7] = -0.0240856271109;
   fEigenVectors_2[2][10][8] = -0.0426924217948;
   fEigenVectors_2[2][10][9] = 0.187300406015;
   fEigenVectors_2[2][10][10] = -0.706081059375;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::Transform_2( std::vector<double>& iv, int cls ) const
{
   // PCA transformation
   const int nVar = 11;
   double *dv = new double[nVar];
   double *rv = new double[nVar];
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];

   // Perform PCA and put it into PCAed events tree
   this->X2P_2( dv, rv, cls );
   for (int ivar=0; ivar<nVar; ivar++) iv[indicesPut.at(ivar)] = rv[ivar];

   delete [] dv;
   delete [] rv;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n2_no_ev::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
