// Class: ReadRecCuts
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::RecCuts
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Mon Aug 12 21:06:29 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/nyx/hades/user/knowakow/PP/FAT/TMVA
Training events: 400568
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
FitMethod: "GA" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
EffMethod: "EffSel" [Selection Method]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
    CutRangeMin[4]: "-1.000000e+00"
    CutRangeMin[5]: "-1.000000e+00"
    CutRangeMin[6]: "-1.000000e+00"
    CutRangeMin[7]: "-1.000000e+00"
    CutRangeMin[8]: "-1.000000e+00"
    CutRangeMin[9]: "-1.000000e+00"
    CutRangeMin[10]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
    CutRangeMax[4]: "-1.000000e+00"
    CutRangeMax[5]: "-1.000000e+00"
    CutRangeMax[6]: "-1.000000e+00"
    CutRangeMax[7]: "-1.000000e+00"
    CutRangeMax[8]: "-1.000000e+00"
    CutRangeMax[9]: "-1.000000e+00"
    CutRangeMax[10]: "-1.000000e+00"
VarProp[0]: "NotEnforced" [Categorisation of cuts]
    VarProp[1]: "NotEnforced"
    VarProp[2]: "NotEnforced"
    VarProp[3]: "NotEnforced"
    VarProp[4]: "NotEnforced"
    VarProp[5]: "NotEnforced"
    VarProp[6]: "NotEnforced"
    VarProp[7]: "NotEnforced"
    VarProp[8]: "NotEnforced"
    VarProp[9]: "NotEnforced"
    VarProp[10]: "NotEnforced"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [4.45244913863e-05,591.79876709]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [2.60141878243e-05,680.619262695]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-27109.4433594,117643.984375]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-30494.9765625,336199.4375]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-848390.4375,742903.3125]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-4408.59033203,5815.69433594]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-10921.9150391,10528.8847656]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-36484.0898438,32938.125]
oa_lambda                     oa_lambda                     oa_lambda                     oa_lambda                     deg                               'F'    [0.0153690213338,179.980255127]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.0131534170359,76398.515625]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.0941462889314,914557.375]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRecCuts : public IClassifierReader {

 public:

   // constructor
   ReadRecCuts( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRecCuts" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "oa_lambda", "dist_lambda_ver_pip_pim", "dist_ver_to_ver" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRecCuts() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRecCuts"
};
   inline double ReadRecCuts::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
