// Class: ReadkMLP_pca_ce_600_n_no_ev
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_pca_ce_600_n_no_ev
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Tue Jul  9 19:20:15 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/nyx/hades/user/knowakow/PP/FAT/TMVA
Training events: 347712
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N,P" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [2.80197054963e-05,679.031311035]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [6.2132923631e-05,680.619262695]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-8469.83496094,8750.23925781]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-6458.21533203,7686.85351562]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-12381.2050781,12644.3095703]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-9303.01855469,13373.6416016]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-31927.2480469,6008.99267578]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-72230.15625,11360.6660156]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.00658369017765,8981.21875]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.0593536905944,4465230.5]
m_inv_pip_pim                 m_inv_pip_pim                 m_inv_pip_pim                 m_inv_pip_pim                 MeV                               'F'    [279.142272949,1466.63110352]
miss_mass_kp                  miss_mass_kp                  miss_mass_kp                  miss_mass_kp                  MeV                               'F'    [-3390.56079102,1638.69995117]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_pca_ce_600_n_no_ev : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_pca_ce_600_n_no_ev( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_pca_ce_600_n_no_ev" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "dist_lambda_ver_pip_pim", "dist_ver_to_ver", "m_inv_pip_pim", "miss_mass_kp" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1.57535600662231;
      fVmax[0] = 0.436240077018738;
      fVmin[1] = -1.49183523654938;
      fVmax[1] = 0.558765172958374;
      fVmin[2] = -1.79121088981628;
      fVmax[2] = 0.0844660103321075;
      fVmin[3] = -1.66614758968353;
      fVmax[3] = 0.933978736400604;
      fVmin[4] = -2.11055159568787;
      fVmax[4] = 0.152089625597;
      fVmin[5] = -1.16381216049194;
      fVmax[5] = 1.2905250787735;
      fVmin[6] = -0.831019997596741;
      fVmax[6] = 0.707691788673401;
      fVmin[7] = -1.05547225475311;
      fVmax[7] = 0.846791207790375;
      fVmin[8] = -2.39749908447266;
      fVmax[8] = 0.292181342840195;
      fVmin[9] = -0.842074811458588;
      fVmax[9] = 0.233131110668182;
      fVmin[10] = -1.99967217445374;
      fVmax[10] = 0.00121532776392996;
      fVmin[11] = -0.345039963722229;
      fVmax[11] = 0.263325482606888;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_pca_ce_600_n_no_ev() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];

   void X2P_2( const double*, double*, int ) const;
   double fMeanValues_2[3][12];
   double fEigenVectors_2[3][12][12];

   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[13][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadkMLP_pca_ce_600_n_no_ev::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.37951753216952;
   fWeightMatrix0to1[1][0] = 2.89736200031176;
   fWeightMatrix0to1[2][0] = 2.49658282123825;
   fWeightMatrix0to1[3][0] = 0.466548101556703;
   fWeightMatrix0to1[4][0] = -1.85355447860966;
   fWeightMatrix0to1[5][0] = -4.35121804473141;
   fWeightMatrix0to1[6][0] = -0.739119861711007;
   fWeightMatrix0to1[7][0] = 20.6858669163815;
   fWeightMatrix0to1[8][0] = -4.35641736989551;
   fWeightMatrix0to1[9][0] = -9.31420385582927;
   fWeightMatrix0to1[10][0] = -13.2896860513357;
   fWeightMatrix0to1[11][0] = 2.2167998463413;
   fWeightMatrix0to1[0][1] = -0.487808433145727;
   fWeightMatrix0to1[1][1] = -0.639072541276521;
   fWeightMatrix0to1[2][1] = -0.733519358326881;
   fWeightMatrix0to1[3][1] = 1.0076212487508;
   fWeightMatrix0to1[4][1] = -0.552622480338225;
   fWeightMatrix0to1[5][1] = 2.41412426184784;
   fWeightMatrix0to1[6][1] = 0.272885438337402;
   fWeightMatrix0to1[7][1] = -4.18511557061482;
   fWeightMatrix0to1[8][1] = 0.385691014514882;
   fWeightMatrix0to1[9][1] = 1.46337102655897;
   fWeightMatrix0to1[10][1] = 3.19354996093887;
   fWeightMatrix0to1[11][1] = 4.35051226223653;
   fWeightMatrix0to1[0][2] = -0.966440913603533;
   fWeightMatrix0to1[1][2] = -0.283840723142318;
   fWeightMatrix0to1[2][2] = 1.84794011959568;
   fWeightMatrix0to1[3][2] = -0.935575189944307;
   fWeightMatrix0to1[4][2] = -1.99778601090183;
   fWeightMatrix0to1[5][2] = 0.142931272384893;
   fWeightMatrix0to1[6][2] = 0.683421271240219;
   fWeightMatrix0to1[7][2] = 2.08497198104997;
   fWeightMatrix0to1[8][2] = -0.430178719176827;
   fWeightMatrix0to1[9][2] = -0.395827921954852;
   fWeightMatrix0to1[10][2] = -0.552280606603423;
   fWeightMatrix0to1[11][2] = -0.0324295685713559;
   fWeightMatrix0to1[0][3] = -1.63847335327083;
   fWeightMatrix0to1[1][3] = 0.93075852215046;
   fWeightMatrix0to1[2][3] = -1.8443004984486;
   fWeightMatrix0to1[3][3] = 1.02515501137858;
   fWeightMatrix0to1[4][3] = 1.36242319807512;
   fWeightMatrix0to1[5][3] = 0.535886393423683;
   fWeightMatrix0to1[6][3] = 1.87761997376498;
   fWeightMatrix0to1[7][3] = -0.405266817851155;
   fWeightMatrix0to1[8][3] = -1.19119132480053;
   fWeightMatrix0to1[9][3] = -0.440179936353913;
   fWeightMatrix0to1[10][3] = 1.19234401634718;
   fWeightMatrix0to1[11][3] = -1.40892750237486;
   fWeightMatrix0to1[0][4] = 1.69773214782102;
   fWeightMatrix0to1[1][4] = 1.91160093061608;
   fWeightMatrix0to1[2][4] = 2.142497234088;
   fWeightMatrix0to1[3][4] = 1.5350725938132;
   fWeightMatrix0to1[4][4] = -1.78218865357411;
   fWeightMatrix0to1[5][4] = 1.61020968966727;
   fWeightMatrix0to1[6][4] = -1.84325606432204;
   fWeightMatrix0to1[7][4] = 1.92743175689386;
   fWeightMatrix0to1[8][4] = -1.01902238486862;
   fWeightMatrix0to1[9][4] = -2.71047433120838;
   fWeightMatrix0to1[10][4] = -0.0799703414789913;
   fWeightMatrix0to1[11][4] = 1.41894034636125;
   fWeightMatrix0to1[0][5] = -1.62702031377375;
   fWeightMatrix0to1[1][5] = 0.311729948487571;
   fWeightMatrix0to1[2][5] = -0.408992077634119;
   fWeightMatrix0to1[3][5] = 0.665860268484466;
   fWeightMatrix0to1[4][5] = 1.83535111265827;
   fWeightMatrix0to1[5][5] = -0.397856332998448;
   fWeightMatrix0to1[6][5] = 0.132712107332505;
   fWeightMatrix0to1[7][5] = -1.52921609368997;
   fWeightMatrix0to1[8][5] = 0.726875903189855;
   fWeightMatrix0to1[9][5] = -0.701397695495412;
   fWeightMatrix0to1[10][5] = -0.578905821586059;
   fWeightMatrix0to1[11][5] = -1.51186051313567;
   fWeightMatrix0to1[0][6] = 0.792899948347552;
   fWeightMatrix0to1[1][6] = 1.20408650464702;
   fWeightMatrix0to1[2][6] = 1.48184943299897;
   fWeightMatrix0to1[3][6] = -0.317348383080297;
   fWeightMatrix0to1[4][6] = -1.93207270306233;
   fWeightMatrix0to1[5][6] = -1.80453557512215;
   fWeightMatrix0to1[6][6] = 1.0004162925753;
   fWeightMatrix0to1[7][6] = 1.10816843535138;
   fWeightMatrix0to1[8][6] = 2.0045999210303;
   fWeightMatrix0to1[9][6] = 0.481296211158501;
   fWeightMatrix0to1[10][6] = 0.769583395972523;
   fWeightMatrix0to1[11][6] = -0.713309633025794;
   fWeightMatrix0to1[0][7] = -0.907283204133082;
   fWeightMatrix0to1[1][7] = -0.27778644595379;
   fWeightMatrix0to1[2][7] = 1.06352388722526;
   fWeightMatrix0to1[3][7] = -1.14992748133404;
   fWeightMatrix0to1[4][7] = -1.57364441092082;
   fWeightMatrix0to1[5][7] = -1.77877685497979;
   fWeightMatrix0to1[6][7] = -0.208770368603536;
   fWeightMatrix0to1[7][7] = -0.572924677108898;
   fWeightMatrix0to1[8][7] = 1.57074126889806;
   fWeightMatrix0to1[9][7] = -1.46765251411488;
   fWeightMatrix0to1[10][7] = -0.60318042778977;
   fWeightMatrix0to1[11][7] = 1.49668460452081;
   fWeightMatrix0to1[0][8] = -0.746820005622811;
   fWeightMatrix0to1[1][8] = -1.31280175938561;
   fWeightMatrix0to1[2][8] = -1.2079681089195;
   fWeightMatrix0to1[3][8] = 0.229325527214604;
   fWeightMatrix0to1[4][8] = -1.97284965200795;
   fWeightMatrix0to1[5][8] = -1.44946657481889;
   fWeightMatrix0to1[6][8] = 0.717029237032982;
   fWeightMatrix0to1[7][8] = 2.71542770301342;
   fWeightMatrix0to1[8][8] = -0.962807172968553;
   fWeightMatrix0to1[9][8] = 1.24388904730373;
   fWeightMatrix0to1[10][8] = -1.52471336322314;
   fWeightMatrix0to1[11][8] = -0.416605460391698;
   fWeightMatrix0to1[0][9] = 0.0210743090166773;
   fWeightMatrix0to1[1][9] = 0.453581351435877;
   fWeightMatrix0to1[2][9] = -1.64309697674089;
   fWeightMatrix0to1[3][9] = 0.335507161995892;
   fWeightMatrix0to1[4][9] = 0.266616694319862;
   fWeightMatrix0to1[5][9] = 0.578658464346226;
   fWeightMatrix0to1[6][9] = -1.41231110242014;
   fWeightMatrix0to1[7][9] = 2.51919199810706;
   fWeightMatrix0to1[8][9] = 0.46730552464354;
   fWeightMatrix0to1[9][9] = -1.194632085673;
   fWeightMatrix0to1[10][9] = 0.425584559983033;
   fWeightMatrix0to1[11][9] = -0.870297323492386;
   fWeightMatrix0to1[0][10] = -1.59312867713986;
   fWeightMatrix0to1[1][10] = 0.128527089958081;
   fWeightMatrix0to1[2][10] = -0.350757532235842;
   fWeightMatrix0to1[3][10] = 1.79624914297712;
   fWeightMatrix0to1[4][10] = 0.778732058540177;
   fWeightMatrix0to1[5][10] = -0.0325834017364783;
   fWeightMatrix0to1[6][10] = -0.343332172953464;
   fWeightMatrix0to1[7][10] = 0.129077825867846;
   fWeightMatrix0to1[8][10] = -1.80591167026979;
   fWeightMatrix0to1[9][10] = 1.07332595375488;
   fWeightMatrix0to1[10][10] = 0.162255665653264;
   fWeightMatrix0to1[11][10] = -1.82910517328982;
   fWeightMatrix0to1[0][11] = 0.751406917316671;
   fWeightMatrix0to1[1][11] = -1.25149498412017;
   fWeightMatrix0to1[2][11] = 0.310514958594957;
   fWeightMatrix0to1[3][11] = 1.29514356360307;
   fWeightMatrix0to1[4][11] = 1.72519790430793;
   fWeightMatrix0to1[5][11] = -1.65418115826777;
   fWeightMatrix0to1[6][11] = 0.347273915006782;
   fWeightMatrix0to1[7][11] = 2.72215649534119;
   fWeightMatrix0to1[8][11] = 1.81751300091958;
   fWeightMatrix0to1[9][11] = -0.241207559149112;
   fWeightMatrix0to1[10][11] = -2.10979483852495;
   fWeightMatrix0to1[11][11] = 0.16804767120192;
   fWeightMatrix0to1[0][12] = -1.15889002588144;
   fWeightMatrix0to1[1][12] = -3.67254363165168;
   fWeightMatrix0to1[2][12] = -3.42889912797114;
   fWeightMatrix0to1[3][12] = -0.270422600896654;
   fWeightMatrix0to1[4][12] = -0.740574502168085;
   fWeightMatrix0to1[5][12] = 0.63037544685473;
   fWeightMatrix0to1[6][12] = -1.44827283160422;
   fWeightMatrix0to1[7][12] = -7.33736189207217;
   fWeightMatrix0to1[8][12] = 1.04156531931805;
   fWeightMatrix0to1[9][12] = 5.47197923527639;
   fWeightMatrix0to1[10][12] = 5.82165850286923;
   fWeightMatrix0to1[11][12] = 0.684013101424026;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.993625633930444;
   fWeightMatrix1to2[0][1] = 2.78134509526811;
   fWeightMatrix1to2[0][2] = 3.64974287485179;
   fWeightMatrix1to2[0][3] = 1.31144805460537;
   fWeightMatrix1to2[0][4] = -1.30750420427712;
   fWeightMatrix1to2[0][5] = 3.19992818239361;
   fWeightMatrix1to2[0][6] = -0.198641002432207;
   fWeightMatrix1to2[0][7] = 15.8036319876368;
   fWeightMatrix1to2[0][8] = 2.85233525379134;
   fWeightMatrix1to2[0][9] = -5.61630917927433;
   fWeightMatrix1to2[0][10] = -8.53394147448407;
   fWeightMatrix1to2[0][11] = 5.1197225253168;
   fWeightMatrix1to2[0][12] = 1.39116068578935;
}

inline double ReadkMLP_pca_ce_600_n_no_ev::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadkMLP_pca_ce_600_n_no_ev::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_pca_ce_600_n_no_ev::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_pca_ce_600_n_no_ev::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_pca_ce_600_n_no_ev::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000485499767819;
   fMax_1[0][0] = 219.682525635;
   fMin_1[1][0] = 2.80197054963e-05;
   fMax_1[1][0] = 679.031311035;
   fMin_1[2][0] = 2.80197054963e-05;
   fMax_1[2][0] = 679.031311035;
   fMin_1[0][1] = 0.00537627376616;
   fMax_1[0][1] = 416.967773438;
   fMin_1[1][1] = 6.2132923631e-05;
   fMax_1[1][1] = 680.619262695;
   fMin_1[2][1] = 6.2132923631e-05;
   fMax_1[2][1] = 680.619262695;
   fMin_1[0][2] = -514.597106934;
   fMax_1[0][2] = 634.596679688;
   fMin_1[1][2] = -8469.83496094;
   fMax_1[1][2] = 8750.23925781;
   fMin_1[2][2] = -8469.83496094;
   fMax_1[2][2] = 8750.23925781;
   fMin_1[0][3] = -604.16015625;
   fMax_1[0][3] = 418.496520996;
   fMin_1[1][3] = -6458.21533203;
   fMax_1[1][3] = 7686.85351562;
   fMin_1[2][3] = -6458.21533203;
   fMax_1[2][3] = 7686.85351562;
   fMin_1[0][4] = -1666.91955566;
   fMax_1[0][4] = 1223.0682373;
   fMin_1[1][4] = -12381.2050781;
   fMax_1[1][4] = 12644.3095703;
   fMin_1[2][4] = -12381.2050781;
   fMax_1[2][4] = 12644.3095703;
   fMin_1[0][5] = -486.255828857;
   fMax_1[0][5] = 381.600860596;
   fMin_1[1][5] = -9303.01855469;
   fMax_1[1][5] = 13373.6416016;
   fMin_1[2][5] = -9303.01855469;
   fMax_1[2][5] = 13373.6416016;
   fMin_1[0][6] = -405.103729248;
   fMax_1[0][6] = 187.405563354;
   fMin_1[1][6] = -31927.2480469;
   fMax_1[1][6] = 6008.99267578;
   fMin_1[2][6] = -31927.2480469;
   fMax_1[2][6] = 6008.99267578;
   fMin_1[0][7] = -629.799926758;
   fMax_1[0][7] = 1493.03039551;
   fMin_1[1][7] = -72230.15625;
   fMax_1[1][7] = 11360.6660156;
   fMin_1[2][7] = -72230.15625;
   fMax_1[2][7] = 11360.6660156;
   fMin_1[0][8] = 0.211806088686;
   fMax_1[0][8] = 893.876647949;
   fMin_1[1][8] = 0.00658369017765;
   fMax_1[1][8] = 8981.21875;
   fMin_1[2][8] = 0.00658369017765;
   fMax_1[2][8] = 8981.21875;
   fMin_1[0][9] = 0.474284917116;
   fMax_1[0][9] = 1588.68200684;
   fMin_1[1][9] = 0.0593536905944;
   fMax_1[1][9] = 4465230.5;
   fMin_1[2][9] = 0.0593536905944;
   fMax_1[2][9] = 4465230.5;
   fMin_1[0][10] = 279.372253418;
   fMax_1[0][10] = 629.105529785;
   fMin_1[1][10] = 279.142272949;
   fMax_1[1][10] = 1466.63110352;
   fMin_1[2][10] = 279.142272949;
   fMax_1[2][10] = 1466.63110352;
   fMin_1[0][11] = -1152.4888916;
   fMax_1[0][11] = 1633.60925293;
   fMin_1[1][11] = -3390.56079102;
   fMax_1[1][11] = 1638.69995117;
   fMin_1[2][11] = -3390.56079102;
   fMax_1[2][11] = 1638.69995117;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::X2P_2( const double* x, double* p, int index ) const
{
   // Calculate the principal components from the original data vector
   // x, and return it in p (function extracted from TPrincipal::X2P)
   // It's the users responsibility to make sure that both x and p are
   // of the right size (i.e., memory must be allocated for p).
   const int nVar = 12;

   for (int i = 0; i < nVar; i++) {
      p[i] = 0;
      for (int j = 0; j < nVar; j++) p[i] += (x[j] - fMeanValues_2[index][j]) * fEigenVectors_2[index][j][i];
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::InitTransform_2()
{
   // PCA transformation, initialisation
   // initialise vector of mean values
   fMeanValues_2[0][0] = -0.981445121654;
   fMeanValues_2[0][1] = -0.965405289172;
   fMeanValues_2[0][2] = -0.0164207714808;
   fMeanValues_2[0][3] = -0.0869097339317;
   fMeanValues_2[0][4] = -0.0129603356431;
   fMeanValues_2[0][5] = -0.179438825708;
   fMeanValues_2[0][6] = 0.683197431806;
   fMeanValues_2[0][7] = 0.728510744478;
   fMeanValues_2[0][8] = -0.995985326547;
   fMeanValues_2[0][9] = -0.99997905494;
   fMeanValues_2[0][10] = -0.897870365125;
   fMeanValues_2[0][11] = 0.935968595213;
   fMeanValues_2[1][0] = -0.95617147589;
   fMeanValues_2[1][1] = -0.960412171696;
   fMeanValues_2[1][2] = -0.0164442648092;
   fMeanValues_2[1][3] = -0.0868091119846;
   fMeanValues_2[1][4] = -0.0128049246593;
   fMeanValues_2[1][5] = -0.179592910284;
   fMeanValues_2[1][6] = 0.683210120816;
   fMeanValues_2[1][7] = 0.727571966054;
   fMeanValues_2[1][8] = -0.993011426463;
   fMeanValues_2[1][9] = -0.999974612584;
   fMeanValues_2[1][10] = -0.721456895416;
   fMeanValues_2[1][11] = 0.606681938331;
   fMeanValues_2[2][0] = -0.956522547205;
   fMeanValues_2[2][1] = -0.960481530123;
   fMeanValues_2[2][2] = -0.0164439384679;
   fMeanValues_2[2][3] = -0.0868105097046;
   fMeanValues_2[2][4] = -0.0128070834432;
   fMeanValues_2[2][5] = -0.179590769925;
   fMeanValues_2[2][6] = 0.683209944555;
   fMeanValues_2[2][7] = 0.727585006443;
   fMeanValues_2[2][8] = -0.993052736332;
   fMeanValues_2[2][9] = -0.999974674292;
   fMeanValues_2[2][10] = -0.723907420732;
   fMeanValues_2[2][11] = 0.611255995461;

   // initialise matrix of eigenvectors
   fEigenVectors_2[0][0][0] = -0.0134809203734;
   fEigenVectors_2[0][0][1] = 0.0382164194718;
   fEigenVectors_2[0][0][2] = -0.0107152388743;
   fEigenVectors_2[0][0][3] = -0.998215921167;
   fEigenVectors_2[0][0][4] = 0.0344360320624;
   fEigenVectors_2[0][0][5] = 0.0242502604817;
   fEigenVectors_2[0][0][6] = -0.00272709818597;
   fEigenVectors_2[0][0][7] = -0.00425032508207;
   fEigenVectors_2[0][0][8] = 0.000660445084756;
   fEigenVectors_2[0][0][9] = -0.00248294679042;
   fEigenVectors_2[0][0][10] = 0.00137833764818;
   fEigenVectors_2[0][0][11] = -9.8286293819e-05;
   fEigenVectors_2[0][1][0] = 0.0396170847848;
   fEigenVectors_2[0][1][1] = 0.991102047655;
   fEigenVectors_2[0][1][2] = 0.108021389453;
   fEigenVectors_2[0][1][3] = 0.0383613493665;
   fEigenVectors_2[0][1][4] = 0.0538033559823;
   fEigenVectors_2[0][1][5] = 0.0105068267393;
   fEigenVectors_2[0][1][6] = 0.000990312010118;
   fEigenVectors_2[0][1][7] = -0.000804341227297;
   fEigenVectors_2[0][1][8] = -0.000390759477919;
   fEigenVectors_2[0][1][9] = -0.00010051817988;
   fEigenVectors_2[0][1][10] = -0.000137705038363;
   fEigenVectors_2[0][1][11] = -7.59827576529e-06;
   fEigenVectors_2[0][2][0] = -0.00208249492585;
   fEigenVectors_2[0][2][1] = -0.00388930015033;
   fEigenVectors_2[0][2][2] = 0.00118848994331;
   fEigenVectors_2[0][2][3] = -0.00563461629564;
   fEigenVectors_2[0][2][4] = 0.14482596743;
   fEigenVectors_2[0][2][5] = -0.278289887672;
   fEigenVectors_2[0][2][6] = -0.099074588271;
   fEigenVectors_2[0][2][7] = 0.94358495968;
   fEigenVectors_2[0][2][8] = -0.0232496047718;
   fEigenVectors_2[0][2][9] = -0.0211196906957;
   fEigenVectors_2[0][2][10] = -0.0193023093089;
   fEigenVectors_2[0][2][11] = 0.000194810624101;
   fEigenVectors_2[0][3][0] = -0.00144321688345;
   fEigenVectors_2[0][3][1] = -0.00308342155253;
   fEigenVectors_2[0][3][2] = 0.000149789623859;
   fEigenVectors_2[0][3][3] = -0.00354405956675;
   fEigenVectors_2[0][3][4] = 0.0647121693279;
   fEigenVectors_2[0][3][5] = -0.112717186953;
   fEigenVectors_2[0][3][6] = 0.989580051662;
   fEigenVectors_2[0][3][7] = 0.0603063317494;
   fEigenVectors_2[0][3][8] = -0.00856755799846;
   fEigenVectors_2[0][3][9] = -0.0099208026209;
   fEigenVectors_2[0][3][10] = 0.0023746326783;
   fEigenVectors_2[0][3][11] = 3.45746454207e-05;
   fEigenVectors_2[0][4][0] = 0.0030435846518;
   fEigenVectors_2[0][4][1] = 0.0090317537953;
   fEigenVectors_2[0][4][2] = -0.00182427069305;
   fEigenVectors_2[0][4][3] = 0.00831850852766;
   fEigenVectors_2[0][4][4] = -0.339463780363;
   fEigenVectors_2[0][4][5] = 0.877782278298;
   fEigenVectors_2[0][4][6] = 0.102495950251;
   fEigenVectors_2[0][4][7] = 0.321144903604;
   fEigenVectors_2[0][4][8] = -0.00261076360765;
   fEigenVectors_2[0][4][9] = -0.0181128320223;
   fEigenVectors_2[0][4][10] = -0.0111656068685;
   fEigenVectors_2[0][4][11] = 0.000470872084639;
   fEigenVectors_2[0][5][0] = 0.000384737990393;
   fEigenVectors_2[0][5][1] = -0.000220985230604;
   fEigenVectors_2[0][5][2] = 0.000247111257765;
   fEigenVectors_2[0][5][3] = -0.00158473453434;
   fEigenVectors_2[0][5][4] = -0.00296932217947;
   fEigenVectors_2[0][5][5] = 0.0091524186082;
   fEigenVectors_2[0][5][6] = -0.00128633235272;
   fEigenVectors_2[0][5][7] = -0.00799620871274;
   fEigenVectors_2[0][5][8] = -0.883882101478;
   fEigenVectors_2[0][5][9] = 0.467286264604;
   fEigenVectors_2[0][5][10] = 0.0153009421708;
   fEigenVectors_2[0][5][11] = -0.000954891383055;
   fEigenVectors_2[0][6][0] = 6.31877968857e-05;
   fEigenVectors_2[0][6][1] = -0.000160375083079;
   fEigenVectors_2[0][6][2] = -0.000434676644845;
   fEigenVectors_2[0][6][3] = 0.00201111398083;
   fEigenVectors_2[0][6][4] = 0.00304432194616;
   fEigenVectors_2[0][6][5] = 0.00461316202736;
   fEigenVectors_2[0][6][6] = -0.00592134655186;
   fEigenVectors_2[0][6][7] = 0.0124598218833;
   fEigenVectors_2[0][6][8] = -0.103373986633;
   fEigenVectors_2[0][6][9] = -0.227101196448;
   fEigenVectors_2[0][6][10] = 0.968250145052;
   fEigenVectors_2[0][6][11] = 0.00232382548143;
   fEigenVectors_2[0][7][0] = 0.000563223998035;
   fEigenVectors_2[0][7][1] = 0.000560651032202;
   fEigenVectors_2[0][7][2] = -0.000465987239011;
   fEigenVectors_2[0][7][3] = -0.00165153271354;
   fEigenVectors_2[0][7][4] = -0.00374961826885;
   fEigenVectors_2[0][7][5] = 0.00534165153187;
   fEigenVectors_2[0][7][6] = 0.0104013983596;
   fEigenVectors_2[0][7][7] = 0.0386545370321;
   fEigenVectors_2[0][7][8] = 0.45540730685;
   fEigenVectors_2[0][7][9] = 0.853801130691;
   fEigenVectors_2[0][7][10] = 0.248471459598;
   fEigenVectors_2[0][7][11] = -0.0155311432216;
   fEigenVectors_2[0][8][0] = 0.0251317973203;
   fEigenVectors_2[0][8][1] = 0.0562569188349;
   fEigenVectors_2[0][8][2] = -0.0147511016236;
   fEigenVectors_2[0][8][3] = -0.0391344209976;
   fEigenVectors_2[0][8][4] = -0.924425734655;
   fEigenVectors_2[0][8][5] = -0.372104803273;
   fEigenVectors_2[0][8][6] = 0.0160168584749;
   fEigenVectors_2[0][8][7] = 0.0338284349313;
   fEigenVectors_2[0][8][8] = -0.00263651172803;
   fEigenVectors_2[0][8][9] = -0.00318058778089;
   fEigenVectors_2[0][8][10] = 0.00339722181006;
   fEigenVectors_2[0][8][11] = -0.000138618778481;
   fEigenVectors_2[0][9][0] = 1.09203139204e-05;
   fEigenVectors_2[0][9][1] = 2.48709754045e-05;
   fEigenVectors_2[0][9][2] = -1.06422626076e-05;
   fEigenVectors_2[0][9][3] = -0.000137754739031;
   fEigenVectors_2[0][9][4] = -6.30391610337e-05;
   fEigenVectors_2[0][9][5] = -0.000323372292209;
   fEigenVectors_2[0][9][6] = 0.000112874519839;
   fEigenVectors_2[0][9][7] = 0.000230929603452;
   fEigenVectors_2[0][9][8] = 0.00647576034891;
   fEigenVectors_2[0][9][9] = 0.0142485243105;
   fEigenVectors_2[0][9][10] = 0.00163335372661;
   fEigenVectors_2[0][9][11] = 0.999876083221;
   fEigenVectors_2[0][10][0] = -0.867151446054;
   fEigenVectors_2[0][10][1] = -0.0179537384226;
   fEigenVectors_2[0][10][2] = 0.496749725831;
   fEigenVectors_2[0][10][3] = 0.00448493554342;
   fEigenVectors_2[0][10][4] = -0.0298675981028;
   fEigenVectors_2[0][10][5] = -0.00726906866721;
   fEigenVectors_2[0][10][6] = -0.000240379794297;
   fEigenVectors_2[0][10][7] = -0.000145136297584;
   fEigenVectors_2[0][10][8] = 9.89745728647e-05;
   fEigenVectors_2[0][10][9] = 0.00057689609794;
   fEigenVectors_2[0][10][10] = 0.000542117752332;
   fEigenVectors_2[0][10][11] = 1.90157234495e-06;
   fEigenVectors_2[0][11][0] = 0.495630266756;
   fEigenVectors_2[0][11][1] = -0.112527607962;
   fEigenVectors_2[0][11][2] = 0.860949155172;
   fEigenVectors_2[0][11][3] = -0.0204683830976;
   fEigenVectors_2[0][11][4] = -0.00585781617533;
   fEigenVectors_2[0][11][5] = -0.000931521023623;
   fEigenVectors_2[0][11][6] = 0.000439713909291;
   fEigenVectors_2[0][11][7] = 0.000108291608833;
   fEigenVectors_2[0][11][8] = 0.000431092295792;
   fEigenVectors_2[0][11][9] = -0.00019962706913;
   fEigenVectors_2[0][11][10] = 0.000401385658048;
   fEigenVectors_2[0][11][11] = 2.38135443824e-06;
   fEigenVectors_2[1][0][0] = -0.00810955218995;
   fEigenVectors_2[1][0][1] = 0.02834416019;
   fEigenVectors_2[1][0][2] = -0.878137157339;
   fEigenVectors_2[1][0][3] = 0.475192899674;
   fEigenVectors_2[1][0][4] = 0.0464966586834;
   fEigenVectors_2[1][0][5] = -0.0017037993866;
   fEigenVectors_2[1][0][6] = 0.00441810251891;
   fEigenVectors_2[1][0][7] = -0.000600113953867;
   fEigenVectors_2[1][0][8] = -0.00332405286908;
   fEigenVectors_2[1][0][9] = 0.000148005073922;
   fEigenVectors_2[1][0][10] = 0.000415998987099;
   fEigenVectors_2[1][0][11] = -0.00131091187454;
   fEigenVectors_2[1][1][0] = -0.00421109170679;
   fEigenVectors_2[1][1][1] = 0.0383073014945;
   fEigenVectors_2[1][1][2] = -0.469974632954;
   fEigenVectors_2[1][1][3] = -0.878444477389;
   fEigenVectors_2[1][1][4] = 0.0771928735392;
   fEigenVectors_2[1][1][5] = 0.000212534730156;
   fEigenVectors_2[1][1][6] = 0.00379099612583;
   fEigenVectors_2[1][1][7] = 0.000259015618279;
   fEigenVectors_2[1][1][8] = -0.000737174814075;
   fEigenVectors_2[1][1][9] = 0.000190384774356;
   fEigenVectors_2[1][1][10] = 2.41845226772e-05;
   fEigenVectors_2[1][1][11] = -0.000397477035176;
   fEigenVectors_2[1][2][0] = 8.77756790423e-05;
   fEigenVectors_2[1][2][1] = -0.00143286599487;
   fEigenVectors_2[1][2][2] = 0.00293553275575;
   fEigenVectors_2[1][2][3] = 0.00268391632541;
   fEigenVectors_2[1][2][4] = 0.0795180170016;
   fEigenVectors_2[1][2][5] = 0.158071080256;
   fEigenVectors_2[1][2][6] = -0.569133284359;
   fEigenVectors_2[1][2][7] = -0.802600790061;
   fEigenVectors_2[1][2][8] = 0.0162084777657;
   fEigenVectors_2[1][2][9] = -0.0177299783777;
   fEigenVectors_2[1][2][10] = 0.00013242168216;
   fEigenVectors_2[1][2][11] = -0.00383783775231;
   fEigenVectors_2[1][3][0] = -1.67787256283e-05;
   fEigenVectors_2[1][3][1] = 0.000498032134525;
   fEigenVectors_2[1][3][2] = -0.00127991697274;
   fEigenVectors_2[1][3][3] = -0.00115689614285;
   fEigenVectors_2[1][3][4] = 0.00447452329852;
   fEigenVectors_2[1][3][5] = -0.85498231886;
   fEigenVectors_2[1][3][6] = -0.487271329244;
   fEigenVectors_2[1][3][7] = 0.177523544489;
   fEigenVectors_2[1][3][8] = -0.00359769464674;
   fEigenVectors_2[1][3][9] = -0.00182973760901;
   fEigenVectors_2[1][3][10] = -8.08965247094e-05;
   fEigenVectors_2[1][3][11] = 0.00421107137079;
   fEigenVectors_2[1][4][0] = -0.0005761553667;
   fEigenVectors_2[1][4][1] = 0.00383276691512;
   fEigenVectors_2[1][4][2] = -0.00803109378618;
   fEigenVectors_2[1][4][3] = -0.00748491601803;
   fEigenVectors_2[1][4][4] = -0.164429978184;
   fEigenVectors_2[1][4][5] = -0.485545857547;
   fEigenVectors_2[1][4][6] = 0.643501240188;
   fEigenVectors_2[1][4][7] = -0.568189970376;
   fEigenVectors_2[1][4][8] = -0.00546880135786;
   fEigenVectors_2[1][4][9] = -0.00834519797238;
   fEigenVectors_2[1][4][10] = 0.000133662535023;
   fEigenVectors_2[1][4][11] = -0.0062611069299;
   fEigenVectors_2[1][5][0] = 0.000193352173866;
   fEigenVectors_2[1][5][1] = -0.00022565385964;
   fEigenVectors_2[1][5][2] = 0.00189719635669;
   fEigenVectors_2[1][5][3] = -0.00043285542361;
   fEigenVectors_2[1][5][4] = 0.000508589790116;
   fEigenVectors_2[1][5][5] = 0.00301403030716;
   fEigenVectors_2[1][5][6] = -0.0104596401731;
   fEigenVectors_2[1][5][7] = -0.022120641729;
   fEigenVectors_2[1][5][8] = -0.599328902073;
   fEigenVectors_2[1][5][9] = 0.783452802996;
   fEigenVectors_2[1][5][10] = -0.00272290029644;
   fEigenVectors_2[1][5][11] = 0.162441415603;
   fEigenVectors_2[1][6][0] = -1.79673179609e-05;
   fEigenVectors_2[1][6][1] = 0.00013581952;
   fEigenVectors_2[1][6][2] = -0.000432289577539;
   fEigenVectors_2[1][6][3] = 0.000260090926366;
   fEigenVectors_2[1][6][4] = -0.000307203172066;
   fEigenVectors_2[1][6][5] = -0.00609683556203;
   fEigenVectors_2[1][6][6] = -0.000598571551427;
   fEigenVectors_2[1][6][7] = 0.000854421659585;
   fEigenVectors_2[1][6][8] = 0.460114854014;
   fEigenVectors_2[1][6][9] = 0.503587023798;
   fEigenVectors_2[1][6][10] = -0.00889925718124;
   fEigenVectors_2[1][6][11] = -0.731147458729;
   fEigenVectors_2[1][7][0] = -0.000283111028087;
   fEigenVectors_2[1][7][1] = 0.000263448531694;
   fEigenVectors_2[1][7][2] = -0.00296410643455;
   fEigenVectors_2[1][7][3] = 0.000787015716521;
   fEigenVectors_2[1][7][4] = -0.000820858401879;
   fEigenVectors_2[1][7][5] = -0.00576651020266;
   fEigenVectors_2[1][7][6] = 0.00789627115746;
   fEigenVectors_2[1][7][7] = -0.00480165314252;
   fEigenVectors_2[1][7][8] = 0.654733144634;
   fEigenVectors_2[1][7][9] = 0.363448032955;
   fEigenVectors_2[1][7][10] = -0.0119194381201;
   fEigenVectors_2[1][7][11] = 0.662539866994;
   fEigenVectors_2[1][8][0] = -0.000136365810974;
   fEigenVectors_2[1][8][1] = 0.0212037816333;
   fEigenVectors_2[1][8][2] = -0.0764060532446;
   fEigenVectors_2[1][8][3] = -0.0448586749306;
   fEigenVectors_2[1][8][4] = -0.978877047123;
   fEigenVectors_2[1][8][5] = 0.0904489095989;
   fEigenVectors_2[1][8][6] = -0.156057377538;
   fEigenVectors_2[1][8][7] = 0.0310456668152;
   fEigenVectors_2[1][8][8] = 0.000994528267406;
   fEigenVectors_2[1][8][9] = -8.00513612942e-05;
   fEigenVectors_2[1][8][10] = 5.13513673656e-05;
   fEigenVectors_2[1][8][11] = 0.000424362493346;
   fEigenVectors_2[1][9][0] = -1.67456343086e-05;
   fEigenVectors_2[1][9][1] = -1.5169823389e-05;
   fEigenVectors_2[1][9][2] = -0.000348195420206;
   fEigenVectors_2[1][9][3] = 0.000162537938317;
   fEigenVectors_2[1][9][4] = -3.01859059456e-05;
   fEigenVectors_2[1][9][5] = 0.000143928017469;
   fEigenVectors_2[1][9][6] = -1.63398754505e-05;
   fEigenVectors_2[1][9][7] = -8.53890388803e-05;
   fEigenVectors_2[1][9][8] = -0.0102676358739;
   fEigenVectors_2[1][9][9] = -0.0109514169116;
   fEigenVectors_2[1][9][10] = -0.999885541896;
   fEigenVectors_2[1][9][11] = -0.00183517701987;
   fEigenVectors_2[1][10][0] = -0.205203747018;
   fEigenVectors_2[1][10][1] = -0.977458196181;
   fEigenVectors_2[1][10][2] = -0.0417947198005;
   fEigenVectors_2[1][10][3] = -0.0207732916111;
   fEigenVectors_2[1][10][4] = -0.0169753968494;
   fEigenVectors_2[1][10][5] = -0.000562196927694;
   fEigenVectors_2[1][10][6] = -8.67121883406e-05;
   fEigenVectors_2[1][10][7] = -0.000227277134592;
   fEigenVectors_2[1][10][8] = 0.000162300807214;
   fEigenVectors_2[1][10][9] = -1.57347853801e-06;
   fEigenVectors_2[1][10][10] = 2.83327989358e-05;
   fEigenVectors_2[1][10][11] = -4.68766534532e-05;
   fEigenVectors_2[1][11][0] = 0.978676375214;
   fEigenVectors_2[1][11][1] = -0.204543157681;
   fEigenVectors_2[1][11][2] = -0.0180788910557;
   fEigenVectors_2[1][11][3] = -0.00420847664339;
   fEigenVectors_2[1][11][4] = -0.00308247524021;
   fEigenVectors_2[1][11][5] = -0.000435532584759;
   fEigenVectors_2[1][11][6] = 0.000438860452966;
   fEigenVectors_2[1][11][7] = -0.000303662307679;
   fEigenVectors_2[1][11][8] = 0.000314796931577;
   fEigenVectors_2[1][11][9] = -4.22364586732e-05;
   fEigenVectors_2[1][11][10] = -1.06176279632e-05;
   fEigenVectors_2[1][11][11] = 0.000120499986444;
   fEigenVectors_2[2][0][0] = -0.00902882732321;
   fEigenVectors_2[2][0][1] = 0.0272038798046;
   fEigenVectors_2[2][0][2] = -0.873827686244;
   fEigenVectors_2[2][0][3] = 0.483105350256;
   fEigenVectors_2[2][0][4] = 0.0466554582898;
   fEigenVectors_2[2][0][5] = -0.00173115315876;
   fEigenVectors_2[2][0][6] = 0.00448063104975;
   fEigenVectors_2[2][0][7] = -0.000597117020423;
   fEigenVectors_2[2][0][8] = -0.00328991506993;
   fEigenVectors_2[2][0][9] = 0.000161910297423;
   fEigenVectors_2[2][0][10] = 0.000414671290704;
   fEigenVectors_2[2][0][11] = -0.00128121709384;
   fEigenVectors_2[2][1][0] = -0.00430265878337;
   fEigenVectors_2[2][1][1] = 0.037992195411;
   fEigenVectors_2[2][1][2] = -0.477929257129;
   fEigenVectors_2[2][1][3] = -0.874167293558;
   fEigenVectors_2[2][1][4] = 0.0770586837401;
   fEigenVectors_2[2][1][5] = 0.000173592817653;
   fEigenVectors_2[2][1][6] = 0.00379179334468;
   fEigenVectors_2[2][1][7] = 0.000265058774774;
   fEigenVectors_2[2][1][8] = -0.00073322342626;
   fEigenVectors_2[2][1][9] = 0.000190435047208;
   fEigenVectors_2[2][1][10] = 2.41410399327e-05;
   fEigenVectors_2[2][1][11] = -0.000393671354949;
   fEigenVectors_2[2][2][0] = 8.47668457978e-05;
   fEigenVectors_2[2][2][1] = -0.00142898054397;
   fEigenVectors_2[2][2][2] = 0.00295500378165;
   fEigenVectors_2[2][2][3] = 0.00266268519032;
   fEigenVectors_2[2][2][4] = 0.07968306516;
   fEigenVectors_2[2][2][5] = 0.159226124561;
   fEigenVectors_2[2][2][6] = -0.566096151139;
   fEigenVectors_2[2][2][7] = -0.804506831982;
   fEigenVectors_2[2][2][8] = 0.0159722142345;
   fEigenVectors_2[2][2][9] = -0.0177204886074;
   fEigenVectors_2[2][2][10] = 0.000132617001389;
   fEigenVectors_2[2][2][11] = -0.00381304349774;
   fEigenVectors_2[2][3][0] = -1.99632223281e-05;
   fEigenVectors_2[2][3][1] = 0.000490014369914;
   fEigenVectors_2[2][3][2] = -0.00128623334201;
   fEigenVectors_2[2][3][3] = -0.0011093778398;
   fEigenVectors_2[2][3][4] = 0.00461407186687;
   fEigenVectors_2[2][3][5] = -0.853713087191;
   fEigenVectors_2[2][3][6] = -0.48996851891;
   fEigenVectors_2[2][3][7] = 0.176201576248;
   fEigenVectors_2[2][3][8] = -0.00352918947851;
   fEigenVectors_2[2][3][9] = -0.00179095272184;
   fEigenVectors_2[2][3][10] = -8.26739660443e-05;
   fEigenVectors_2[2][3][11] = 0.00421128862189;
   fEigenVectors_2[2][4][0] = -0.00056706812853;
   fEigenVectors_2[2][4][1] = 0.00382201724986;
   fEigenVectors_2[2][4][2] = -0.0080894036449;
   fEigenVectors_2[2][4][3] = -0.00740901640842;
   fEigenVectors_2[2][4][4] = -0.164849403212;
   fEigenVectors_2[2][4][5] = -0.487302733625;
   fEigenVectors_2[2][4][6] = 0.644057830497;
   fEigenVectors_2[2][4][7] = -0.565925982067;
   fEigenVectors_2[2][4][8] = -0.00564181790302;
   fEigenVectors_2[2][4][9] = -0.00844240985751;
   fEigenVectors_2[2][4][10] = 0.000136180240537;
   fEigenVectors_2[2][4][11] = -0.00629520157079;
   fEigenVectors_2[2][5][0] = 0.000196584844397;
   fEigenVectors_2[2][5][1] = -0.000221927654099;
   fEigenVectors_2[2][5][2] = 0.00188934439911;
   fEigenVectors_2[2][5][3] = -0.000449486484459;
   fEigenVectors_2[2][5][4] = 0.000503491974102;
   fEigenVectors_2[2][5][5] = 0.00301252294015;
   fEigenVectors_2[2][5][6] = -0.0103164922533;
   fEigenVectors_2[2][5][7] = -0.0220154851155;
   fEigenVectors_2[2][5][8] = -0.59961091928;
   fEigenVectors_2[2][5][9] = 0.783320810036;
   fEigenVectors_2[2][5][10] = -0.00274100044525;
   fEigenVectors_2[2][5][11] = 0.162059992002;
   fEigenVectors_2[2][6][0] = -1.80687181678e-05;
   fEigenVectors_2[2][6][1] = 0.000135257150549;
   fEigenVectors_2[2][6][2] = -0.000425798655483;
   fEigenVectors_2[2][6][3] = 0.000262610642389;
   fEigenVectors_2[2][6][4] = -0.000295297936128;
   fEigenVectors_2[2][6][5] = -0.00607924774427;
   fEigenVectors_2[2][6][6] = -0.000597588074955;
   fEigenVectors_2[2][6][7] = 0.000694477418543;
   fEigenVectors_2[2][6][8] = 0.459554703732;
   fEigenVectors_2[2][6][9] = 0.503180259455;
   fEigenVectors_2[2][6][10] = -0.00865095150134;
   fEigenVectors_2[2][6][11] = -0.731782829162;
   fEigenVectors_2[2][7][0] = -0.00024063380911;
   fEigenVectors_2[2][7][1] = 0.000302473401618;
   fEigenVectors_2[2][7][2] = -0.00290212041034;
   fEigenVectors_2[2][7][3] = 0.000801109141665;
   fEigenVectors_2[2][7][4] = -0.000719770011171;
   fEigenVectors_2[2][7][5] = -0.00581485413277;
   fEigenVectors_2[2][7][6] = 0.00797434021276;
   fEigenVectors_2[2][7][7] = -0.00500386244197;
   fEigenVectors_2[2][7][8] = 0.654873528909;
   fEigenVectors_2[2][7][9] = 0.364294819816;
   fEigenVectors_2[2][7][10] = -0.0120712203683;
   fEigenVectors_2[2][7][11] = 0.661930553923;
   fEigenVectors_2[2][8][0] = -0.000218189166928;
   fEigenVectors_2[2][8][1] = 0.0210127417182;
   fEigenVectors_2[2][8][2] = -0.0769185926937;
   fEigenVectors_2[2][8][3] = -0.0439663396266;
   fEigenVectors_2[2][8][4] = -0.978797509618;
   fEigenVectors_2[2][8][5] = 0.0909596329194;
   fEigenVectors_2[2][8][6] = -0.156366533282;
   fEigenVectors_2[2][8][7] = 0.0306393073137;
   fEigenVectors_2[2][8][8] = 0.00108663080241;
   fEigenVectors_2[2][8][9] = -2.30643153233e-05;
   fEigenVectors_2[2][8][10] = 4.85716411154e-05;
   fEigenVectors_2[2][8][11] = 0.000494934121808;
   fEigenVectors_2[2][9][0] = -1.6730970353e-05;
   fEigenVectors_2[2][9][1] = -1.49969001784e-05;
   fEigenVectors_2[2][9][2] = -0.000345639342923;
   fEigenVectors_2[2][9][3] = 0.000165314745013;
   fEigenVectors_2[2][9][4] = -2.91618949201e-05;
   fEigenVectors_2[2][9][5] = 0.000143571104131;
   fEigenVectors_2[2][9][6] = -1.53246018723e-05;
   fEigenVectors_2[2][9][7] = -8.23528494318e-05;
   fEigenVectors_2[2][9][8] = -0.0102380281171;
   fEigenVectors_2[2][9][9] = -0.0109020781787;
   fEigenVectors_2[2][9][10] = -0.999885850938;
   fEigenVectors_2[2][9][11] = -0.00210636791018;
   fEigenVectors_2[2][10][0] = -0.211266141948;
   fEigenVectors_2[2][10][1] = -0.976222053593;
   fEigenVectors_2[2][10][2] = -0.0405528384946;
   fEigenVectors_2[2][10][3] = -0.0207016832222;
   fEigenVectors_2[2][10][4] = -0.0168407998875;
   fEigenVectors_2[2][10][5] = -0.000563036277268;
   fEigenVectors_2[2][10][6] = -7.56789788981e-05;
   fEigenVectors_2[2][10][7] = -0.000228441345398;
   fEigenVectors_2[2][10][8] = 0.000195495531964;
   fEigenVectors_2[2][10][9] = 2.006421113e-05;
   fEigenVectors_2[2][10][10] = 2.70066534296e-05;
   fEigenVectors_2[2][10][11] = -1.148865733e-05;
   fEigenVectors_2[2][11][0] = 0.977377158909;
   fEigenVectors_2[2][11][1] = -0.210590739583;
   fEigenVectors_2[2][11][2] = -0.0189652242452;
   fEigenVectors_2[2][11][3] = -0.00387433562594;
   fEigenVectors_2[2][11][4] = -0.00319126932905;
   fEigenVectors_2[2][11][5] = -0.0004327502261;
   fEigenVectors_2[2][11][6] = 0.000423612476309;
   fEigenVectors_2[2][11][7] = -0.000298654526684;
   fEigenVectors_2[2][11][8] = 0.000294305560469;
   fEigenVectors_2[2][11][9] = -5.54789935094e-05;
   fEigenVectors_2[2][11][10] = -9.84562582268e-06;
   fEigenVectors_2[2][11][11] = 9.76320123925e-05;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::Transform_2( std::vector<double>& iv, int cls ) const
{
   // PCA transformation
   const int nVar = 12;
   double *dv = new double[nVar];
   double *rv = new double[nVar];
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];

   // Perform PCA and put it into PCAed events tree
   this->X2P_2( dv, rv, cls );
   for (int ivar=0; ivar<nVar; ivar++) iv[indicesPut.at(ivar)] = rv[ivar];

   delete [] dv;
   delete [] rv;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_n_no_ev::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
