// Class: ReadkMLP_ce_600_n2_no_ev
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_ce_600_n2_no_ev
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Tue Jul  9 18:35:48 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/nyx/hades/user/knowakow/PP/FAT/TMVA
Training events: 347712
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [2.80197054963e-05,679.031311035]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [6.2132923631e-05,680.619262695]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-8469.83496094,8750.23925781]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-6458.21533203,7686.85351562]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-12381.2050781,12644.3095703]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-9303.01855469,13373.6416016]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-31927.2480469,6008.99267578]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-72230.15625,11360.6660156]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.00658369017765,8981.21875]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.0593536905944,4465230.5]
m_inv_pip_pim                 m_inv_pip_pim                 m_inv_pip_pim                 m_inv_pip_pim                 MeV                               'F'    [279.142272949,1466.63110352]
miss_mass_kp                  miss_mass_kp                  miss_mass_kp                  miss_mass_kp                  MeV                               'F'    [-3390.56079102,1638.69995117]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_ce_600_n2_no_ev : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_ce_600_n2_no_ev( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_ce_600_n2_no_ev" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "dist_lambda_ver_pip_pim", "dist_ver_to_ver", "m_inv_pip_pim", "miss_mass_kp" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_ce_600_n2_no_ev() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[13][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[13][13];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][13];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadkMLP_ce_600_n2_no_ev::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 13; fWeights[2] = new double[13]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.100541818815003;
   fWeightMatrix0to1[1][0] = 2.36429463078971;
   fWeightMatrix0to1[2][0] = 0.889206897456584;
   fWeightMatrix0to1[3][0] = 1.67947285849;
   fWeightMatrix0to1[4][0] = -2.39526983572789;
   fWeightMatrix0to1[5][0] = -1.5359563134917;
   fWeightMatrix0to1[6][0] = -0.672504324144741;
   fWeightMatrix0to1[7][0] = 1.83146081697142;
   fWeightMatrix0to1[8][0] = -1.42206937757083;
   fWeightMatrix0to1[9][0] = -0.784527742585668;
   fWeightMatrix0to1[10][0] = -1.62609107153667;
   fWeightMatrix0to1[11][0] = -0.494140792075156;
   fWeightMatrix0to1[0][1] = -0.414073184955744;
   fWeightMatrix0to1[1][1] = -1.74271423802928;
   fWeightMatrix0to1[2][1] = -0.606312541622072;
   fWeightMatrix0to1[3][1] = 0.654977500068832;
   fWeightMatrix0to1[4][1] = -1.08372891465583;
   fWeightMatrix0to1[5][1] = 1.15451931950699;
   fWeightMatrix0to1[6][1] = 2.41453778180468;
   fWeightMatrix0to1[7][1] = 1.3794118851858;
   fWeightMatrix0to1[8][1] = -0.332598455819939;
   fWeightMatrix0to1[9][1] = -1.14272392342204;
   fWeightMatrix0to1[10][1] = 0.881290195634075;
   fWeightMatrix0to1[11][1] = 0.0173868318169287;
   fWeightMatrix0to1[0][2] = -1.12822389031384;
   fWeightMatrix0to1[1][2] = -0.518086276204774;
   fWeightMatrix0to1[2][2] = 1.51316314262467;
   fWeightMatrix0to1[3][2] = -1.08619497399038;
   fWeightMatrix0to1[4][2] = -1.5770638129906;
   fWeightMatrix0to1[5][2] = -0.0998191191946895;
   fWeightMatrix0to1[6][2] = 0.899907953920213;
   fWeightMatrix0to1[7][2] = 1.65718566463558;
   fWeightMatrix0to1[8][2] = -0.330970103568693;
   fWeightMatrix0to1[9][2] = -0.220444453858438;
   fWeightMatrix0to1[10][2] = 0.141305908458583;
   fWeightMatrix0to1[11][2] = -0.279923573834402;
   fWeightMatrix0to1[0][3] = -1.31988986106568;
   fWeightMatrix0to1[1][3] = 1.57990212509286;
   fWeightMatrix0to1[2][3] = -1.2067891248313;
   fWeightMatrix0to1[3][3] = 1.10956353568501;
   fWeightMatrix0to1[4][3] = 1.3961155897901;
   fWeightMatrix0to1[5][3] = 0.594884020039193;
   fWeightMatrix0to1[6][3] = 2.24932667049214;
   fWeightMatrix0to1[7][3] = 1.18571967084914;
   fWeightMatrix0to1[8][3] = -0.747177385102;
   fWeightMatrix0to1[9][3] = -1.69142771442622;
   fWeightMatrix0to1[10][3] = 0.690347696072969;
   fWeightMatrix0to1[11][3] = 0.0608589271969462;
   fWeightMatrix0to1[0][4] = 1.64404875816714;
   fWeightMatrix0to1[1][4] = 1.07205617259862;
   fWeightMatrix0to1[2][4] = 1.57922242553231;
   fWeightMatrix0to1[3][4] = 1.31476161347984;
   fWeightMatrix0to1[4][4] = -1.16615486686936;
   fWeightMatrix0to1[5][4] = 0.747896205553175;
   fWeightMatrix0to1[6][4] = -1.46462955136379;
   fWeightMatrix0to1[7][4] = -0.934833045320269;
   fWeightMatrix0to1[8][4] = -1.32080583097136;
   fWeightMatrix0to1[9][4] = -1.82200036259634;
   fWeightMatrix0to1[10][4] = 1.35555647081789;
   fWeightMatrix0to1[11][4] = 0.675147505856376;
   fWeightMatrix0to1[0][5] = -1.42951291710524;
   fWeightMatrix0to1[1][5] = -0.128784847627166;
   fWeightMatrix0to1[2][5] = -0.314401579441964;
   fWeightMatrix0to1[3][5] = 0.695234277382007;
   fWeightMatrix0to1[4][5] = 2.49286072450486;
   fWeightMatrix0to1[5][5] = -1.05730924143173;
   fWeightMatrix0to1[6][5] = 0.623255216966802;
   fWeightMatrix0to1[7][5] = -1.24621796795781;
   fWeightMatrix0to1[8][5] = 0.769468813471042;
   fWeightMatrix0to1[9][5] = -0.926838402870932;
   fWeightMatrix0to1[10][5] = -0.970461729347506;
   fWeightMatrix0to1[11][5] = -1.42661562664442;
   fWeightMatrix0to1[0][6] = 0.0638404119160498;
   fWeightMatrix0to1[1][6] = 2.88795470721482;
   fWeightMatrix0to1[2][6] = 1.33210285601295;
   fWeightMatrix0to1[3][6] = -0.339385600820366;
   fWeightMatrix0to1[4][6] = -4.01483260192164;
   fWeightMatrix0to1[5][6] = 0.71378464138739;
   fWeightMatrix0to1[6][6] = -0.815892946005274;
   fWeightMatrix0to1[7][6] = 0.619166965201678;
   fWeightMatrix0to1[8][6] = 1.95483702887154;
   fWeightMatrix0to1[9][6] = 1.02015482708739;
   fWeightMatrix0to1[10][6] = 1.7875924415287;
   fWeightMatrix0to1[11][6] = -0.766275185330783;
   fWeightMatrix0to1[0][7] = -1.28935417365725;
   fWeightMatrix0to1[1][7] = 0.164081302799305;
   fWeightMatrix0to1[2][7] = 1.1505570209373;
   fWeightMatrix0to1[3][7] = -1.11886933303284;
   fWeightMatrix0to1[4][7] = -2.32347741291823;
   fWeightMatrix0to1[5][7] = -0.506133320177181;
   fWeightMatrix0to1[6][7] = -0.982375499047024;
   fWeightMatrix0to1[7][7] = -0.0142911376617634;
   fWeightMatrix0to1[8][7] = 1.63374161488618;
   fWeightMatrix0to1[9][7] = -1.4254761234161;
   fWeightMatrix0to1[10][7] = -0.513924115037958;
   fWeightMatrix0to1[11][7] = 1.6382435312082;
   fWeightMatrix0to1[0][8] = -0.46951104521447;
   fWeightMatrix0to1[1][8] = -0.441828206582535;
   fWeightMatrix0to1[2][8] = -1.47102856085223;
   fWeightMatrix0to1[3][8] = 0.0825958162477436;
   fWeightMatrix0to1[4][8] = -3.29296949370351;
   fWeightMatrix0to1[5][8] = -1.5201526061475;
   fWeightMatrix0to1[6][8] = 0.475281877054622;
   fWeightMatrix0to1[7][8] = 1.66619417114932;
   fWeightMatrix0to1[8][8] = -1.16280287410667;
   fWeightMatrix0to1[9][8] = 1.50714014187632;
   fWeightMatrix0to1[10][8] = -0.52619973804848;
   fWeightMatrix0to1[11][8] = -0.862541485230839;
   fWeightMatrix0to1[0][9] = 1.02193095777536;
   fWeightMatrix0to1[1][9] = -2.35610585873899;
   fWeightMatrix0to1[2][9] = -1.77536180725856;
   fWeightMatrix0to1[3][9] = 0.205747843634549;
   fWeightMatrix0to1[4][9] = 3.39598486121235;
   fWeightMatrix0to1[5][9] = -3.51153740028501;
   fWeightMatrix0to1[6][9] = 1.44411599000802;
   fWeightMatrix0to1[7][9] = 1.64929685696172;
   fWeightMatrix0to1[8][9] = 0.347498410962615;
   fWeightMatrix0to1[9][9] = -1.55256157299178;
   fWeightMatrix0to1[10][9] = -0.425662917508381;
   fWeightMatrix0to1[11][9] = -1.16865469781304;
   fWeightMatrix0to1[0][10] = -3.59429108051456;
   fWeightMatrix0to1[1][10] = 0.951817242621763;
   fWeightMatrix0to1[2][10] = -0.351421702094606;
   fWeightMatrix0to1[3][10] = 1.84664191383986;
   fWeightMatrix0to1[4][10] = 3.34943411005155;
   fWeightMatrix0to1[5][10] = 0.192451383987046;
   fWeightMatrix0to1[6][10] = -4.08476935432957;
   fWeightMatrix0to1[7][10] = -0.0479455658872994;
   fWeightMatrix0to1[8][10] = -1.80449697933944;
   fWeightMatrix0to1[9][10] = 2.79208474254999;
   fWeightMatrix0to1[10][10] = -0.384591604579081;
   fWeightMatrix0to1[11][10] = -1.84577018055715;
   fWeightMatrix0to1[0][11] = 1.21106462345244;
   fWeightMatrix0to1[1][11] = -8.73762263320869;
   fWeightMatrix0to1[2][11] = 0.0584702468597592;
   fWeightMatrix0to1[3][11] = 1.11879962777407;
   fWeightMatrix0to1[4][11] = 9.61835416670539;
   fWeightMatrix0to1[5][11] = -10.8768438980761;
   fWeightMatrix0to1[6][11] = 7.98428677448405;
   fWeightMatrix0to1[7][11] = 1.53345931368488;
   fWeightMatrix0to1[8][11] = 1.61844193816101;
   fWeightMatrix0to1[9][11] = -0.441583020640924;
   fWeightMatrix0to1[10][11] = -4.58147797304007;
   fWeightMatrix0to1[11][11] = -0.180077818212194;
   fWeightMatrix0to1[0][12] = -2.5039856689442;
   fWeightMatrix0to1[1][12] = 4.28174267404825;
   fWeightMatrix0to1[2][12] = 1.21840614833572;
   fWeightMatrix0to1[3][12] = -0.430573223224871;
   fWeightMatrix0to1[4][12] = -3.50580835534948;
   fWeightMatrix0to1[5][12] = 4.12653408563771;
   fWeightMatrix0to1[6][12] = -4.20975536190796;
   fWeightMatrix0to1[7][12] = 0.791867960164619;
   fWeightMatrix0to1[8][12] = 1.71992346355451;
   fWeightMatrix0to1[9][12] = 0.0423166940700439;
   fWeightMatrix0to1[10][12] = 0.620910177444709;
   fWeightMatrix0to1[11][12] = 0.37973272385873;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.646851518436542;
   fWeightMatrix1to2[1][0] = 0.518808797104782;
   fWeightMatrix1to2[2][0] = 0.87180530521629;
   fWeightMatrix1to2[3][0] = -3.02861650370759;
   fWeightMatrix1to2[4][0] = 2.01381904086347;
   fWeightMatrix1to2[5][0] = 0.936415783705826;
   fWeightMatrix1to2[6][0] = -0.0207630438788119;
   fWeightMatrix1to2[7][0] = 0.661098907927521;
   fWeightMatrix1to2[8][0] = 1.25233424183707;
   fWeightMatrix1to2[9][0] = -0.612730926863283;
   fWeightMatrix1to2[10][0] = -2.00818251741256;
   fWeightMatrix1to2[11][0] = 0.370367155905729;
   fWeightMatrix1to2[0][1] = -0.881749493436636;
   fWeightMatrix1to2[1][1] = -0.722424580080261;
   fWeightMatrix1to2[2][1] = 1.56018514044469;
   fWeightMatrix1to2[3][1] = 1.53381173140009;
   fWeightMatrix1to2[4][1] = -4.90499813677922;
   fWeightMatrix1to2[5][1] = 4.38950635904235;
   fWeightMatrix1to2[6][1] = -0.290122846109159;
   fWeightMatrix1to2[7][1] = -1.94446808864779;
   fWeightMatrix1to2[8][1] = 3.00509936413026;
   fWeightMatrix1to2[9][1] = 0.235962015336176;
   fWeightMatrix1to2[10][1] = 0.709877247316733;
   fWeightMatrix1to2[11][1] = -1.34705490799456;
   fWeightMatrix1to2[0][2] = -1.52459137529677;
   fWeightMatrix1to2[1][2] = 0.788551932577886;
   fWeightMatrix1to2[2][2] = 1.74176441756942;
   fWeightMatrix1to2[3][2] = -1.21752088957701;
   fWeightMatrix1to2[4][2] = -0.817657862683217;
   fWeightMatrix1to2[5][2] = -0.127570161130837;
   fWeightMatrix1to2[6][2] = -0.634753895829191;
   fWeightMatrix1to2[7][2] = 1.76381092112757;
   fWeightMatrix1to2[8][2] = 0.481875218755561;
   fWeightMatrix1to2[9][2] = 0.0585494447854191;
   fWeightMatrix1to2[10][2] = -1.04989111582335;
   fWeightMatrix1to2[11][2] = 0.739842131677074;
   fWeightMatrix1to2[0][3] = 1.63062702190659;
   fWeightMatrix1to2[1][3] = 1.07174007391736;
   fWeightMatrix1to2[2][3] = 0.293816543163556;
   fWeightMatrix1to2[3][3] = -0.733793223936987;
   fWeightMatrix1to2[4][3] = -2.04763831573156;
   fWeightMatrix1to2[5][3] = 1.12802159726392;
   fWeightMatrix1to2[6][3] = 0.439723001086405;
   fWeightMatrix1to2[7][3] = -1.39203484867836;
   fWeightMatrix1to2[8][3] = -0.650423058568236;
   fWeightMatrix1to2[9][3] = 0.337662120178997;
   fWeightMatrix1to2[10][3] = 0.152750312505292;
   fWeightMatrix1to2[11][3] = -1.94587246001685;
   fWeightMatrix1to2[0][4] = 1.75738773047741;
   fWeightMatrix1to2[1][4] = 0.703468930005597;
   fWeightMatrix1to2[2][4] = -0.601820923102534;
   fWeightMatrix1to2[3][4] = 0.62567334546952;
   fWeightMatrix1to2[4][4] = 7.233525221479;
   fWeightMatrix1to2[5][4] = -2.27359665382975;
   fWeightMatrix1to2[6][4] = 2.27668779329736;
   fWeightMatrix1to2[7][4] = -0.17676376219194;
   fWeightMatrix1to2[8][4] = -3.62706200615268;
   fWeightMatrix1to2[9][4] = -0.769092611519062;
   fWeightMatrix1to2[10][4] = 2.20701199387942;
   fWeightMatrix1to2[11][4] = 0.974446892467772;
   fWeightMatrix1to2[0][5] = 0.674486568951592;
   fWeightMatrix1to2[1][5] = 0.125948139068662;
   fWeightMatrix1to2[2][5] = 1.96751262003715;
   fWeightMatrix1to2[3][5] = -1.75019062903524;
   fWeightMatrix1to2[4][5] = -6.44717283302816;
   fWeightMatrix1to2[5][5] = 2.59752121789921;
   fWeightMatrix1to2[6][5] = -3.31501684481457;
   fWeightMatrix1to2[7][5] = 1.00743704551784;
   fWeightMatrix1to2[8][5] = 3.77037362008565;
   fWeightMatrix1to2[9][5] = -1.11501089560694;
   fWeightMatrix1to2[10][5] = 0.539046875005267;
   fWeightMatrix1to2[11][5] = -0.0391631201657409;
   fWeightMatrix1to2[0][6] = -1.82900107119924;
   fWeightMatrix1to2[1][6] = -1.28347978245357;
   fWeightMatrix1to2[2][6] = 0.993724872040351;
   fWeightMatrix1to2[3][6] = -0.686571315202754;
   fWeightMatrix1to2[4][6] = 5.05835761131992;
   fWeightMatrix1to2[5][6] = -3.33307104675593;
   fWeightMatrix1to2[6][6] = 2.46224882696624;
   fWeightMatrix1to2[7][6] = -1.79638852694032;
   fWeightMatrix1to2[8][6] = -0.330407315156912;
   fWeightMatrix1to2[9][6] = 0.367173025160022;
   fWeightMatrix1to2[10][6] = -2.23739892802188;
   fWeightMatrix1to2[11][6] = -1.8800671546851;
   fWeightMatrix1to2[0][7] = -1.91628437191911;
   fWeightMatrix1to2[1][7] = -0.440194372374938;
   fWeightMatrix1to2[2][7] = -1.89749269413036;
   fWeightMatrix1to2[3][7] = -1.53053017005372;
   fWeightMatrix1to2[4][7] = -1.96978877370594;
   fWeightMatrix1to2[5][7] = 0.0806010892004061;
   fWeightMatrix1to2[6][7] = -1.06441077089621;
   fWeightMatrix1to2[7][7] = -1.593341907091;
   fWeightMatrix1to2[8][7] = 1.48934994329826;
   fWeightMatrix1to2[9][7] = -0.805162348397512;
   fWeightMatrix1to2[10][7] = 0.179058397910276;
   fWeightMatrix1to2[11][7] = -1.07530162275058;
   fWeightMatrix1to2[0][8] = 0.228387927736651;
   fWeightMatrix1to2[1][8] = 1.5091179225558;
   fWeightMatrix1to2[2][8] = 1.31151607263109;
   fWeightMatrix1to2[3][8] = -0.357135961850969;
   fWeightMatrix1to2[4][8] = -2.1405935599978;
   fWeightMatrix1to2[5][8] = -0.604820801364439;
   fWeightMatrix1to2[6][8] = -1.83958154981789;
   fWeightMatrix1to2[7][8] = -1.63749546020713;
   fWeightMatrix1to2[8][8] = 1.20023229548164;
   fWeightMatrix1to2[9][8] = 0.822227229866586;
   fWeightMatrix1to2[10][8] = 1.88162971171863;
   fWeightMatrix1to2[11][8] = -0.640104212655294;
   fWeightMatrix1to2[0][9] = 0.610625699501594;
   fWeightMatrix1to2[1][9] = -0.847763065092536;
   fWeightMatrix1to2[2][9] = -1.95791777840044;
   fWeightMatrix1to2[3][9] = 2.97552714754483;
   fWeightMatrix1to2[4][9] = -0.202430727352672;
   fWeightMatrix1to2[5][9] = -0.192259325022314;
   fWeightMatrix1to2[6][9] = -1.60013537363549;
   fWeightMatrix1to2[7][9] = 0.796680317956052;
   fWeightMatrix1to2[8][9] = 1.91047986951233;
   fWeightMatrix1to2[9][9] = 0.982298697529107;
   fWeightMatrix1to2[10][9] = 0.695036233633982;
   fWeightMatrix1to2[11][9] = 0.0474524881212341;
   fWeightMatrix1to2[0][10] = 1.39583929700324;
   fWeightMatrix1to2[1][10] = 0.909126055052223;
   fWeightMatrix1to2[2][10] = 0.969450928614128;
   fWeightMatrix1to2[3][10] = -0.293850714233245;
   fWeightMatrix1to2[4][10] = -2.47432775455797;
   fWeightMatrix1to2[5][10] = 1.45439520017146;
   fWeightMatrix1to2[6][10] = -2.71136918722523;
   fWeightMatrix1to2[7][10] = -0.53121998046763;
   fWeightMatrix1to2[8][10] = -0.42954851874443;
   fWeightMatrix1to2[9][10] = -1.28395439585235;
   fWeightMatrix1to2[10][10] = -1.75179502625172;
   fWeightMatrix1to2[11][10] = 1.84748355680395;
   fWeightMatrix1to2[0][11] = -1.82640468524375;
   fWeightMatrix1to2[1][11] = 1.32042483533758;
   fWeightMatrix1to2[2][11] = -1.62560012397733;
   fWeightMatrix1to2[3][11] = 1.5896301944616;
   fWeightMatrix1to2[4][11] = -1.62214098668645;
   fWeightMatrix1to2[5][11] = 0.850766668759035;
   fWeightMatrix1to2[6][11] = -0.0547996567278338;
   fWeightMatrix1to2[7][11] = -1.85521251083906;
   fWeightMatrix1to2[8][11] = 1.03274936521926;
   fWeightMatrix1to2[9][11] = 1.13473118039387;
   fWeightMatrix1to2[10][11] = -1.99498322800834;
   fWeightMatrix1to2[11][11] = -1.82202455251;
   fWeightMatrix1to2[0][12] = -1.69417356853726;
   fWeightMatrix1to2[1][12] = -1.18473610452178;
   fWeightMatrix1to2[2][12] = 1.81247371000209;
   fWeightMatrix1to2[3][12] = -0.0242603981392086;
   fWeightMatrix1to2[4][12] = -0.368920451484149;
   fWeightMatrix1to2[5][12] = -0.438078135928051;
   fWeightMatrix1to2[6][12] = -2.14464007936476;
   fWeightMatrix1to2[7][12] = -1.70800567798826;
   fWeightMatrix1to2[8][12] = -0.131627264842956;
   fWeightMatrix1to2[9][12] = -0.848545344292234;
   fWeightMatrix1to2[10][12] = 0.98061993594276;
   fWeightMatrix1to2[11][12] = -1.66440657286637;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.24527070925307;
   fWeightMatrix2to3[0][1] = 2.38787816504056;
   fWeightMatrix2to3[0][2] = 0.843124979207471;
   fWeightMatrix2to3[0][3] = -3.53357021532717;
   fWeightMatrix2to3[0][4] = 7.27151144983149;
   fWeightMatrix2to3[0][5] = -2.64247457630864;
   fWeightMatrix2to3[0][6] = 3.67151327472596;
   fWeightMatrix2to3[0][7] = 0.959637858361752;
   fWeightMatrix2to3[0][8] = -3.15827577405192;
   fWeightMatrix2to3[0][9] = -1.5842107637527;
   fWeightMatrix2to3[0][10] = -2.35840927494675;
   fWeightMatrix2to3[0][11] = -0.807654120233116;
   fWeightMatrix2to3[0][12] = 0.958333588692556;
}

inline double ReadkMLP_ce_600_n2_no_ev::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadkMLP_ce_600_n2_no_ev::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_ce_600_n2_no_ev::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_ce_600_n2_no_ev::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_ce_600_n2_no_ev::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_ce_600_n2_no_ev::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.000485499767819;
   fMax_1[0][0] = 219.682525635;
   fMin_1[1][0] = 2.80197054963e-05;
   fMax_1[1][0] = 679.031311035;
   fMin_1[2][0] = 2.80197054963e-05;
   fMax_1[2][0] = 679.031311035;
   fMin_1[0][1] = 0.00537627376616;
   fMax_1[0][1] = 416.967773438;
   fMin_1[1][1] = 6.2132923631e-05;
   fMax_1[1][1] = 680.619262695;
   fMin_1[2][1] = 6.2132923631e-05;
   fMax_1[2][1] = 680.619262695;
   fMin_1[0][2] = -514.597106934;
   fMax_1[0][2] = 634.596679688;
   fMin_1[1][2] = -8469.83496094;
   fMax_1[1][2] = 8750.23925781;
   fMin_1[2][2] = -8469.83496094;
   fMax_1[2][2] = 8750.23925781;
   fMin_1[0][3] = -604.16015625;
   fMax_1[0][3] = 418.496520996;
   fMin_1[1][3] = -6458.21533203;
   fMax_1[1][3] = 7686.85351562;
   fMin_1[2][3] = -6458.21533203;
   fMax_1[2][3] = 7686.85351562;
   fMin_1[0][4] = -1666.91955566;
   fMax_1[0][4] = 1223.0682373;
   fMin_1[1][4] = -12381.2050781;
   fMax_1[1][4] = 12644.3095703;
   fMin_1[2][4] = -12381.2050781;
   fMax_1[2][4] = 12644.3095703;
   fMin_1[0][5] = -486.255828857;
   fMax_1[0][5] = 381.600860596;
   fMin_1[1][5] = -9303.01855469;
   fMax_1[1][5] = 13373.6416016;
   fMin_1[2][5] = -9303.01855469;
   fMax_1[2][5] = 13373.6416016;
   fMin_1[0][6] = -405.103729248;
   fMax_1[0][6] = 187.405563354;
   fMin_1[1][6] = -31927.2480469;
   fMax_1[1][6] = 6008.99267578;
   fMin_1[2][6] = -31927.2480469;
   fMax_1[2][6] = 6008.99267578;
   fMin_1[0][7] = -629.799926758;
   fMax_1[0][7] = 1493.03039551;
   fMin_1[1][7] = -72230.15625;
   fMax_1[1][7] = 11360.6660156;
   fMin_1[2][7] = -72230.15625;
   fMax_1[2][7] = 11360.6660156;
   fMin_1[0][8] = 0.211806088686;
   fMax_1[0][8] = 893.876647949;
   fMin_1[1][8] = 0.00658369017765;
   fMax_1[1][8] = 8981.21875;
   fMin_1[2][8] = 0.00658369017765;
   fMax_1[2][8] = 8981.21875;
   fMin_1[0][9] = 0.474284917116;
   fMax_1[0][9] = 1588.68200684;
   fMin_1[1][9] = 0.0593536905944;
   fMax_1[1][9] = 4465230.5;
   fMin_1[2][9] = 0.0593536905944;
   fMax_1[2][9] = 4465230.5;
   fMin_1[0][10] = 279.372253418;
   fMax_1[0][10] = 629.105529785;
   fMin_1[1][10] = 279.142272949;
   fMax_1[1][10] = 1466.63110352;
   fMin_1[2][10] = 279.142272949;
   fMax_1[2][10] = 1466.63110352;
   fMin_1[0][11] = -1152.4888916;
   fMax_1[0][11] = 1633.60925293;
   fMin_1[1][11] = -3390.56079102;
   fMax_1[1][11] = 1638.69995117;
   fMin_1[2][11] = -3390.56079102;
   fMax_1[2][11] = 1638.69995117;
}

//_______________________________________________________________________
inline void ReadkMLP_ce_600_n2_no_ev::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_ce_600_n2_no_ev::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadkMLP_ce_600_n2_no_ev::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
