#ifndef PPimEpEm_ID_buffer_h
#define PPipEpEm_ID_buffer_h

#include "PPimEpEm.h"

class PPimEpEm_ID_buffer
{
public :
  // Declaration of leaf types
  Float_t         eVert_chi2;
  Float_t         eVert_x;
  Float_t         eVert_y;
  Float_t         eVert_z;
  Float_t         event;
  Float_t         hneg_mult;
  Float_t         hpos_mult;
  Float_t         isBest;
  Float_t         lneg_mult;
  Float_t         lpos_mult;
  Float_t         p_beta;
  Float_t         p_beta_new;
  Float_t         p_dedx_in;
  Float_t         p_dedx_in_sigma;
  Float_t         p_dedx_mdc;
  Float_t         p_dedx_mdc_sigma;
  Float_t         p_dedx_out;
  Float_t         p_dedx_out_sigma;
  Float_t         p_dedx_tof;
  Float_t         p_id;
  Float_t         p_isring;
  Float_t         p_kIsLepton;
  Float_t         p_kIsUsed;
  Float_t         p_mdcchi2;
  Float_t         p_oa_hadr;
  Float_t         p_oa_lept;
  Float_t         p_p;
  Float_t         p_phi;
  Float_t         p_q;
  Float_t         p_r;
  Float_t         p_resolution;
  Float_t         p_rkchi2;
  Float_t         p_sector;
  Float_t         p_shw_sum0;
  Float_t         p_shw_sum1;
  Float_t         p_shw_sum2;
  /*
    Float_t         p_sim_corrflag;
    Float_t         p_sim_geninfo;
    Float_t         p_sim_geninfo1;
    Float_t         p_sim_geninfo2;
    Float_t         p_sim_genweight;
    Float_t         p_sim_id;
    Float_t         p_sim_iscommon;
    Float_t         p_sim_mediumid;
    Float_t         p_sim_p;
    Float_t         p_sim_parentid;
    Float_t         p_sim_primaryflag;
    Float_t         p_sim_processid;
    Float_t         p_sim_px;
    Float_t         p_sim_py;
    Float_t         p_sim_pz;
    Float_t         p_sim_vertexx;
    Float_t         p_sim_vertexy;
    Float_t         p_sim_vertexz;
  */  
  Float_t         p_system;
  Float_t         p_theta;
  Float_t         p_tof_exp;
  Float_t         p_tof_mom;
  Float_t         p_tof_new;
  Float_t         p_tofino_mult;
  Float_t         p_track_length;
  Float_t         p_z;
  Float_t         pim_beta;
  Float_t         pim_beta_new;
  Float_t         pim_dedx_in;
  Float_t         pim_dedx_in_sigma;
  Float_t         pim_dedx_mdc;
  Float_t         pim_dedx_mdc_sigma;
  Float_t         pim_dedx_out;
  Float_t         pim_dedx_out_sigma;
  Float_t         pim_dedx_tof;
  Float_t         pim_id;
  Float_t         pim_isring;
  Float_t         pim_kIsLepton;
  Float_t         pim_kIsUsed;
  Float_t         pim_mdcchi2;
  Float_t         pim_oa_hadr;
  Float_t         pim_oa_lept;
  Float_t         pim_p;
  Float_t         pim_phi;
  Float_t         pim_q;
  Float_t         pim_r;
  Float_t         pim_resolution;
  Float_t         pim_rkchi2;
  Float_t         pim_sector;
  Float_t         pim_shw_sum0;
  Float_t         pim_shw_sum1;
  Float_t         pim_shw_sum2;
  /*
    Float_t         pim_sim_corrflag;
    Float_t         pim_sim_geninfo;
    Float_t         pim_sim_geninfo1;
    Float_t         pim_sim_geninfo2;
    Float_t         pim_sim_genweight;
    Float_t         pim_sim_id;
    Float_t         pim_sim_iscommon;
    Float_t         pim_sim_mediumid;
    Float_t         pim_sim_p;
    Float_t         pim_sim_parentid;
    Float_t         pim_sim_primaryflag;
    Float_t         pim_sim_processid;
    Float_t         pim_sim_px;
    Float_t         pim_sim_py;
    Float_t         pim_sim_pz;
    Float_t         pim_sim_vertexx;
    Float_t         pim_sim_vertexy;
    Float_t         pim_sim_vertexz;
  */  
  Float_t         pim_system;
  Float_t         pim_theta;
  Float_t         pim_tof_exp;
  Float_t         pim_tof_mom;
  Float_t         pim_tof_new;
  Float_t         pim_tofino_mult;
  Float_t         pim_track_length;
  Float_t         pim_z;
  Float_t         em_beta;
  Float_t         em_beta_new;
  Float_t         em_dedx_in;
  Float_t         em_dedx_in_sigma;
  Float_t         em_dedx_mdc;
  Float_t         em_dedx_mdc_sigma;
  Float_t         em_dedx_out;
  Float_t         em_dedx_out_sigma;
  Float_t         em_dedx_tof;
  Float_t         em_id;
  Float_t         em_isring;
  Float_t         em_kIsLepton;
  Float_t         em_kIsUsed;
  Float_t         em_mdcchi2;
  Float_t         em_oa_hadr;
  Float_t         em_oa_lept;
  Float_t         em_p;
  Float_t         em_phi;
  Float_t         em_q;
  Float_t         em_r;
  Float_t         em_resolution;
  Float_t         em_rkchi2;
  Float_t         em_sector;
  Float_t         em_shw_sum0;
  Float_t         em_shw_sum1;
  Float_t         em_shw_sum2;
  /*
    Float_t         em_sim_corrflag;
    Float_t         em_sim_geninfo;
    Float_t         em_sim_geninfo1;
    Float_t         em_sim_geninfo2;
    Float_t         em_sim_genweight;
    Float_t         em_sim_id;
    Float_t         em_sim_iscommon;
    Float_t         em_sim_mediumid;
    Float_t         em_sim_p;
    Float_t         em_sim_parentid;
    Float_t         em_sim_primaryflag;
    Float_t         em_sim_processid;
    Float_t         em_sim_px;
    Float_t         em_sim_py;
    Float_t         em_sim_pz;
    Float_t         em_sim_vertexx;
    Float_t         em_sim_vertexy;
    Float_t         em_sim_vertexz;
  */  
  Float_t         em_system;
  Float_t         em_theta;
  Float_t         em_tof_exp;
  Float_t         em_tof_mom;
  Float_t         em_tof_new;
  Float_t         em_tofino_mult;
  Float_t         em_track_length;
  Float_t         em_z;
  Float_t         ep_beta;
  Float_t         ep_beta_new;
  Float_t         ep_dedx_in;
  Float_t         ep_dedx_in_sigma;
  Float_t         ep_dedx_mdc;
  Float_t         ep_dedx_mdc_sigma;
  Float_t         ep_dedx_out;
  Float_t         ep_dedx_out_sigma;
  Float_t         ep_dedx_tof;
  Float_t         ep_id;
  Float_t         ep_isring;
  Float_t         ep_kIsLepton;
  Float_t         ep_kIsUsed;
  Float_t         ep_mdcchi2;
  Float_t         ep_oa_hadr;
  Float_t         ep_oa_lept;
  Float_t         ep_p;
  Float_t         ep_phi;
  Float_t         ep_q;
  Float_t         ep_r;
  Float_t         ep_resolution;
  Float_t         ep_rkchi2;
  Float_t         ep_sector;
  Float_t         ep_shw_sum0;
  Float_t         ep_shw_sum1;
  Float_t         ep_shw_sum2;
  /*
    Float_t         ep_sim_corrflag;
    Float_t         ep_sim_geninfo;
    Float_t         ep_sim_geninfo1;
    Float_t         ep_sim_geninfo2;
    Float_t         ep_sim_genweight;
    Float_t         ep_sim_id;
    Float_t         ep_sim_iscommon;
    Float_t         ep_sim_mediumid;
    Float_t         ep_sim_p;
    Float_t         ep_sim_parentid;
    Float_t         ep_sim_primaryflag;
    Float_t         ep_sim_processid;
    Float_t         ep_sim_px;
    Float_t         ep_sim_py;
    Float_t         ep_sim_pz;
    Float_t         ep_sim_vertexx;
    Float_t         ep_sim_vertexy;
    Float_t         ep_sim_vertexz;
  */  
  Float_t         ep_system;
  Float_t         ep_theta;
  Float_t         ep_tof_exp;
  Float_t         ep_tof_mom;
  Float_t         ep_tof_new;
  Float_t         ep_tofino_mult;
  Float_t         ep_track_length;
  Float_t         ep_z;
  Float_t         runnumber;
  Float_t         totalmult;
  Float_t         trigbit;
  Float_t         trigdec;
  Float_t         trigdownscale;
  Float_t         trigdownscaleflag;    

  PPimEpEm_ID_buffer(const PPimEpEm_ID_buffer& src)
  {
    eVert_chi2=src.eVert_chi2;
    eVert_x=src.eVert_x;
    eVert_y=src.eVert_y;
    eVert_z=src.eVert_z;
    event=src.event;
    hneg_mult=src.hneg_mult;
    hpos_mult=src.hpos_mult;
    isBest=src.isBest;
    lneg_mult=src.lneg_mult;
    lpos_mult=src.lpos_mult;
    p_beta=src.p_beta;
    p_beta_new=src.p_beta_new;
    p_dedx_in=src.p_dedx_in;
    p_dedx_in_sigma=src.p_dedx_in_sigma;
    p_dedx_mdc=src.p_dedx_mdc;
    p_dedx_mdc_sigma=src.p_dedx_mdc_sigma;
    p_dedx_out=src.p_dedx_out;
    p_dedx_out_sigma=src.p_dedx_out_sigma;
    p_dedx_tof=src.p_dedx_tof;
    p_id=src.p_id;
    p_isring=src.p_isring;
    p_kIsLepton=src.p_kIsLepton;
    p_kIsUsed=src.p_kIsUsed;
    p_mdcchi2=src.p_mdcchi2;
    p_oa_hadr=src.p_oa_hadr;
    p_oa_lept=src.p_oa_lept;
    p_p=src.p_p;
    p_phi=src.p_phi;
    p_q=src.p_q;
    p_r=src.p_r;
    p_resolution=src.p_resolution;
    p_rkchi2=src.p_rkchi2;
    p_sector=src.p_sector;
    p_shw_sum0=src.p_shw_sum0;
    p_shw_sum1=src.p_shw_sum1;
    p_shw_sum2=src.p_shw_sum2;
    /*
      p_sim_corrflag=src.p_sim_corrflag;
      p_sim_geninfo=src.p_sim_geninfo;
      p_sim_geninfo1=src.p_sim_geninfo1;
      p_sim_geninfo2=src.p_sim_geninfo2;
      p_sim_genweight=src.p_sim_genweight;
      p_sim_id=src.p_sim_id;
      p_sim_iscommon=src.p_sim_iscommon;
      p_sim_mediumid=src.p_sim_mediumid;
      p_sim_p=src.p_sim_p;
      p_sim_parentid=src.p_sim_parentid;
      p_sim_primaryflag=src.p_sim_primaryflag;
      p_sim_processid=src.p_sim_processid;
      p_sim_px=src.p_sim_px;
      p_sim_py=src.p_sim_py;
      p_sim_pz=src.p_sim_pz;
      p_sim_vertexx=src.p_sim_vertexx;
      p_sim_vertexy=src.p_sim_vertexy;
      p_sim_vertexz=src.p_sim_vertexz;
    */    
    p_system=src.p_system;
    p_theta=src.p_theta;
    p_tof_exp=src.p_tof_exp;
    p_tof_mom=src.p_tof_mom;
    p_tof_new=src.p_tof_new;
    p_tofino_mult=src.p_tofino_mult;
    p_track_length=src.p_track_length;
    p_z=src.p_z;
    pim_beta=src.pim_beta;
    pim_beta_new=src.pim_beta_new;
    pim_dedx_in=src.pim_dedx_in;
    pim_dedx_in_sigma=src.pim_dedx_in_sigma;
    pim_dedx_mdc=src.pim_dedx_mdc;
    pim_dedx_mdc_sigma=src.pim_dedx_mdc_sigma;
    pim_dedx_out=src.pim_dedx_out;
    pim_dedx_out_sigma=src.pim_dedx_out_sigma;
    pim_dedx_tof=src.pim_dedx_tof;
    pim_id=src.pim_id;
    pim_isring=src.pim_isring;
    pim_kIsLepton=src.pim_kIsLepton;
    pim_kIsUsed=src.pim_kIsUsed;
    pim_mdcchi2=src.pim_mdcchi2;
    pim_oa_hadr=src.pim_oa_hadr;
    pim_oa_lept=src.pim_oa_lept;
    pim_p=src.pim_p;
    pim_phi=src.pim_phi;
    pim_q=src.pim_q;
    pim_r=src.pim_r;
    pim_resolution=src.pim_resolution;
    pim_rkchi2=src.pim_rkchi2;
    pim_sector=src.pim_sector;
    pim_shw_sum0=src.pim_shw_sum0;
    pim_shw_sum1=src.pim_shw_sum1;
    pim_shw_sum2=src.pim_shw_sum2;
    /*
      pim_sim_corrflag=src.pim_sim_corrflag;
      pim_sim_geninfo=src.pim_sim_geninfo;
      pim_sim_geninfo1=src.pim_sim_geninfo1;
      pim_sim_geninfo2=src.pim_sim_geninfo2;
      pim_sim_genweight=src.pim_sim_genweight;
      pim_sim_id=src.pim_sim_id;
      pim_sim_iscommon=src.pim_sim_iscommon;
      pim_sim_mediumid=src.pim_sim_mediumid;
      pim_sim_p=src.pim_sim_p;
      pim_sim_parentid=src.pim_sim_parentid;
      pim_sim_primaryflag=src.pim_sim_primaryflag;
      pim_sim_processid=src.pim_sim_processid;
      pim_sim_px=src.pim_sim_px;
      pim_sim_py=src.pim_sim_py;
      pim_sim_pz=src.pim_sim_pz;
      pim_sim_vertexx=src.pim_sim_vertexx;
      pim_sim_vertexy=src.pim_sim_vertexy;
      pim_sim_vertexz=src.pim_sim_vertexz;
    */    
    pim_system=src.pim_system;
    pim_theta=src.pim_theta;
    pim_tof_exp=src.pim_tof_exp;
    pim_tof_mom=src.pim_tof_mom;
    pim_tof_new=src.pim_tof_new;
    pim_tofino_mult=src.pim_tofino_mult;
    pim_track_length=src.pim_track_length;
    pim_z=src.pim_z;
    em_beta=src.em_beta;
    em_beta_new=src.em_beta_new;
    em_dedx_in=src.em_dedx_in;
    em_dedx_in_sigma=src.em_dedx_in_sigma;
    em_dedx_mdc=src.em_dedx_mdc;
    em_dedx_mdc_sigma=src.em_dedx_mdc_sigma;
    em_dedx_out=src.em_dedx_out;
    em_dedx_out_sigma=src.em_dedx_out_sigma;
    em_dedx_tof=src.em_dedx_tof;
    em_id=src.em_id;
    em_isring=src.em_isring;
    em_kIsLepton=src.em_kIsLepton;
    em_kIsUsed=src.em_kIsUsed;
    em_mdcchi2=src.em_mdcchi2;
    em_oa_hadr=src.em_oa_hadr;
    em_oa_lept=src.em_oa_lept;
    em_p=src.em_p;
    em_phi=src.em_phi;
    em_q=src.em_q;
    em_r=src.em_r;
    em_resolution=src.em_resolution;
    em_rkchi2=src.em_rkchi2;
    em_sector=src.em_sector;
    em_shw_sum0=src.em_shw_sum0;
    em_shw_sum1=src.em_shw_sum1;
    em_shw_sum2=src.em_shw_sum2;
    /*
      em_sim_corrflag=src.em_sim_corrflag;
      em_sim_geninfo=src.em_sim_geninfo;
      em_sim_geninfo1=src.em_sim_geninfo1;
      em_sim_geninfo2=src.em_sim_geninfo2;
      em_sim_genweight=src.em_sim_genweight;
      em_sim_id=src.em_sim_id;
      em_sim_iscommon=src.em_sim_iscommon;
      em_sim_mediumid=src.em_sim_mediumid;
      em_sim_p=src.em_sim_p;
      em_sim_parentid=src.em_sim_parentid;
      em_sim_primaryflag=src.em_sim_primaryflag;
      em_sim_processid=src.em_sim_processid;
      em_sim_px=src.em_sim_px;
      em_sim_py=src.em_sim_py;
      em_sim_pz=src.em_sim_pz;
      em_sim_vertexx=src.em_sim_vertexx;
      em_sim_vertexy=src.em_sim_vertexy;
      em_sim_vertexz=src.em_sim_vertexz;
    */    
    em_system=src.em_system;
    em_theta=src.em_theta;
    em_tof_exp=src.em_tof_exp;
    em_tof_mom=src.em_tof_mom;
    em_tof_new=src.em_tof_new;
    em_tofino_mult=src.em_tofino_mult;
    em_track_length=src.em_track_length;
    em_z=src.em_z;
    ep_beta=src.ep_beta;
    ep_beta_new=src.ep_beta_new;
    ep_dedx_in=src.ep_dedx_in;
    ep_dedx_in_sigma=src.ep_dedx_in_sigma;
    ep_dedx_mdc=src.ep_dedx_mdc;
    ep_dedx_mdc_sigma=src.ep_dedx_mdc_sigma;
    ep_dedx_out=src.ep_dedx_out;
    ep_dedx_out_sigma=src.ep_dedx_out_sigma;
    ep_dedx_tof=src.ep_dedx_tof;
    ep_id=src.ep_id;
    ep_isring=src.ep_isring;
    ep_kIsLepton=src.ep_kIsLepton;
    ep_kIsUsed=src.ep_kIsUsed;
    ep_mdcchi2=src.ep_mdcchi2;
    ep_oa_hadr=src.ep_oa_hadr;
    ep_oa_lept=src.ep_oa_lept;
    ep_p=src.ep_p;
    ep_phi=src.ep_phi;
    ep_q=src.ep_q;
    ep_r=src.ep_r;
    ep_resolution=src.ep_resolution;
    ep_rkchi2=src.ep_rkchi2;
    ep_sector=src.ep_sector;
    ep_shw_sum0=src.ep_shw_sum0;
    ep_shw_sum1=src.ep_shw_sum1;
    ep_shw_sum2=src.ep_shw_sum2;
    /*
      ep_sim_corrflag=src.ep_sim_corrflag;
      ep_sim_geninfo=src.ep_sim_geninfo;
      ep_sim_geninfo1=src.ep_sim_geninfo1;
      ep_sim_geninfo2=src.ep_sim_geninfo2;
      ep_sim_genweight=src.ep_sim_genweight;
      ep_sim_id=src.ep_sim_id;
      ep_sim_iscommon=src.ep_sim_iscommon;
      ep_sim_mediumid=src.ep_sim_mediumid;
      ep_sim_p=src.ep_sim_p;
      ep_sim_parentid=src.ep_sim_parentid;
      ep_sim_primaryflag=src.ep_sim_primaryflag;
      ep_sim_processid=src.ep_sim_processid;
      ep_sim_px=src.ep_sim_px;
      ep_sim_py=src.ep_sim_py;
      ep_sim_pz=src.ep_sim_pz;
      ep_sim_vertexx=src.ep_sim_vertexx;
      ep_sim_vertexy=src.ep_sim_vertexy;
      ep_sim_vertexz=src.ep_sim_vertexz;
    */    
    ep_system=src.ep_system;
    ep_theta=src.ep_theta;
    ep_tof_exp=src.ep_tof_exp;
    ep_tof_mom=src.ep_tof_mom;
    ep_tof_new=src.ep_tof_new;
    ep_tofino_mult=src.ep_tofino_mult;
    ep_track_length=src.ep_track_length;
    ep_z=src.ep_z;
    runnumber=src.runnumber;
    totalmult=src.totalmult;
    trigbit=src.trigbit;
    trigdec=src.trigdec;
    trigdownscale=src.trigdownscale;
    trigdownscaleflag=src.trigdownscaleflag;
  }

  PPimEpEm_ID_buffer(PPimEpEm *src)
  {
    eVert_chi2=src->eVert_chi2;
    eVert_x=src->eVert_x;
    eVert_y=src->eVert_y;
    eVert_z=src->eVert_z;
    event=src->event;
    hneg_mult=src->hneg_mult;
    hpos_mult=src->hpos_mult;
    isBest=src->isBest;
    lneg_mult=src->lneg_mult;
    lpos_mult=src->lpos_mult;
    p_beta=src->p_beta;
    p_beta_new=src->p_beta_new;
    p_dedx_in=src->p_dedx_in;
    p_dedx_in_sigma=src->p_dedx_in_sigma;
    p_dedx_mdc=src->p_dedx_mdc;
    p_dedx_mdc_sigma=src->p_dedx_mdc_sigma;
    p_dedx_out=src->p_dedx_out;
    p_dedx_out_sigma=src->p_dedx_out_sigma;
    p_dedx_tof=src->p_dedx_tof;
    p_id=src->p_id;
    p_isring=src->p_isring;
    p_kIsLepton=src->p_kIsLepton;
    p_kIsUsed=src->p_kIsUsed;
    p_mdcchi2=src->p_mdcchi2;
    p_oa_hadr=src->p_oa_hadr;
    p_oa_lept=src->p_oa_lept;
    p_p=src->p_p;
    p_phi=src->p_phi;
    p_q=src->p_q;
    p_r=src->p_r;
    p_resolution=src->p_resolution;
    p_rkchi2=src->p_rkchi2;
    p_sector=src->p_sector;
    p_shw_sum0=src->p_shw_sum0;
    p_shw_sum1=src->p_shw_sum1;
    p_shw_sum2=src->p_shw_sum2;
    /*
      p_sim_corrflag=src->p_sim_corrflag;
      p_sim_geninfo=src->p_sim_geninfo;
      p_sim_geninfo1=src->p_sim_geninfo1;
      p_sim_geninfo2=src->p_sim_geninfo2;
      p_sim_genweight=src->p_sim_genweight;
      p_sim_id=src->p_sim_id;
      p_sim_iscommon=src->p_sim_iscommon;
      p_sim_mediumid=src->p_sim_mediumid;
      p_sim_p=src->p_sim_p;
      p_sim_parentid=src->p_sim_parentid;
      p_sim_primaryflag=src->p_sim_primaryflag;
      p_sim_processid=src->p_sim_processid;
      p_sim_px=src->p_sim_px;
      p_sim_py=src->p_sim_py;
      p_sim_pz=src->p_sim_pz;
      p_sim_vertexx=src->p_sim_vertexx;
      p_sim_vertexy=src->p_sim_vertexy;
      p_sim_vertexz=src->p_sim_vertexz;
    */    
    p_system=src->p_system;
    p_theta=src->p_theta;
    p_tof_exp=src->p_tof_exp;
    p_tof_mom=src->p_tof_mom;
    p_tof_new=src->p_tof_new;
    p_tofino_mult=src->p_tofino_mult;
    p_track_length=src->p_track_length;
    p_z=src->p_z;
    pim_beta=src->pim_beta;
    pim_beta_new=src->pim_beta_new;
    pim_dedx_in=src->pim_dedx_in;
    pim_dedx_in_sigma=src->pim_dedx_in_sigma;
    pim_dedx_mdc=src->pim_dedx_mdc;
    pim_dedx_mdc_sigma=src->pim_dedx_mdc_sigma;
    pim_dedx_out=src->pim_dedx_out;
    pim_dedx_out_sigma=src->pim_dedx_out_sigma;
    pim_dedx_tof=src->pim_dedx_tof;
    pim_id=src->pim_id;
    pim_isring=src->pim_isring;
    pim_kIsLepton=src->pim_kIsLepton;
    pim_kIsUsed=src->pim_kIsUsed;
    pim_mdcchi2=src->pim_mdcchi2;
    pim_oa_hadr=src->pim_oa_hadr;
    pim_oa_lept=src->pim_oa_lept;
    pim_p=src->pim_p;
    pim_phi=src->pim_phi;
    pim_q=src->pim_q;
    pim_r=src->pim_r;
    pim_resolution=src->pim_resolution;
    pim_rkchi2=src->pim_rkchi2;
    pim_sector=src->pim_sector;
    pim_shw_sum0=src->pim_shw_sum0;
    pim_shw_sum1=src->pim_shw_sum1;
    pim_shw_sum2=src->pim_shw_sum2;
    /*
      pim_sim_corrflag=src->pim_sim_corrflag;
      pim_sim_geninfo=src->pim_sim_geninfo;
      pim_sim_geninfo1=src->pim_sim_geninfo1;
      pim_sim_geninfo2=src->pim_sim_geninfo2;
      pim_sim_genweight=src->pim_sim_genweight;
      pim_sim_id=src->pim_sim_id;
      pim_sim_iscommon=src->pim_sim_iscommon;
      pim_sim_mediumid=src->pim_sim_mediumid;
      pim_sim_p=src->pim_sim_p;
      pim_sim_parentid=src->pim_sim_parentid;
      pim_sim_primaryflag=src->pim_sim_primaryflag;
      pim_sim_processid=src->pim_sim_processid;
      pim_sim_px=src->pim_sim_px;
      pim_sim_py=src->pim_sim_py;
      pim_sim_pz=src->pim_sim_pz;
      pim_sim_vertexx=src->pim_sim_vertexx;
      pim_sim_vertexy=src->pim_sim_vertexy;
      pim_sim_vertexz=src->pim_sim_vertexz;
    */    
    pim_system=src->pim_system;
    pim_theta=src->pim_theta;
    pim_tof_exp=src->pim_tof_exp;
    pim_tof_mom=src->pim_tof_mom;
    pim_tof_new=src->pim_tof_new;
    pim_tofino_mult=src->pim_tofino_mult;
    pim_track_length=src->pim_track_length;
    pim_z=src->pim_z;
    em_beta=src->em_beta;
    em_beta_new=src->em_beta_new;
    em_dedx_in=src->em_dedx_in;
    em_dedx_in_sigma=src->em_dedx_in_sigma;
    em_dedx_mdc=src->em_dedx_mdc;
    em_dedx_mdc_sigma=src->em_dedx_mdc_sigma;
    em_dedx_out=src->em_dedx_out;
    em_dedx_out_sigma=src->em_dedx_out_sigma;
    em_dedx_tof=src->em_dedx_tof;
    em_id=src->em_id;
    em_isring=src->em_isring;
    em_kIsLepton=src->em_kIsLepton;
    em_kIsUsed=src->em_kIsUsed;
    em_mdcchi2=src->em_mdcchi2;
    em_oa_hadr=src->em_oa_hadr;
    em_oa_lept=src->em_oa_lept;
    em_p=src->em_p;
    em_phi=src->em_phi;
    em_q=src->em_q;
    em_r=src->em_r;
    em_resolution=src->em_resolution;
    em_rkchi2=src->em_rkchi2;
    em_sector=src->em_sector;
    em_shw_sum0=src->em_shw_sum0;
    em_shw_sum1=src->em_shw_sum1;
    em_shw_sum2=src->em_shw_sum2;
    /*
      em_sim_corrflag=src->em_sim_corrflag;
      em_sim_geninfo=src->em_sim_geninfo;
      em_sim_geninfo1=src->em_sim_geninfo1;
      em_sim_geninfo2=src->em_sim_geninfo2;
      em_sim_genweight=src->em_sim_genweight;
      em_sim_id=src->em_sim_id;
      em_sim_iscommon=src->em_sim_iscommon;
      em_sim_mediumid=src->em_sim_mediumid;
      em_sim_p=src->em_sim_p;
      em_sim_parentid=src->em_sim_parentid;
      em_sim_primaryflag=src->em_sim_primaryflag;
      em_sim_processid=src->em_sim_processid;
      em_sim_px=src->em_sim_px;
      em_sim_py=src->em_sim_py;
      em_sim_pz=src->em_sim_pz;
      em_sim_vertexx=src->em_sim_vertexx;
      em_sim_vertexy=src->em_sim_vertexy;
      em_sim_vertexz=src->em_sim_vertexz;
    */    
    em_system=src->em_system;
    em_theta=src->em_theta;
    em_tof_exp=src->em_tof_exp;
    em_tof_mom=src->em_tof_mom;
    em_tof_new=src->em_tof_new;
    em_tofino_mult=src->em_tofino_mult;
    em_track_length=src->em_track_length;
    em_z=src->em_z;
    ep_beta=src->ep_beta;
    ep_beta_new=src->ep_beta_new;
    ep_dedx_in=src->ep_dedx_in;
    ep_dedx_in_sigma=src->ep_dedx_in_sigma;
    ep_dedx_mdc=src->ep_dedx_mdc;
    ep_dedx_mdc_sigma=src->ep_dedx_mdc_sigma;
    ep_dedx_out=src->ep_dedx_out;
    ep_dedx_out_sigma=src->ep_dedx_out_sigma;
    ep_dedx_tof=src->ep_dedx_tof;
    ep_id=src->ep_id;
    ep_isring=src->ep_isring;
    ep_kIsLepton=src->ep_kIsLepton;
    ep_kIsUsed=src->ep_kIsUsed;
    ep_mdcchi2=src->ep_mdcchi2;
    ep_oa_hadr=src->ep_oa_hadr;
    ep_oa_lept=src->ep_oa_lept;
    ep_p=src->ep_p;
    ep_phi=src->ep_phi;
    ep_q=src->ep_q;
    ep_r=src->ep_r;
    ep_resolution=src->ep_resolution;
    ep_rkchi2=src->ep_rkchi2;
    ep_sector=src->ep_sector;
    ep_shw_sum0=src->ep_shw_sum0;
    ep_shw_sum1=src->ep_shw_sum1;
    ep_shw_sum2=src->ep_shw_sum2;
    /*
      ep_sim_corrflag=src->ep_sim_corrflag;
      ep_sim_geninfo=src->ep_sim_geninfo;
      ep_sim_geninfo1=src->ep_sim_geninfo1;
      ep_sim_geninfo2=src->ep_sim_geninfo2;
      ep_sim_genweight=src->ep_sim_genweight;
      ep_sim_id=src->ep_sim_id;
      ep_sim_iscommon=src->ep_sim_iscommon;
      ep_sim_mediumid=src->ep_sim_mediumid;
      ep_sim_p=src->ep_sim_p;
      ep_sim_parentid=src->ep_sim_parentid;
      ep_sim_primaryflag=src->ep_sim_primaryflag;
      ep_sim_processid=src->ep_sim_processid;
      ep_sim_px=src->ep_sim_px;
      ep_sim_py=src->ep_sim_py;
      ep_sim_pz=src->ep_sim_pz;
      ep_sim_vertexx=src->ep_sim_vertexx;
      ep_sim_vertexy=src->ep_sim_vertexy;
      ep_sim_vertexz=src->ep_sim_vertexz;
    */    
    ep_system=src->ep_system;
    ep_theta=src->ep_theta;
    ep_tof_exp=src->ep_tof_exp;
    ep_tof_mom=src->ep_tof_mom;
    ep_tof_new=src->ep_tof_new;
    ep_tofino_mult=src->ep_tofino_mult;
    ep_track_length=src->ep_track_length;
    ep_z=src->ep_z;
    runnumber=src->runnumber;
    totalmult=src->totalmult;
    trigbit=src->trigbit;
    trigdec=src->trigdec;
    trigdownscale=src->trigdownscale;
    trigdownscaleflag=src->trigdownscaleflag;

  }
};
#endif
